### ISSUE TITLE
Option: Edit uploaded metadata

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#10]
I noticed when metadata has been either created or uploaded there is no option to edit it once it is saved within geoportal.  
Current options include;  Upload Metadata, Change Owner, Delete Item

The 1.2.x version had the capability to **edit any of the entries once uploaded.**  
Is there a way to switch this on?  Otherwise I would like to make a request to include this in a future version.

**Comment by umacgillivray** [comment]
[geoportal]/app/context/metadata-editor.js
// set this to true
allowNonGxeDocs: true,

**Comment by MapZombie** [comment]
Great, that worked.  Thank you.
