### ISSUE TITLE
is toKnownXslt implemented

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#102]
I see in evaluator.js that there is a 'toKnownXslt' key on the object for the ISO19115 scheme. If I put a path for an xslt in here will it get executed on the incoming metadata, as in geoportal v1?

**Comment by umacgillivray** [comment]
Yes it will. The resulting xml will then be evaluated.

**Comment by smrgeoinfo** [comment]
I finally got to testing this, and got this error:

> Could not make xslt template from: /DataciteToISO19139v3.2.xslt

What XSLT processor is Geoportal using?  My stylesheet is xslt v1.0, I've developed and tested using Oxygen and Xalan.
