### ISSUE TITLE
pre configure the map panel to display selected data

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#103]
I'd like to configure the map panel to start our with some of our IEDA web services in the table of contents for the map panel, but can't see how to engineer that. Is it possible?

**Comment by umacgillivray** [comment]
The viewer is built using the Web AppBuilder for ArcGIS. You could create a WebMap with your own data layers using ArcGIS Online, share the WebMap with "Everyone", then configure Geoportal to use it.

[tomcat]/webapps/geoportal/viewer/config.json

// this is the portal url 
"portalUrl": "http://www.arcgis.com",

// this is the WebMap id
"itemId": "6e03e8c26aad4b9c92a87c1063ddb0e3",

**Comment by smrgeoinfo** [comment]
@umacgillivray thanks for the info. We've found a number of other problems using the map panel and are going to hide it in our IEDA geoportal for now.
