### ISSUE TITLE
Can we add csv to a map?

### ISSUE THREAD

**Issue by otwn** [Esri/geoportal-server-catalog#105]
Geoportal works fine and collects metadata for csv file and create a link.
Unfortunately "Add to Map" fails to load a csv file and says "Unable to load: http://.....csv"

I opened arcgis.com "http://www.arcgis.com/home/webmap/viewer.html?useExisting=1" and drag and drop the same csv file. I also used "add layer from web" and pasted the same url on geoportal. It worked. 

Assuming WebApp Builder has the same function, I hope to see the csv data on a map. CSV file contains around 4000 rows.

**Comment by zguo** [comment]
currently "add to map" only add map services to the map viewer, it does not add csv files to map,  you might check if web app builder have some existing widget let user add csv files to the map.
