### ISSUE TITLE
harvest from NASA Common Metadata Repository (CMR)

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#106]
The GCMD (part of CMR) repository implements a custom harvest process described at https://wiki.earthdata.nasa.gov/display/CMR/CMR+Harvesting+Best+Practices.  Has anyone implemented a harvester to harvest from the NASA CMR to a Geoportal?

**Comment by mhogeweg** [comment]
I would implement this specific harvesting scheme in a dedicated python script that publishes to the Geoportal Server API.
