### ISSUE TITLE
Error when uploading metadata to geoportal server 2.5.1

### ISSUE THREAD

**Issue by sukeshlaghate** [Esri/geoportal-server-catalog#107]
Hi,
I followed the steps mentioned in the Installing Geoportal Server 2.5.0 wiki site.
I was able to successfully install geoportal Server 2.5.1 with simple authentication. However, when I tried to create and save a new metadata it fails and issues 502 and 500 errors, following is the debug window message
```
  Failed to load resource: the server responded with a status of 502 (Bad Gateway)
SearchPane.js:155 search-error
(anonymous) @ SearchPane.js:155
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at json (init.js:147)
    at n (init.js:146)
    at d.f [as handleResponse] (init.js:138)
    at XMLHttpRequest.e (init.js:143)
```
followed by 
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
MetadataEditor.js:173 SaveMetadata.error f
(anonymous) @ MetadataEditor.js:173
```
Any help in resolving this issue is much appreciated.

**Comment by sukeshlaghate** [comment]
Hi 
I tried to reinstall elastic search and geoportal 2.5.1. still the issue persists. attached is the log file dump and elastic search settings (yml) that i have created on my local node. I noticed that the log file for geoportal  states 
```
 failed to get node info for {#transport#-1}{GFhwOFifT2698N7xqKjkCA}{ril150666kb152}{192.168.56.1:9300}, disconnecting...
org.elasticsearch.transport.NodeDisconnectedException: [][192.168.56.1:9300][cluster:monitor/nodes/liveness] disconnected
2017-12-01 15:44:13,838 DEBUG [com.esri.geoportal.lib.elastic.ElasticContext] - Checking index: metadata
2017-12-01 15:44:13,851 ERROR [com.esri.geoportal.lib.elastic.ElasticContext] - Error executing ensureIndex()
```

elastic search yml is 

```
bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: RIL150666KB152
path.data: C:\ProgramData\Elastic\Elasticsearch\data
path.logs: C:\ProgramData\Elastic\Elasticsearch\logs
transport.tcp.port: 9300
transport.host: 192.168.56.1
http.host: 127.0.0.1
```

Request you to help in resolving this issue.
Thank you in advance.
[geoportal.log](https://github.com/Esri/geoportal-server-catalog/files/1521204/geoportal.log)

**Comment by umacgillivray** [comment]
A few questions. 
What version of Elasticsearch are you running?
Is it running on the same machine as Geoportal?
You can check  the version with:  http://host:9200

You configure the Elasticsearch host within:
[tomcat]/webapps/geoportal/WEB-INF/classes/config/app-context.xml
By default it uses "localhost", you may need to change this if Elasticsearch is running on a different machine.

**Comment by sukeshlaghate** [comment]
Hi umacgillivray ,
Thank you for responding. Please find answers below:
What version of Elasticsearch are you running? 5.6.4
Is it running on the same machine as Geoportal? Yes on same machine.

running following command in windows cmd shell
`curl -XGET localhost:9200/_cat/health`
returns green status which i believe means elastic search is working fine.
```
epoch      timestamp cluster       status node.total node.data shards pri relo init unas
sign pending_tasks max_task_wait_time active_shards_percent
1512372708 13:01:48  elasticsearch green           1         1      0   0    0    0
   0             0                  -                100.0%
```

Any insights on resolving this issue is much appreciated.

**Comment by zguo** [comment]
it could some issue between geoportal 2.5.1  (uses Elasticsearch client 5.1.1) and Elasticsearch 5.6.4, we haven't test that combination yet, possible upgrading the client jar to 5.6.4 might resolve the issue, alternatively you might try an earlier version of Elasticsearch.

**Comment by sukeshlaghate** [comment]
Hi Zguo and Umacgilivray,

Thank you for responding. We cleaned up the machines and re-installed in order starting with tomcat 8.0, then elastic search 5.6.4, and finally Geoportal-server-catalog 2.5.1 with geoportal search. This solved the issue and we are able to run the searchs. I have issue with geoportalsearch for which I am opening another issue.

Thanks for your help.
