### ISSUE TITLE
Where is the Publish link in Geoportal server 2.5.1

### ISSUE THREAD

**Issue by sukeshlaghate** [Esri/geoportal-server-catalog#108]
Hi 
I was wondering where has Publish link for publishing resources has gone in Geoportal server 2.5.1.
In previous version i.e. 1.2.9 a publisher could see an option to publish the resource. However in Geoportal server 2.5.1 I see only two options viz create metadata and upload metadata option. Am I missing some configuration setting to enable publish resource?

**Comment by zguo** [comment]
Most of publishing function are now handled by a separate harvester application, the app is available at https://github.com/Esri/geoportal-server-harvester.
