### ISSUE TITLE
GeoportalSearch in MapPanel doesn't show all results

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#111]
search for langseth AND "Seismic navigation" AND MGL1111 at http://catalog-dev.iedadata.org:8080/geoportal/#  (note this is dev, likely to change content...) in the searchPanel, I get three results, and all three are listed.
If I do the same search using the GeoPortalSearch widget in the Map panel, it report three hits, but only two display. The first record shown in the searchPanel doesn't show up in the GeoportalSearch results list. 

If I upload a test record with the text 'zzyzzx', and search for 'zzyzzx', I the record shows up in the search panel but not the GeoportalSearch on the map panel. I suspect its the same problem

**Comment by zguo** [comment]
Geoportal 2.6.2 included a new search widget, suggest to upgrade and try if the same issue still there, did a quick search on a test instance, result seems to be consistent.
