### ISSUE TITLE
featureRequest: 'Zoom To' link in MapPanel Geoportal Search results list 

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#112]
In the MapPanel, using the Geoportal Search widget, bounding boxes for results are shown, and if you click on a box, a pop up is displayed with the title and abstract, and a 'Zoom To' link at the bottom. It would be much more useful if this 'zoom to' link showed up with the links under the abstract in the search results listing of the Geoportal Search widget itself.   I haven't been able to figure out how the 'Zoom To' function is implemented in the pop-up...

**Comment by zguo** [comment]
"Zoom to" function has been added to the search widget.
