### ISSUE TITLE
geoportalsearch results does not list add to map for local geoportal2.x

### ISSUE THREAD

**Issue by sukeshlaghate** [Esri/geoportal-server-catalog#116]
Hi
I am using geoportal 2.5.1 with elastic search 5.6.4.
I configured geoportalsearch widget for mapviewer by providing following in config.json
```
{
       "url": "http://localhost:8081/geoportal/rest/metadata/search",
       "name": "Local Geoportal",
       "gptversion":2
}
```
restarting geoportal and the geoportalsearch widget starts to list my local geoportal in the catalog dropdown. 
Following are the issues that I am facing

1. When providing keywords it does not return any results. The same search when performed from search tab shows result with "addtomap" enabled. clicking the link adds the map in the map viewer

2. when keywords field is kept empty and search is performed;  It fetches and displays results with foot print however the result does not show "addtomap" link. 

refer to attached screen shots
![geoportalsearch_withkeyword](https://user-images.githubusercontent.com/25061957/33794603-cb407aa0-dcf4-11e7-8eac-1e203f15a241.png)
![geoportalsearch_withoutkeyword](https://user-images.githubusercontent.com/25061957/33794604-cb7f51d0-dcf4-11e7-9bfe-8699e96b0940.png)
![searchpanel_withkeyword](https://user-images.githubusercontent.com/25061957/33794605-cbbbd1a0-dcf4-11e7-940c-c99333d93842.png)

Can anyone please help me in resolving the issue?

**Comment by dawitkk** [comment]
The widget is not working for me when I add this into the catalog config_geoportalsearch.json
{
       "url": "http://localhost:8080/geoportal/rest/metadata/search",
       "name": "GP",
       "gptversion":2
}
Any help is appreciated...

**Comment by DeveshScientist** [comment]
@dawitkk  You have to change https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/viewer/widgets/GeoportalSearch/views/SearchPane.js

and

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/viewer/widgets/GeoportalSearch/common/QueryTask.js .

then it will work like a charm

**Comment by dawitkk** [comment]
@Devesh Kumar Thank you so much!

**Comment by rmuellerjr** [comment]
> @dawitkk You have to change https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/viewer/widgets/GeoportalSearch/views/SearchPane.js
> 
> and
> 
> https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/viewer/widgets/GeoportalSearch/common/QueryTask.js .
> 
> then it will work like a charm

What exactly do you need to change to make this work?

**Comment by dawitkk** [comment]
@DeveshScientist  Thank you sir!

**Comment by dawitkk** [comment]
@rmuellerjr replace old with these two files

**Comment by rmuellerjr** [comment]
Gottcha. Thanks
