### ISSUE TITLE
configuration/evaluators for DataCite XML

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#118]
Has anyone set up a configuration for harvesting DataCite XML?

**Comment by mhogeweg** [comment]
do you have an example or an API endpoint we can look at?

**Comment by smrgeoinfo** [comment]
here's a WAF with lots of examples:
http://get.iedadata.org/metadata/DataCite/ECL/

**Comment by mhogeweg** [comment]
ok. this would require configuring a metadata schema for this type of XML. that is possible, but will take some time. Good thing they have their schema documented: http://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf. 

The configuration of an XML schema is different from the geoportal 1.x process although following the same process. I could start a basic editor (perhaps for the minimal mandatory fields) and then hand it over to you? the point is to just be able to index these, or also to be able to edit them?

**Comment by smrgeoinfo** [comment]
At this point we just need to harvest/index, not edit. What I'm currently doing is transforming the DataCite to ISO XML and harvesting that; I've thought about putting the toISO xslt in the evaluator flow (toKnowXSLT) and harvesting the DataCite records that way, but the cleanest way would be to have a configuration for indexing the dataCite directly.  I've done some looking at what's involved, but it looked like a big job.   If there's not already something existing, I'll try the toKnownXSLT approach first.  (side track...) It would be nice if the portal could offer DataCite XML and ISO XML as output formats.

**Comment by mhogeweg** [comment]
I have created a start of a DataCite editor. You’ll see this in the /metadata/app/gxe/types/datacite folder.
this zip is a standalone editor, but you can take the datacite folder and include in your Geoportal 2.5.x.
include the type definition from the editor.html into this file:
…\geoportal\WEB-INF\classes\metadata\js\Evaluator.js
then to index elements, you’ll need to write an evaluator for DataCite (following one of the other types examples).
I’ll continue working on this, but wanted to share the first step (editor is itself also not complete yet).

[metadata 20180128.zip](https://github.com/Esri/geoportal-server-catalog/files/1671791/metadata.20180128.zip)

**Comment by smrgeoinfo** [comment]
Thanks Marten, I’ll check it out. The Evaluator is the bit that’s holding me up—Since I already have an xslt to transform DataCite to ISO19139, I was trying the short cut of catching the DataCite metadata and using ‘toKnownXslt’ property in the evaluator to change to ISO and process that way. Unfortunatly now I’m stuck because the XSLT can’t load (see  #121 )
