### ISSUE TITLE
Configure geoportal instance to work with filtered set of records from index

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#119]
We're deploying a Geoportal to integrated metadata from several partner systems here at the Interdisciplinary Earth Data Alliance (http://app.iedadata.org/catalog).  We also want to set up a catalog instance specific to one of the partner systems; I'd like to connect to the same ElasticSearch backend, but filter the index to only see records from that system.  The effect would be like having one of the facets in the 'Partner system' section always selected.   Is there some way to configure a Geoportal instance to provide such a filtered view?

**Comment by smrgeoinfo** [comment]
@mhogeweg @umacgillivray, I'm under pressure to get this working, can you give me any leads?  Sorry to be a pest!

**Comment by mhogeweg** [comment]
I'll follow up with Urban on this in the morning.

**Comment by smrgeoinfo** [comment]
Thanks, I appreciate the help.  I'm trying to figure out the code in the app/search folder and its slow going...

**Comment by umacgillivray** [comment]
A couple of options.

1. You can modify the search page to filter all results.

2. Elasticsearch can have multiple indexes. Each Geoportal app can point to a different index within the same Elasticsearch.

Option 1

A filter is already supported on the URL, e.g.: 
http://host:port/geoportal?filter=title:data
All searches will be filtered for documents that have "data" in the title.

You could modify the search page to do this without having a filter paramater on the URL.
[tomcat]/webapps/geoportal/app/search/PageUrlFilter.js

    postCreate: function() {
      this.inherited(arguments);

      // add this line
      this._addQuery("title:data");

Option 2

You can have multiple Geoportal applications each pointing to a different index within the same Elasticsearch.

[tomcat]/webapps/anothergeoportal/WEB-INF/classes/config/app-context.xml

    <beans:property name="indexName" value="metadata" />

    

    <beans:property name="indexName" value="anotherindex" />

[tomcat]/webapps/anothergeoportal/WEB-INF/classes/config/app-security.xml

    <security:intercept-url pattern="/elastic/metadata/_count/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/metadata/*/_count/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/metadata/_search/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/metadata/*/_search/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/metadata/_mappings/**" method="GET" access="permitAll" />
    <security:intercept-url pattern="/elastic/metadata/*/_mappings/**" method="GET" access="permitAll" />

    

    <security:intercept-url pattern="/elastic/anotherindex/_count/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/anotherindex/*/_count/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/anotherindex/_search/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/anotherindex/*/_search/**" access="permitAll" />
    <security:intercept-url pattern="/elastic/anotherindex/_mappings/**" method="GET" access="permitAll" />
    <security:intercept-url pattern="/elastic/anotherindex/*/_mappings/**" method="GET" access="permitAll" />

You'll need to restart Tomcat.

**Comment by smrgeoinfo** [comment]
@umacgillivray THANKS!  I used option 1 and it works like a charm.
