### ISSUE TITLE
problem with EC2 geoportal deployment

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#120]
I'm trying to deploy v2.5.0 iedadata fork to a new Centos7.3 build on an Amazon EC2 instance. 
I'm using the same code base for the war file that's currently running on a CentOS 7.3 Linode vm (http://catalog-dev.iedadata.org:8080/geoportal/), just had to update the cluster name and changed node location to localhost from the host name for the other instance. Elasticsearch is up and running, the geoportal war deploys OK, last entries in geoportal.log are
 DEBUG [com.esri.geoportal.lib.elastic.ElasticContext] - Checking index: metadata
 INFO [com.esri.geoportal.context.GeoportalContext] - Starting up GeoportalContext...
 
when I open the web page, the app progress bar appears, but that's all that happens, the web site never opens.   I'm stumped. Nothing in the log files indicates a problem.

**Comment by mhogeweg** [comment]
Anything in the browser console or network traffic view?

**Comment by smrgeoinfo** [comment]
In the console there's a GET for WorkbenchPanel.js that gets a 404, but the panel is never invoked to display, I don't think thats the problem.
then get
<pre>
init.js:10 Uncaught Error: xhrFailed
    at d (init.js:10)
    at Function.q.getText (init.js:14)
    at qa (init.js:32)
    at a (init.js:10)
    at init.js:19
    at ja (init.js:28)
    at na (init.js:19)
    at init.js:33
    at a (init.js:10)
    at Xa (init.js:33)
</pre>

In the network view, init.js is initiating a lot of calls to other js and html (types script, xhr), all 200's; last one is MappedTextBox.js.  (type script) from init.js:35.

In my working Geoportal, that call is followed by geoportal (type xhr), MapServer?f=json (type xhr), then a bunch of font, png, and jpeg calls.

**Comment by smrgeoinfo** [comment]
I changed SELinux directive from 'enforce'd to 'permissive', and relaxed permissions on /opt/tomcat.   Harvester works now, and seems to harvest to the geoportal Instance, but when I try to open the geoportal site it still hangs at the same place.

**Comment by mhogeweg** [comment]
the tomcat itself is running: http://52.54.48.218:8080/ but geoportal itself is not showing and neither is a static image like http://geoss.esri.com/geoportal2/images/favicon.ico shows.

can you confirm there's the Catalina/localhost/geoportal.xml configured etc?

**Comment by smrgeoinfo** [comment]
Oops, the instance I'm testing is named geoportalAWS.
Investigations this morning show message that keeps showing up in the geoportal.log
2018-01-23 08:46:32,900 INFO [org.elasticsearch.client.transport.TransportClientNodesService] - failed to connect to node [{#transport#-1}{7juPEnrtSSqO5PvDtI47Bw}{localhost}{127.0.0.1:9300}], removed from nodes list
org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:9300] connect_timeout[30s]
....
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:9300

but netstat -tulpn shows
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      1030/java
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      1030/java

so the net is listening for localhost on 9300, ES is running 

I'm suspicious that the problem has something to do with SELinux on CentOS so I disabled SELinux and rebooted, didn't solve problem.

**Comment by smrgeoinfo** [comment]
On my working CentOS 7.3 instance, in the app-context file, if the Elasticsearch node is identified with the host name that has a DNS mappign to the the instance, things work
<beans:value>catalog-dev.iedadata.org</beans:value>

but if I change the beans:value to 'localhost', I get the ' failed to connect to node' error.  I thought localhost was the default value?
				<beans:value>localhost</beans:value>

I don't have a registered host name for the Amazon test instance I've been working on; I've tried the Amazon host name that EC2 provides, localhost, and 127.0.0.1, none of those worked.

**Comment by smrgeoinfo** [comment]
OK, I'm not sure what fixed things but
I made a new Geoportal Build from the source project and deployed the new war
in etc/elasticsearch/elasticsearch.yml
network.host=localhost
http.port=9200
in app-context.xml use localhost as the host name for the elastic search nodes. 
restart Elastic, restart tomcat.
now it works.

**Comment by smrgeoinfo** [comment]
Closing; actual problem not clearly isolated. too bad.
