### ISSUE TITLE
could not make xslt template-- toKnownXSLT

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#121]
I'm trying to insert an XSLT to process harvested records using toKnowXSLT in  evaluator.js, and got this error:

> Could not make xslt template from: /DataciteToISO19139v3.2.xslt

What XSLT processor is Geoportal using?  My stylesheet is xslt v1.0, I've developed and tested using Oxygen and Xalan.

[Heres the xslt I want to run](https://github.com/iedadata/resources/blob/master/DataCiteXMLTransforms/DataciteToISO19139v3.2.xslt)
In the geoportal, its in the same directory with the evaluator.js files.

**Comment by smrgeoinfo** [comment]
I'm testing  by logging in as geoportal admin, then using the 'upload' function to upload a DataCite XML record. I substituted a [minimal xslt](https://github.com/iedadata/resources/blob/master/DataCiteXMLTransforms/simpletransform.xslt) to test if its a problem with xslt complexity, and got the same message. I think the problem is in the xslt processing by the geoportal?

**Comment by valentinedwv** [comment]
Is it a path issue?
eg 
metadata/js/DataciteToISO19139v3.2.xslt

**Comment by valentinedwv** [comment]
working on trying to get it working in the command line version:

javax.xml.transform.TransformerException: java.lang.RuntimeException: Use of the extension function 'http://exslt.org/dates-and-times:dateTime' is not allowed when the secure processing feature is set to true.

**Comment by valentinedwv** [comment]
But then there is a nasty inf loop in Metadata document

`
public void interrogate() throws UnrecognizedTypeException, Exception {
    setXml(XmlUtil.identity(getXml())); // TODO may not be xml based
    if (hasXml()) ensureDom();
    Evaluator evaluator = GeoportalContext.getInstance().getBeanIfDeclared(
        "metadata.Evaluator",Evaluator.class,new Evaluator());
    evaluator.interrogate(this);
    
    // execute an immediate transformation if required
    if (getMetadataType() != null) {
      String toKnownXslt = getMetadataType().getToKnownXslt();
      if (toKnownXslt != null && toKnownXslt.length() > 0) {
        XsltTemplate xsltTemplate = XsltTemplates.getCompiledTemplate(toKnownXslt);
        String result = xsltTemplate.transform(getXml());
        setXml(result);
        interrogate();
      }
    } else {
      throw new UnrecognizedTypeException();
    }
`

**Comment by valentinedwv** [comment]
MetadataType  is always the original MD type.
