### ISSUE TITLE
CSS Modify Search Results Description Height (Option)

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#124]
_**Optional Display**_
We created a CSS style to make each **description** a consistent size and make it easier to scan the list of results. This cuts off the text if it goes on too long.  This allows three lines of text to display.  A person could figure out how to "collapse" the description, but this is a quick fix.  

```
/* Style for descriptions creates a cap of a few lines of text  */
.g-item-card .g-item-description {
	max-height: 46px;
	overflow: hidden;
        width: 85%;
}
```

**Comment by umacgillivray** [comment]
@KathleenPate  Thanks, we added this to our main.css;
