### ISSUE TITLE
Metadata Display:  HTML display of xml & Jump to Anchors

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#127]
### **How do I build hyperlinks to _Contact Information_ in HTML ISO Display?**

I used the _Standalone Editor_ to write some ISO metadata; and discovered it previews HTML with two hyperlinks at the top which are very helpful. The ISO metadata I uploaded does not have these anchors in the html display. _**How can we code our XML to prompt the Portal to create these hyperlinks??**_

EXAMPLE of SourceCode of ISO display:
```
<a name="title">Metadata Title</a><a name="title"></a><br><br>
<a href="#identificationInfo"><span style="text-transform: capitalize;">Identification Information</span></a>
<a href="#distributionInfo"><span style="text-transform: capitalize;">Distribution Information</span></a><br>
<hr><pre><b>Metadata: </b></pre>
...
<a name="identificationInfo"> 
...
<a href="#title">Return To Index</a>
<a name="distributionInfo">  Distribution info: </a>
 <b>    Distribution: </b>
 <b>        Digital transfer options: </b>

```

It would be very helpful if someone on the ADMIN team could publish at least one ISO record in the SandBox for testing purposes. I enclose a public ISO metadata record that you can publish in the SandBox. :)

https://geodiscover.alberta.ca/geoportal/csw?getxml=%7BCB1D2FBD-4695-4CAC-ACCD-40DB2774F23D%7D

**Comment by pandzel** [comment]
It appears to be a bug in XSLT. #283 fixes that.

**Comment by zguo** [comment]
Thanks.
