### ISSUE TITLE
ElasticSearch 2.x only

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#13]
Since the code uses the direct connect, it needs to be emphasized that Elasticsearch must be 2.X 

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html
(The client must have the same major version (e.g. 2.x, or 5.x) as the nodes in the cluster.)

https://github.com/Esri/geoportal-server-catalog/wiki/Installing-Geoportal-Server-2.0.1

**Comment by umacgillivray** [comment]
I modified the prerequisite text:
Install Elasticsearch (2.3.3 or higher, this will only work with a 2.X version of Elasticsearch)
