### ISSUE TITLE
iso19115-2 Not finding anchors

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#14]
We are using the NOAA NODC style Anchors. These are not being transformed to keywords:
http://hydro10.sdsc.edu/metadata/NODC/00026049-853D-4C29-B621-F7AD2470AC21.xml

http://132.249.238.151:8080/cinergi/waf/CZO_Datasets/http_____71_185_29_35__stroudwater__StroudData__chemistry__CZO_CRB_WCC_0110_CHEM_AUTO_HEADER_csv.xml

```
<gmd:descriptiveKeywords>
<!--Cinergi keyword enhanced at Sat Jun 25 02:00:45 UTC 2016-->
<gmd:MD_Keywords>
<gmd:keyword>
<gmx:Anchor xlink:href="http://sweet.jpl.nasa.gov/2.3/realmHydro.owl#HydrosphereFeature">Creek</gmx:Anchor>
</gmd:keyword>
<gmd:keyword>
<gmx:Anchor xlink:href="http://sweet.jpl.nasa.gov/2.3/realmHydro.owl#HydrosphereFeature">River</gmx:Anchor>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme">theme</gmd:MD_KeywordTypeCode>
</gmd:type>
<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>Feature > Hydrologic Feature</gco:CharacterString>
</gmd:title>
<gmd:date>
<gmd:CI_Date>
<gmd:date>
<gco:Date>2016-06-25</gco:Date>
</gmd:date>
<gmd:dateType>
<gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
</gmd:dateType>
</gmd:CI_Date>
</gmd:date>
<gmd:otherCitationDetails>
<gco:CharacterString>Cinergi keyword enhanced at Sat Jun 25 02:00:45 UTC 2016</gco:CharacterString>
</gmd:otherCitationDetails>
</gmd:CI_Citation>
</gmd:thesaurusName>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>

```

**Comment by valentinedwv** [comment]
So that would be modifying EvaluatorFor_ISO.js?
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/metadata/js/EvaluatorFor_ISO.js

**Comment by umacgillivray** [comment]
Yes that's right. The JavaScripts are run with the Nashorn engine. They mostly use convenience methods from EvaluatorBase.js. "G" is simply a global initially defined within EvaluatorBase.js. Evaluator.js is the main script, it defines the xml types, interrogates, and executes appropriately (iso vs fgdc vs ...). The process is kicked off by the Java class: https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/java/com/esri/geoportal/base/metadata/Evaluator.java
