### ISSUE TITLE
Sanbox Site Down since 2.5.2

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#147]
Hello, For the past few days the San(D)box site is not loading. (there is a typo on the GIT-hub page of the word sandbox) I presume the site is down because of the newest updates to 2.5.2. I wanted to see what the "preview" feature looked like. Can someone take a look at the server and get it restarted? _Thanks_. Kathleen

**Comment by mhogeweg** [comment]
hi, sorry for the invoncenience. the sandbox sites are back up:
1.2.9 - https://gptogc.esri.com
2.5.2 - http://geoss.esri.com/geoportal2
