### ISSUE TITLE
How to get  records after startPosition 10000

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#148]
Both the CSW and OpenSearch API requests fail when the 'startPosition' or 'from' parameter is >10,000. I'm assuming this is related to the ElasticSearch limit on number of records returned.  We have a catalog with >1,000,000 records, and I need to page through these to gather the file identifiers.   Any suggestions?

**Comment by pandzel** [comment]
You are correct; Elastic has a default limit of records returned in search set to 10k. It is possible to increase this limit (index.max_result_window) as mentioned here: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/index-modules.html.

Better solution is a scrolling API as described here: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-scroll.html. This is actually what harvester is doing. You can access scroll API available for geoportal through <geoportal>/elastic/_search/scroll/ mapping. You need a publisher credentials to access it, or you can change access policy to that endpoint in app-security.xml.

**Comment by smrgeoinfo** [comment]
Thanks Piotr, I'll use that, maybe even use the code from harvester
