### ISSUE TITLE
ItemCard Modification:  Added link to Resource Title

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#169]
Our User base requested a link to the readable (html) metadata for the **search results _Title_** on the Item card. I copied the render code from the ItemsLink function and applied it to the Title. Now clients can click right on the title to review the metadata.  :-)

**ItemCard.js** (webappp/app/search/ItemCard.js)
Insert at line 285 - after _renderItemLinks:
```
    _renderTitleLink: function(itemId,item) {
        var titleNode = this.titleNode;
        var uri = "./rest/metadata/item/"+encodeURIComponent(itemId);
        var htmlNode = domConstruct.create("a",{
          href: uri+"/html",
          target: "_blank",
          innerHTML: item.title
        },titleNode);
    },
```
replace line 99 for set Title text
`      this._renderTitleLink(hit._id,item);`

Sharing in case your clients have the same request.

**Comment by zguo** [comment]
Thanks, this has been added into the code.
