### ISSUE TITLE
Configure group access for simple authentication

### ISSUE THREAD

**Issue by mathieufortier** [Esri/geoportal-server-catalog#173]
Hi,
I don't understand this part, for Geoportal 2.6.
If I have 2 users like this:
<security:user authorities="ROLE_PUBLISHER" password="user1" name="user1"/>
<security:user authorities="ROLE_PUBLISHER" password="user2" name="user2"/>
How can I create group "department1" and asign "user1" and "user2" in this group? I tried that but it's wot working:
<security:user authorities="ROLE_PUBLISHER,user1,user2" password="department1" name="department1"/>

In "Set Access" I can see "Share with Groups", but it is always empty? How can I manage this?

Thanks in advance,
Mathieu

**Comment by mathieufortier** [comment]
Hi everyone,

I succeded. If you create new Metadata with user "department1" you can share with "user1" and "user2" by clicking "Set Access". If i'm putting "Private access" when I log with "user1" or "user2" I can't see the metadata?? What is the benefit to "share"? In witch action or function??

Thanks,
Mathieu

**Comment by zguo** [comment]
Following is an example might help:

`        
  <security:user name="deptadmin" password="deptadmin" authorities="department1, department2" /> 
  <security:user name="user1" password="user1" authorities="department1" /> 
  <security:user name="user2" password="user2" authorities="department2" /> 
`

In the above case, if deptadmin set a record to private and share with department1, user1 will be able to see the record as it is in department1, user2 will not be see the record as it is in department2.

Thanks,

ZhongPing

**Comment by mathieufortier** [comment]
Working good! 
Thanks for the precision!
Mathieu
