### ISSUE TITLE
How to: Add two filters on SearchPanel under one Title

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#177]
**How can I collect terms from two metadata fields shown as one Filter**. I have tried various logic models and it hasn't worked for me. I only get one or the other or none at all. I need to know the syntax to pull two fields.

**E.G** I want to pull data _file types_ from FGDC and ISO metadata.  Below is a sample I tried which did not work. 

```
<div data-dojo-type="app/search/TermsAggregation"
  data-dojo-props="field:'contentType_s'||field:'apiso_Type_s',label:'${i18n.search.criteria.contentType}'"></div>
```
I would prefer not to have a heading for FGDC File Types and another for ISO File Types, since my clients should not have to look in two places for one thing. Thanks.

**Comment by valentinedwv** [comment]
Modify the Evaluator for FGDC  to put the content type into "apiso_Type_s"

Modify the Evaluator for FGDC and ISO to put the content type into "format_s"
Format should be a field since it is a core queryable in the spec
