### ISSUE TITLE
HTML Links not working

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#18]
```
{
error: {
message: "Could not make xslt template from /metadata/details/iso-details/xml-to-html-ISO.xsl"
}
}
```

found in the exploded war file at: 
webapps/geoportal/WEB-INF/classes/metadata/details

**Comment by umacgillivray** [comment]
It couldn't find the file. Are you running this with Tomcat or something else?

**Comment by valentinedwv** [comment]
Tomcat8. installed using war. LINUX

AH. case issue.
```
FATAL ERROR:  '/opt/tomcat/webapps/geoportal/WEB-INF/classes/metadata/details/iso-details/printTextLines.xsl (No such file or directory)'
           :/opt/tomcat/webapps/geoportal/WEB-INF/classes/metadata/details/iso-details/printTextLines.xsl (No such file or directory)
ERROR:  'Could not compile styleshe
```
]
![image](https://cloud.githubusercontent.com/assets/851784/17638830/dd64af42-60a1-11e6-95aa-a91f55aba5b2.png)

**Comment by umacgillivray** [comment]
I renamed to printTextLines.xsl, thx
