### ISSUE TITLE
LDAP Authentication and Group Access Troubles

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#182]
**Assigning _Internal_ Access**
Having issues with assigning access via ADS Groups.
I have 
 •	enabled Group access in the app-context.xml config file 
 •	turned on Active Directory for Authentication
 •	defined authorized Groups within the domain
 •	assigned roles in the roleMap

**HELP!** When I log in as an Administrator I can only assign access to the Admin group, but, I would like to assign access to everyone in our Domain (I tried to bring in Departments but even they did not show up). I am in the _All Domain Users_ group. I have tried various permutations of assigning Roles to the Active Directory groups and still only see one group in the metadata dialogue box. See Screen capture here:
![setaccess-groups](https://user-images.githubusercontent.com/13800356/43026965-45ae5f60-8c35-11e8-89af-028ac50aaed7.png)

CODE SAMPLES:
Here are the two groups I defined in the authentication-LDAP.xml file
```
	           group-search-filter="(&amp;
                          (|(cn=Domain Users)
                          (cn=GDA-G-GEODISCOVER-ADMINS-DEV-USERS))
```	 

 
In Context User file I tried to create a new Role [INTERNAL] to see if that would help – no luck
```
/geoportal/src/main/java/com/esri/geoportal/context/AppUser.java
    groups = new ArrayList<Group>();
    username = p.getName();
    if (username != null && username.length() > 0) {
      isAnonymous = false;
      isAdmin = sc.isUserInRole("ADMIN");
      isPublisher = sc.isUserInRole("PUBLISHER");
      isInternal = sc.isUserInRole("INTERNAL");
```

AuthenitcationLDAP.xml defined roles to Active Directory Groups using the INTERNAL role
```
    <beans:property name="roleMap">
      <beans:map key-type="java.lang.String" value-type="java.lang.String">
        <beans:entry key="ROLE_All Domain Users" value="INTERNAL" />
        <beans:entry key="ROLE_GDA-G-GEODISCOVER_ADMINS_DEV-USERS" value="ADMIN,PUBLISHER" />  
```
Any suggestions on how to get the _All_Domain_Users_ Group to show up in the "Assign Access" dialog box??  Thanks

**Comment by zguo** [comment]
Unfortunately we don't have an existing active directory I can try,  here is a few suggestions:

Is the administrator in the  All_Domain_Users group? the drop down will only show those groups the administrator is a member of. 

try use group search filter something like "(&amp;(objectclass=group)(member:1.2.840.113556.1.4.1941:={0}))" to see if it help.

is the name in         <beans:entry key="ROLE_All Domain Users" value="INTERNAL" />   "All_Domain_Users"?

**Comment by valentinedwv** [comment]
The ROLE_ prefix is what spring security uses, spent a bit of time getting a keycloak oauth working.

`<beans:entry key="ROLE_GDA-G-GEODISCOVER_ADMINS_DEV-USERS" value="ADMIN,PUBLISHER" />`

Does you AD have the ROLE_  prefix or should you be matching``` GDA-G-GEODISCOVER_ADMINS_DEV-USERS```?

Question for the person who wrote the mapper, in the ArcGIS mapper, it puts the prefix on the roles, so shouldn't those values be 
```value="ROLE_ADMIN,ROLE_PUBLISHER"```

**Comment by zguo** [comment]
not sure if it is still an issue, but the values does not need to have the prefix
value="ADMIN,PUBLISHER"
