### ISSUE TITLE
Problem with outputSchema=http://www.isotc211.org/2005/gmd

### ISSUE THREAD

**Issue by robert1c** [Esri/geoportal-server-catalog#183]
I need geoportal for INSPIRE.
When I ask for csw with query:
/geoportal/csw?request=GetRecordById&service=CSW&version=3.0.0&elementSetName=full&Id=05c343be55e4425ca0a5199a3a375a9c&outputSchema=http://www.isotc211.org/2005/gmd

I get this answer:
`
<ExceptionReport xmlns="http://www.opengis.net/ows/2.0" version="3.0.0">
<Exception exceptionCode="InvalidParameterValue" locator="outputSchema">
<ExceptionText>
CSW: The outputSchema parameter must be http://www.opengis.net/cat/csw/3.0 or http://www.w3.org/2005/Atom
</ExceptionText>
</Exception>
</ExceptionReport>
`

I tried add row. Without success.

`
 <ows:Value>http://www.isotc211.org/2005/gmd</ows:Value>

 <ows:Parameter name="outputSchema">
        <ows:AllowedValues>
          <ows:Value>http://www.opengis.net/cat/csw/3.0</ows:Value>
          <ows:Value>http://www.w3.org/2005/Atom</ows:Value>
		  <ows:Value>http://www.isotc211.org/2005/gmd</ows:Value>
        </ows:AllowedValues>
      </ows:Parameter>
`

Please, help me with this problem.

Robert

**Comment by mhogeweg** [comment]
hi Robert, can you tell us what you're trying to do? do you have your geoportal publicly accessibe?

**Comment by smrgeoinfo** [comment]
I ran into the same problem and had to stick with geoportal v1.2 for our CSW services-- the new geoportal-server-catalog does not support ISO19139 xml output format--even if that's what you harvested in the first place.   This is a show stopper for using in production systems where we want to expose CSW with ISO output.

**Comment by robert1c** [comment]
First step: I want have Inspire geoportal server based on your geoportal server (Use ElsaticSerach is very good idea.). 
Next step extend fields to Slovak Inspire profile.
Yes it is accessible. This request it is OK:

http://apl.geology.sk/geoportal/csw?request=GetRecordById&service=CSW&version=3.0.0&elementSetName=full&Id=05c343be55e4425ca0a5199a3a375a9c&outputSchema=http://www.opengis.net/cat/csw/3.0

This mandatory query (Inspire) fail:

http://apl.geology.sk/geoportal/csw?request=GetRecordById&service=CSW&version=3.0.0&elementSetName=full&Id=05c343be55e4425ca0a5199a3a375a9c&outputSchema=http://www.isotc211.org/2005/gmd



Robert

**Comment by mhogeweg** [comment]
we will look at including the ISO output schema to the Geoportal 2.x CSW implementation. Note that this will only consider ISO metadata documents (we don't translate metadata between schemas). Note also that we have limited the implementation of the filter, since we do not see clients create highly complex 'where clauses' for search and discovery.

Finally, the INSPIRE Discovery Service is based on the OGC CSW ISO Applicaton Profile that is a profile of CSW 2.0.2, not 3.0.

**Comment by robert1c** [comment]
I was hoping that the next version will support outputschema = http: //www.isotc211.org/2005/gmd.
GetCapabilities is ok.
http://apl.geology.sk/geoportal/csw?service=CSW&version=3.0.0&request=GetCapabilities&outputSchema=http://www.isotc211.org/2005/gmd

in GetRecords
http://apl.geology.sk/geoportal/csw?request=GetRecords&service=CSW&version=3.0.0&typeName=csw:Record&outputschema=http://www.isotc211.org/2005/gmd

returns CSW: The outputSchema parameter must be http://www.opengis.net/cat/csw/3.0 or http://www.w3.org/2005/Atom

My boss is a bit angry.
We use ArcGIS Server and we wanted CSW server to be from ESRI.
Can you write to me if you will support CSW server outputschema = http: //www.isotc211.org/2005/gmd
Or I have to look for another OpenSource solution. We can also change the map server.

Sincerely

Robert

**Comment by robert1c** [comment]
Result from old geoportal
https://apl.geology.sk/geoportal/csw?request=GetRecords&service=CSW&version=2.0.2&typeName=csw:Record&outputschema=http://www.isotc211.org/2005/gmd

Is ok

**Comment by zguo** [comment]
Hi Robert
We will work on adding support to iso schema http://www.isotc211.org/2005/gmd next. Due to a change in the way Elasticsearch stores xml between 5.x and 6.x, we plan to add this support for geoportal running Elasticsearch 6.x. Thanks.

**Comment by zguo** [comment]
implemented in 2.6.2.
