### ISSUE TITLE
XSLT StyleSheet for ISO missing latest update

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#184]
Alberta was shown an updated xslt stylesheet to format the XML metadata into a more readable format.  With the latest 2.6.0 release there is an old 2016 stylesheet in the code.

`geoportal/src/main/resources/metadata/details/iso-details/xml-to-html-ISO.xsl`

**Please push the new stylesheet to GitHub**. Thank you
![iso-xhtml](https://user-images.githubusercontent.com/13800356/43596021-5acd1912-963b-11e8-9f56-50a0d5276e56.png)

**Comment by smrgeoinfo** [comment]
I've done a bunch of work on an ISO to HTML transform that uses some Javascript to display a location map, and puts a schema.org JSON-LD script in the HTML that should improve indexing by Schema.org aware search engines.  The code is in this repo https://github.com/usgin/metadataTransforms/tree/master/ISO19139toHTMLandSDO

you can see what it looks like with searches at 
http://catalog.iedadata.org (map not implemented, slightly older version). Click on 'full metadata record' link in search results.
or 
http://cinergi.sdsc.edu/geoportal (current version) click on the 'html' link in search results.

**Comment by zguo** [comment]
@KathleenPate  the change was actually posted to github last February, what issue are you having?

**Comment by KathleenPate** [comment]
@Zguo Earlier this year my coworkers had a video conference with Redlands staff and were shown a new ISO html layout developed for Alberta. It is my understanding that Alberta requested the Field names be converted to more user friendly terms. Example: CI_Address: would simply be Address:
I have never seen the layout, but my coworkers who were in the presentation tell me that what they see in the Sandbox does not match what they saw in the presentation. Does that ring a bell?
My coworkers will be back in the office Tuesday and I can get more specifics from them if this does not make sense.

**Comment by zguo** [comment]
#283

**Comment by KathleenPate** [comment]
We did two things to fix up the display of ISO metadata display; add a stylesheet, and, add new display elements.  File path: /geoportal/src/main/resources/metadata/details/iso-details/

### We **modified the field connections** in `elements-ISO.xml ` to fix display issue. 
For _Example_ we added an option _without_ the gmd: in the tag name because our docs didn't have gmd prefixes. 
	`<name tagname="abstract">Abstract</name>`

### **Add Bootstrap Stylesheet found in the GeoPortal into the _xml-to-htm-ISO.xsl_**
```
	<head>
	<link rel="stylesheet" href="/geoportal/lib/calcite-bootstrap/css/calcite-bootstrap.css"/>
	<style>
		pre 	{font-family: Verdana, sans-serif; color: #333333; border: none; }
```

- See SAMPLE on our Beta Site: [https://gda.alberta.ca/geoportal/](https://gda.alberta.ca/geoportal/)

**_ADD_**
Link to bootstrap css stylesheet

**REMOVE**
removed some CSS style for body, b, a: & li

**_ADD_**
under `<body>` tag add three DIV containers.
(sample)
```
	<div class="container">
	  <div class="panel panel-default">
	  <div class="panel-body">
```

**ADD**
After the div class="title" closing tag add another` </div>` to close the panel-body

After the ` <!-- <br></br><br></br> -->` add another DIV tag to hold the top anchor tag links
	`<div class="panel-heading">`

Close this Div after the `</xsl:for-each>` (removing the `<hr><hr>`)

**ADD**
after the `</xsl:for-each>` tag add a new Div tag to hold the Abstract (if desired)

```
<div class="panel panel-info">
    	<div class="panel-heading">
	<strong>Abstract: </strong>
	<xsl:value-of select="//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract/gco:CharacterString"/>
	</div>
```

Close the other `<div>` tags placing them _after_ the `</pre>` 

TADA!! 😃
