### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by crackman77** [Esri/geoportal-server-catalog#185]
Hi everyone

First of all thanks for making available this amazing product !

I have deployed both the catlog and the server (2.5.X) for a client and we had a security audit last week

Some breaches have been found especially regarding XML vulnerabilities (XXE and XSS)

Would you have any hints on upgrading the catalog to secure properly web services to these types of attacks

Was thinking about https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet 
and OWASP ESAPI 

Don't know if it is the right way to do it

Regards

Marc

**Comment by mhogeweg** [comment]
hi, we take security very serious and we're regularly testing. However, we have found some differences in test configuration between different scanning systems and it is well possible we have not caught all there is to catch. Is it possible for you to send me the scan results? mhogeweg at esri dot com
