### ISSUE TITLE
Time Period Slider

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#19]
Always shows a point way beyond now. 
When queried. shows no results

![image](https://cloud.githubusercontent.com/assets/851784/17632898/a99444ce-607f-11e6-8b6e-fcc2804cb1a4.png)

**Comment by umacgillivray** [comment]
There are some records with a temporal extent of 9999-01-01, seems to be causing an es issue, not sure why. 
http://132.249.238.169:8080/geoportal/rest/metadata/item/9883d3b0d8df4a2bb049461bbabbc233/xml
               <gmd:temporalElement>
                  <gmd:EX_TemporalExtent>
                     <gmd:extent>
                        <ns4:TimeInstant ns4:id="d36589e96">
                           <ns4:timePosition>9999-01-01</ns4:timePosition>
                        </ns4:TimeInstant>
                     </gmd:extent>
                  </gmd:EX_TemporalExtent>
               </gmd:temporalElement>
http://132.249.238.169:8080/geoportal/rest/metadata/item/9883d3b0d8df4a2bb049461bbabbc233?pretty=true
        "timeperiod_nst":{
            "begin_dt":"9999-01-01T00:00:00Z",
            "begin_indeterminate_s":null,
            "end_dt":"9999-01-01T23:59:59.999Z",
            "end_indeterminate_s":null
        },

**Comment by valentinedwv** [comment]
Time slider <=this year, default option.
People doing models might want to change the default

**Comment by umacgillivray** [comment]
Nashorn has access to the jvm. The evaluators can access Sping config:
```
var geoportalContext = com.esri.geoportal.context.GeoportalContext.getInstance();
var springContext = geoportalContext.getApplicationContext();
var myProp = springContext.getBean("myProp");

src/main/resources/app-context.xml
  <beans:bean id="myProp" class="java.lang.String">
    <beans:constructor-arg value="myPropValue"/>
  </beans:bean>
```

Evaluator.js::G._initializeTask creates a task object that can be used to hold configuration.

Nashorn does not have the ecosystem of Node, but an evaluator can instantiate a Java object to execute an HTTP request and return the response. JSON.parse the response if applicable, and use the result to enhance the item being indexed.
