### ISSUE TITLE
Bulk upload capability?

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server-catalog#2]
Is there an option to upload multiple metadata files at once? Or is this a feature of the geoportal-server-harvester?

Thanks

**Comment by pandzel** [comment]
Harvester will be primary a tool to upload multiple files. At this moment it only allows to copy data from WAF and CSW repositories, though.

**Comment by mhogeweg** [comment]
I also have some python scripts to push things into Geoportal 2.0 from local disk or from a sitemap file. these should be moved to the new harvesting framework, but may help get you started sooner.

**Comment by slead** [comment]
@mhogeweg "python scripts" implies that geoprocessing could be a new way to get data from ArcCatalog into the geoportal, rather than needing the ArcCatalog plugin? This would be a good step forward IMO.
