### ISSUE TITLE
How to arrange metadata elements into table layout

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#210]
Hi,
I Have a urgent requirement of customizing the metadata ingestion forms into a beauty full table layout. i tried multiple things like 
1. adding a html table for layout
2. adding dojo container layout
but everything is throwing an error in element repeater.js when we click on add multiple fields tab (metadata contact plus in below image) becuase i think gxe cannot repeat non gxe elements.
![capture](https://user-images.githubusercontent.com/43044931/48219891-d3640a00-e3b3-11e8-8f14-f9ab62f94e81.PNG)

**Please help, how to make a beauty full table layout from all metadata fields so that we can utilize the white space on right side of metadata editor form ??**

**Comment by mhogeweg** [comment]
hi,

not sure if I fully understand what you're after with 'table layout'. Note that in the template files (the .html files) in the editor, you can include regular HTML markup. You can also update the CSS used in the editor.

lastly, the metadata is provided in XML in the catalog and you could create an XSLT that renders the XML in a specific HTML layout, referencing specific CSS/JS  to provide the behavior and look-and-feel you are after.

**Comment by DeveshScientist** [comment]
thanks @mhogeweg , that was really helpfull. 👍
