### ISSUE TITLE
How to upload the metadata form content from a csv file.?

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#214]
hi,
I want to populate iso metadata forms from csv file.

I have tried this with traditional way of dojox.data.CsvStore but getting error with multiple dynamic fields like "metadata contact".
Please suggest a way of filling out the metadata forms using CSV file or any other mean which is possible.

like in below image how multiple "metadata contact" field will be uploaded from single csv
say contact.csv
metadata contact,email,role
xyz,xyz@ttt.com,admin
abc,xyz@ttt.com,admin

![48219891-d3640a00-e3b3-11e8-8f14-f9ab62f94e81](https://user-images.githubusercontent.com/43044931/48705159-59702400-ebf0-11e8-84c2-1b9632c5d5d1.PNG)

please suggest a way.
Thanks and Regards

**Comment by mhogeweg** [comment]
you may be better off writing a python script that parses the CSV file and creates XML that is then pushed into geoportal. typically I expect your CSV to have more than 1 row of metadata.

The Geoportal Server API supports PUT requests that allow you to submit metadata programmatically.

A note: metadata is highly nested and repetitive. I would be curious to see a full example of metadata in CSV. it simply is not a good format to store metadata in. Do you have examples?

**Comment by DeveshScientist** [comment]
Hi,
@mhogeweg  Thanks For Reply, you made my day.
Currently Working on it. I will reply you soon on your above comments.
Thanks and Regards

**Comment by DeveshScientist** [comment]
hi,

Sir we are trying to upload the content from csv to metadata forms and not to database. 

as you rightly suggested metadata is highly nested and repetitive, so only few part of metadata content is available in csv. 

what is the best way to upload the csv to metadata forms and not to elastic search index.

Thanks.

**Comment by august-zhu** [comment]
Hi @mhogeweg , I'm interested in programmatically upload metadata using PUT request (however the API syntax doc is quite simplified). Can you provide an example? Thanks!

**Comment by mhogeweg** [comment]
see #240
