### ISSUE TITLE
close the open endpoint of elastic search so that only geoportal-server 2.6 can use it.

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#216]
Hi, I am new newbie.
I want to close the open endpoint of elastic search 5.1.1 so that geoportal-server 2.6 can use it.

I have tired closing elastic search endpoint using searchguard plugin(opensource alternative to xpack) of elastic search 5.1.1. but then geoportal also unable to access elastic search 5.1.1.
I donot want anyone to access my elastic search 5.1.1 for outside ( like http:elasticsearchserver:9200/delete/_all) other then  geoportal-server (because it is authenticated).

Thanks

**Comment by mhogeweg** [comment]
You can prevent access to port 9200 via Tomcat configuration. That way only someone logged into the host will be able to run those 9200 commands. Since geoportal server is on the same host as elastic, that should be ok.

`<Connector port="9200" address="127.0.0.1" ...`

**Comment by DeveshScientist** [comment]
Hi,

This solution will work in single machine deployment . 

but we have cluster of nodes and shard . when i restrict the access to port 9200 via Tomcat configuration , then nodes of cluster cannot communicate with each other hence solution not working. 

how should i configure each node and shard of elastic search ?

Thanks,

**Comment by valentinedwv** [comment]
What is the OS?
https://serverfault.com/questions/146569/iptables-how-to-allow-only-one-ip-through-specific-port

or
firewall-cmd --permanent --zone=public --add-rich-rule='
  rule family="ipv4"
  source address="1.2.3.4/32"
  port protocol="tcp" port="4567" accept'
