### ISSUE TITLE
Expand filters when filter is added

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#22]
When first filter is added,  dropPane should expand.
When last is removed, dropPane should collapse.

![image](https://cloud.githubusercontent.com/assets/851784/17982824/773ecbf4-6abe-11e6-8eca-930c9451cef5.png)

**Comment by umacgillivray** [comment]
It should collapse when the last filter is removed.

**Comment by umacgillivray** [comment]
The enhancement was installed. Property autoExpand was added to app/search/AppliedFilters, default is true.
