### ISSUE TITLE
Allow use of different XSLT library

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#221]
Have an issue where the default library produces undesirable output. 
com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl 

This will allow us to use a version of Saxon that is not fully JAXP 1.5 compliant.

> I found a record that has the extra comma problem in the google validator: “Front Probability, GOES Imager, Western Hemisphere, 2001-present, EXPERIMENTAL (10 Day Composite), Lon+/-180” 
> http://datadiscoverystudio.org/geoportal/rest/metadata/item/a3be912494da4d2085c8a0ff6d143096/html
> 
> when the geoportal runs the xslt to generate html + JSON-LD, there’s an extra comma after the second distribution:
> "fileFormat": "OPeNDAP v.DAP/2.0"}
>                 , ]
> That stops the google parser. 
> 
> But when I run the transforms in Oxygen on my desktop (using a Xalan, Saxon 6.5.5, Saxon 9.6.0) the JSON is valid.   I grabbed the transform from  
> 132.249.238.169/ /opt/tomcat/webapps/geoportal/WEB-INF/classes/metadata/details/iso-details/ISO19139ToSchemaOrgDataset1.0.xslt and get the same result on my desktop.  And it looks like the same one that’s in the github repo that I test locally.  So…
>

**Comment by mhogeweg** [comment]
We'll review the MPL license for this library before we decide to include this pull request.

**Comment by valentinedwv** [comment]
> We'll review the MPL license for this library before we decide to include this pull request.

Thanks, It can be commented out in the POM, or just left out of the POM with the code in place
