### ISSUE TITLE
Initial install: "An Error Occurred"

### ISSUE THREAD

**Issue by rmuellerjr** [Esri/geoportal-server-catalog#226]
I've tried several times re-install and can't seem to get around this error (See below) after installing, which prevents me from doing anything within the application. I have Apache 8.5/ Java 1.8.0_161-b12 / ElasticSearch 6.4 / GeoPortal Catalog 2.6.1 on Windows 10 per the wiki install here. No other modifications were made other than to the [Cors filter for Tomcat](suite.opengeo.org/docs/latest/sysadmin/cors/index.html ). 

Anyone else encountering this error?

Error:
init.js:141 POST http://localhost:8090/geoportal2/elastic/metadata/item/_search?from=0&size=10&sort=title.sort%3Aasc 500

**Comment by rmuellerjr** [comment]
Sorry for the delay and thanks for the reply.

Yes, the return on "localhost:9200" is:

{
  "name" : "PH30Bhj",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "BjrK6tzeTT6M2uKOX1Q87g",
  "version" : {
    "number" : "6.4.0",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "595516e",
    "build_date" : "2018-08-17T23:18:47.308994Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by mhogeweg** [comment]
are you seeing any errors in the geoportal logs?

**Comment by rmuellerjr** [comment]
The log file (\Tomcat 8.5\logs\geoportal.log) doesn't provide much above "Info" aside for:
  Warn: Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)

Looks like I was missing log details in another log file (\Tomcat 8.5\logs\tomcat8-stderr.2018-12-12) which reported several Severe and Warning, mostly around async and CorsFilter (see below), which modified the web.xml to allow for CORS. I'm testing now to verify that I can clear the error and still allow CORS to be processed correctly.

19-Dec-2018 12:33:18.400 WARNING [http-nio-8090-exec-26] org.apache.catalina.connector.Request.startAsync Unable to start async because the following classes in the processing chain do not support async [org.apache.catalina.filters.CorsFilter]
 java.lang.IllegalStateException: A filter or servlet of the current chain does not support asynchronous operations.
