### ISSUE TITLE
Merge data with a common field

### ISSUE THREAD

**Issue by sagatchua** [Esri/geoportal-server-catalog#229]
For the needs of a governmental institution in Switzerland, we need to harvest periodically data from different sources (WMS from ArcGIS Server, metadata from www.geocat.ch) into our geoportal (Geoportal Server 2.6.1). I'd like the WMS link and the corresponding metadata link of each dataset to appear on the same dataset in the catalog, based on a common field. How can I do this ? Are there different ways of doing this? Thank you so much for your help!

**Comment by valentinedwv** [comment]
So you want to merge multiple records into one record.
Not simple.

Right now, during ingest, a record with the same gmd:fileIdentifier will be overwritten

Best method would be a  staging store that keeps the repositories separate, then have a merging function to create a universal record.


You might be able to have a merge flag that would say "pull links if fileid exists" Extend the MetaDataDocument with a flag to merge record, and then extend evaluate to take flacg and the json from canonical record, and merge.

**Comment by sagatchua** [comment]
Thanks very much for you help
