### ISSUE TITLE
Getting XML out of the Elasticsearch interface

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#23]
Is there a magical get URL pattern?

**Comment by mhogeweg** [comment]
yes!

example:
[http://geoss.esri.com/geoportal2/rest/metadata/item/915af1f81bc549eb8aba2bf023d391a5/xml](http://geoss.esri.com/geoportal2/rest/metadata/item/915af1f81bc549eb8aba2bf023d391a5/xml)

the pattern is:
http://host:port/context/rest/metadata/item/{id}/xml

leave out /xml to get [the JSON representation](http://geoss.esri.com/geoportal2/rest/metadata/item/915af1f81bc549eb8aba2bf023d391a5) of the item
replace /xml with /html to get a [styled rendering](http://geoss.esri.com/geoportal2/rest/metadata/item/915af1f81bc549eb8aba2bf023d391a5/html)

**Comment by valentinedwv** [comment]
I  was looking for info from the elasticsearch (aka localhost:9200) rest interface.
so:
http://132.249.238.169:9200/metadata_v1/item/bd5daa45f0f7448fa65ff2aa07eeb73b
gets you a the json, sans XML block
http://localhost:9200/metadata_v1/item/{id} 

but what gets the original metadata?
tried:
http://localhost:9200/metadata_v1/{clob|sys_meta|clob.sys_meta|sys_itemid}/{id}

**Comment by mhogeweg** [comment]
is there something specific that you can't use the geoportal API for that? it's the same XML that is returned.

**Comment by valentinedwv** [comment]
Developer curiosity... where did it go.

**Comment by umacgillivray** [comment]
/metadata/clob/{id}_xml

The clob ids are suffixed with _xml, the xml is stored in a json property named sys_clob
