### ISSUE TITLE
Thoughts on indeterminate "now"

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#238]
If document is set to be now, do we want to add a _dt at time of ingest?
This way it would be found in many searches.

Different thought is add a button to say search for "now" in indeterminate_s, and add now as the end of the range search.

**Comment by mhogeweg** [comment]
what do you mean exactly with 'document is set to be now'? the period for which the data applies? an example of that would be a stream gauge that always get updated data and therefor the temporal coverage would always be until now (until the gauge is decommissioned for example). 

setting 'now' to any specific time would immediately outdate the metadata, no?

**Comment by valentinedwv** [comment]
Adding  present date to end position is 'now' would be prudent/proactive at time of ingest? ```
<gmd:extent>
   <gml:TimePeriod gml:id="id">
      <gml:beginPosition indeterminatePosition="before">1980</gml:beginPosition>
      <gml:endPosition indeterminatePosition="now"/>
   </gml:TimePeriod>
</gmd:extent>
```
translates to 
```
    "timeperiod_nst" : [
      {
        "begin_dt" : "1980-01-01T00:00:00Z",
        "begin_year_l" : "1980",
        "begin_indeterminate_s" : null,
        "end_dt" : null,
        "end_year_l" : null,
        "end_indeterminate_s" : "now"
      },

```
Not adding it means that document would not be found if user searched for a range of say 2000/2001
Adding it means, yes out of date, but findable.
```
    "timeperiod_nst" : [
      {
        "begin_dt" : "1980-01-03T00:00:00Z",
        "begin_year_l" : "1980",
        "begin_indeterminate_s" : null,
        "end_dt" :  2019-03-14:T16:43:00Z,
        "end_year_l" : "2019",
        "end_indeterminate_s" : "now"
      },
```
'now' is there. Updating the index could be solved by updating using an elasticsearch update script, find 
""end_indeterminate_s" : "now"" update to XXXX.

 Other option is modifying the temporal search filters.

Use case for setting to today:
*  year search 
* simpler date range query
* An app/user going direct to the elasticsearch gpt rest interface. We would need to provide the example queries to cover the use case of now.
