### ISSUE TITLE
Programmatically upload

### ISSUE THREAD

**Issue by august-zhu** [Esri/geoportal-server-catalog#240]
Hi,

Newbie here.
I know the GeoPortal Server API support PUT requests that can upload metadata programmatically. But the API doc is so simplified. Can anybody provide an example (or simply steps) on how to do this?

Thanks!

**Comment by mhogeweg** [comment]
hi, I added a simple sample python script here:
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/doc/put_metadata.py

This shows you how to crawl through a local folder structure and push the metadata (assumed here to be XML files) to Geoportal 2.

**Comment by august-zhu** [comment]
@mhogeweg Thanks! Help a lot!
