### ISSUE TITLE
Release 2.6.1: Elasticsearch client is 5.1.1 - not compatible with Elasticsearch 6.x

### ISSUE THREAD

**Issue by str3tch** [Esri/geoportal-server-catalog#242]
Hi there,

I installed Geoportal 2.6.1, which in the release notes states it is compatible with Elasticsearch 6.x - however, the client in the 2.6.1 release (and still in the master branch of this repo) is still 5.1.1 - which is not compatible with Elasticsearch 6.x

Was this an oversight? I am not sure how Geoportal can be compatible with 6.x when it uses 5.1.1 client?

Or perhaps I am missing something - did I do something wrong?

Setup:
- Geoportal 2.6.1
- Seperate Elasticsearch 6.4.0 cluster

cheers,
Str3tch

**Comment by str3tch** [comment]
I can see in Elastic that the 9300 transport calls are being rejected from Geoportal because it's an incompatible version.

I expanded the WAR file on my mac, just for ease to show what's in it:

https://www.screencast.com/t/HDe9rChO93

**Comment by umacgillivray** [comment]
@str3tch 
The v5 transport client provides backward compatibility for v5 Elasticsearch instances. By default, Geoportal 2.6.1 will use HTTP to communicate with Elasticsearch 6*.  Not sure why you are seeing traffic on 9300, maybe you are re-using an earlier copy of app-context.xml? 
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/config/app-context.xml

This line is important:
<beans:bean id="elasticContext" class="com.esri.geoportal.lib.elastic.ElasticContextHttp">

**Comment by str3tch** [comment]
Ah! Thank you! It was an upgrade from an earlier version, maybe I copy pasted the old app context. I’ll try it out and report back today

**Comment by str3tch** [comment]
yep, that was it. thanks!
