### ISSUE TITLE
Opensearch links always include default sort

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#244]
If relevancy is selected, the opensearch links include the default sort, even if there is a search (text, location)
This changes the order of the results (no longer by relavancy.

**Comment by KathleenPate** [comment]
I would like a more documentation (wiki) on how the default sort works and how to manage various sort options either within the Search Results pane, and, the Search Filters. Thanks

**Comment by zguo** [comment]
implemented.
