### ISSUE TITLE
ElasticSearch Relevance & boosting _score value

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#248]
Have there been any modifications to the default ElasticSearch _score parameter? I understand that the default score is based on an algorithm with a .getBoost function. Have any GeoPortal specific Boost functions been written to accommodate geospatial metadata?  If so **where can I find those** to make adjustments for our collection??

_default relevance:_ score(q,d) = queryNorm(q) * coord(q,d) * ∑ ( tf(t in d) * idf(t)² * **t.getBoost**() * norm(t,d)) (t in q)

**Comment by mhogeweg** [comment]
hi, we have not made any modifications to elastic or implemented boost functions.
