### ISSUE TITLE
Geoportal Search Component page links

### ISSUE THREAD

**Issue by rmuellerjr** [Esri/geoportal-server-catalog#256]
All the links for this page are "404 not found"

Wiki link: https://github.com/Esri/geoportal-server-catalog/wiki/Geoportal-Search-Component

**Comment by mhogeweg** [comment]
thanks for the catch! I updated the various links. they should be ok now. We had deployed the component in /geoportal2 instead of /csw3 as was referenced in the page.

http://geoss.esri.com/geoportal2
