### ISSUE TITLE
Geoportal Server 2.6.1 in Disconnected environment with Argis Enterprise 10.6.1

### ISSUE THREAD

**Issue by MarcSimon007** [Esri/geoportal-server-catalog#257]
In a VM disconnected from internet with OS WIN2012 R2 installed, I did a full install from ArcGIS Enterprise 10.6.1 (all the services Portal and ArcGIS Server are working well). After that I installed java jre and jdk version 8u-161-windows x64,  Tomcat apache 5.8.33, Elasticsearch-6.6.1 and Geoportal Server 2.6.1. At each step I did tests to see if the componenst are working. For the geoportal-server-catalog I followed https://github.com/Esri/geoportal-server-catalog/wiki/Installing-Geoportal-Server-2.6.1 and https://github.com/Esri/geoportal-server-catalog/wiki/Configure-geoportal-for-a-disconnected-environment but unsuccessful. 
Result when I try to go to https://<servername>:8080/geoportal, I see only this:
![image](https://user-images.githubusercontent.com/13694027/54371150-34a92c00-4679-11e9-9807-62622d0bc5ad.png) - only the progressbar defined in index.html.
I did the same configuration in a VM connected to internet and all is working fine.

Some Idea?

**Comment by valentinedwv** [comment]
Any messages in the javascript console?
Chrome: right three vertical dots, more tools>developer tools, then click console.

**Comment by MarcSimon007** [comment]
All the messages to the links are corrected one by one. There are three open comments concerning the fonts.

**Comment by MarcSimon007** [comment]
Issue is not closed.

**Comment by MarcSimon007** [comment]
I have following messages, all related to index.html file
![image](https://user-images.githubusercontent.com/13694027/54464316-7b308080-4776-11e9-8cb9-044f282082cf.png)
The Avenir_Next_W01_300.woff file exist in folder C:\inetpub\wwwroot\arcgis_js_v325_api\arcgis_js_api\library\3.25\3.25\esri\themes\calcite\fonts\avenir-next and the and the Avenir_Next_W01_300.woff2 file exist in folder C:\inetpub\wwwroot\arcgis_js_v325_api\arcgis_js_api\library\3.25\3.25\esri\themes\calcite\fonts\avenir-next ==> I suppose the fonts exists but are not loaded. 
I changed all stylesheet references as: 
![image](https://user-images.githubusercontent.com/13694027/54465201-3e668880-477a-11e9-933a-e0e46a9664a4.png)

**Comment by mhogeweg** [comment]
did you add .woff2 as a known MIME type in IIS?

![image](https://user-images.githubusercontent.com/394890/54465711-c9735e80-4739-11e9-87df-d14424242b2d.png)

**Comment by MarcSimon007** [comment]
No. I can do it.

**Comment by MarcSimon007** [comment]
.woff was existing in IIS, I add .woff2 but no result change
![image](https://user-images.githubusercontent.com/13694027/54468119-f3547180-4789-11e9-9f31-df307b04e43d.png)

**Comment by mhogeweg** [comment]
perhaps an obvious one, but did you try opening the URL to the fonts directly in the browser?

**Comment by MarcSimon007** [comment]
Yes. The result is the download from the woff file. I try all the URL changes one by one in the web browser. All URL are positive except one and it is at Tomcat proxy.jsp.

**Comment by mhogeweg** [comment]
wait, the link ends with .woff? not .woff2? both flavors exist. also add the .woff type to IIS. see this article on the issue and the resolution:
https://hotcakescommerce.zendesk.com/hc/en-us/articles/210926903-HTTP-404-Not-Found-Error-with-woff-or-woff2-Font-Files

**Comment by MarcSimon007** [comment]
Hi Marten, I did what was explain at the article but the issue is not resolved. Please find in attach the last log files from Tomcat. It is an access to folder problem, is it possible that this is a certificate issue?
Other question: is it necessary to install a IIS to tomcat connector?
[localhost_access_log.2019-03-25.txt](https://github.com/Esri/geoportal-server-catalog/files/3001259/localhost_access_log.2019-03-25.txt)
[Remarks with developer tool.txt](https://github.com/Esri/geoportal-server-catalog/files/3001260/Remarks.with.developer.tool.txt)
[tomcat8-stderr.2019-03-25.log](https://github.com/Esri/geoportal-server-catalog/files/3001261/tomcat8-stderr.2019-03-25.log)
[tomcat8-stdout.2019-03-25.log](https://github.com/Esri/geoportal-server-catalog/files/3001262/tomcat8-stdout.2019-03-25.log)
[catalina.2019-03-25.log](https://github.com/Esri/geoportal-server-catalog/files/3001263/catalina.2019-03-25.log)
[commons-daemon.2019-03-25.log](https://github.com/Esri/geoportal-server-catalog/files/3001264/commons-daemon.2019-03-25.log)
[geoportal.log](https://github.com/Esri/geoportal-server-catalog/files/3001265/geoportal.log)
[localhost.2019-03-25.log](https://github.com/Esri/geoportal-server-catalog/files/3001266/localhost.2019-03-25.log)

**Comment by mhogeweg** [comment]
a colleague ran into the same issue and then I noticed he (and you so it seems) don't have IIS front your Tomcat. Here is an article that shows how to get the mime types defined in Tomcat web.xml:
https://gist.github.com/alexanderbartels/831ae012245cbf633bc6

you'll need to do this for woff and woff2

**Comment by MarcSimon007** [comment]
Marten, sorry no change to do. All this mime-mapping rules exist at the web.xml file, except .woff2. No change from result?
With more deep investigate, I can see following error:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED ===> 9431e9a5-7a6d-4b5f-82be-4d935972de5a.css:1
Failed to load resource: the server responded with a status of 404 () ===> ags.esribelux.eu/:1
Access to font at 'http://ags.esribelux.eu/arcgis_js_v325_api/arcgis_js_api/library/3.25/3.25/esri/themes/calcite/fonts/avenir-next/Avenir_Next_W01_300.woff2' from origin 'http://ags.esribelux.eu:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. ==>(index):1
Failed to load resource: net::ERR_FAILED ==> Avenir_Next_W01_300.woff2:1
Access to font at 'http://ags.esribelux.eu/arcgis_js_v325_api/arcgis_js_api/library/3.25/3.25/esri/themes/calcite/fonts/avenir-next/Avenir_Next_W01_300.woff' from origin 'http://ags.esribelux.eu:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. ==> (index):1
Failed to load resource: net::ERR_FAILED ==> Avenir_Next_W01_300.woff:1
Failed to load resource: the server responded with a status of 404 () ==> ags.esribelux.eu/:1
Uncaught ReferenceError: require is not defined ==> (index):48
at (index):48
Status code 404 ==> access problems to resolve between tomcat and IIS. Is there a solution to use a IIS Tomcat connector?

**Comment by mhogeweg** [comment]
there could be a CORS issue accessing ags.esribelux.eu from port 8080. 

I do notice that I get a 404 when accessing the link to the woff2 font and as well when accessing the server top address http://ags.esribelux.eu

![image](https://user-images.githubusercontent.com/394890/55204575-c7bf8700-518c-11e9-99bd-f1df7009481c.png)

**Comment by MarcSimon007** [comment]
You can not access http://ags.esribelux.eu, it is a full disconnected environment.

**Comment by MarcSimon007** [comment]
Marten, I did all what you suggested, but without results. To clarify the situtaion I have defined to VM the first with arcgis enterprise ags.esribelux.eu and the second with the geoportal server (elasticsearch, tomcat and geoprtal server) gps.esribelux.eu.
I continue to receive this errors:
![image](https://user-images.githubusercontent.com/13694027/55301681-15aee600-543e-11e9-9f90-f9036ab82634.png)
All is linked to the XML file in attach

[index.txt](https://github.com/Esri/geoportal-server-catalog/files/3027653/index.txt)

**Comment by MarcSimon007** [comment]
Marten, Due to the problems communication between the websites, I installed the geoportal.war in IIS 8.5 (delivered with ArcGIS Server 2012 R2. I have no more problems with cors and fonts.
But I have two errors in the index.html file and no results actually: I can see only the banner. Can you investigate this?
![image](https://user-images.githubusercontent.com/13694027/55340718-85a48700-54a5-11e9-9074-fe88e2d62387.png)
![image](https://user-images.githubusercontent.com/13694027/55340737-8fc68580-54a5-11e9-806b-2b051493280b.png)

**Comment by MarcSimon007** [comment]
Also here the index.html file saved in txt format
[index.txt](https://github.com/Esri/geoportal-server-catalog/files/3030248/index.txt)

**Comment by mhogeweg** [comment]
I bet that if you open the link to the JS API you get something similar to what I get:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /arcgis_js_api/library/3.25/3.25 was not found on this server.</p>
</body></html>
```

that server is not entirely disconnected from the web. my request to https://gps.esribelux.eu/arcgis_js_api/library/3.25/3.25 makes it to the server (or at least to some proxy before it and it responds with 404).

if your geoportal is on the same machine as the JS API, can you use an internal address like localhost? or even a relative path like ```/arcgis_js_api/library/3.25/3.25```?

**Comment by MarcSimon007** [comment]
Marten,
Absolutely false, I see next window:
![image](https://user-images.githubusercontent.com/13694027/55346961-fa7ebd80-54b3-11e9-92d7-7a0dc77232f7.png)
I can access the api library with servername, localhost and IP adress from server gps.esribelux .eu and with servername and IP adress from server ags.esribelux.eu.
From my host I can ping it, but I can't access them: the ethernet connector is active, but is not allowed to internet access.

**Comment by MarcSimon007** [comment]
I forgot to mention tyhat effectively the geoportal server is on the same machine as the JS API 3.25., I have also installed Java jdk1.8.0_161.
I have stopped Tomcat, while I have activated the GeoPortal through IIS.

**Comment by mhogeweg** [comment]
then you should be able to use a relative path even to the JS API that would ideally avoid the request going out to some sort of network proxy before going back to the server. from that machine itself or from your client machine, can you open that JS API url?

**Comment by MarcSimon007** [comment]
Direct relatif path to JS API as //ArcGIS_js_api/Library/3.25/3.25 or \\arcgsi_js_api\library\3.25\3.25\. When I give a relative path //gps.esribelux.eu/arcgis_js_api/library/3.25/3.25/ he goes immediately to http://gps.esribelux.eu/arcgis_js_api/library/3.25/3.25/ and access the directory.

Provenance : Courrier pour Windows 10

De : Marten
Envoyé le :01 April 2019 19:38
À : Esri/geoportal-server-catalog
Cc : MarcSimon007; State change
Objet :Re: [Esri/geoportal-server-catalog] Geoportal Server 2.6.1 inDisconnected environment with Argis Enterprise 10.6.1 (#257)

then you should be able to use a relative path even to the JS API that would ideally avoid the request going out to some sort of network proxy before going back to the server. from that machine itself or from your client machine, can you open that JS API url?

**Comment by mhogeweg** [comment]
@umacgillivray do you have suggestions for marc?

**Comment by MarcSimon007** [comment]
I did a fast test with the relative path but the errors are the same as before


Provenance : Courrier pour Windows 10

De : Marten
Envoyé le :01 April 2019 20:26
À : Esri/geoportal-server-catalog
Cc : MarcSimon007; State change
Objet :Re: [Esri/geoportal-server-catalog] Geoportal Server 2.6.1 inDisconnected environment with Argis Enterprise 10.6.1 (#257)

@umacgillivray do you have suggestions for marc?

**Comment by mhogeweg** [comment]
after discussing with Urban a bit. the URL to the JS API should return the init.js content, not a browse directory view of the JS API. similar to when you open this: https://js.arcgis.com/3.22

another option is if you have Portal for ArcGIS in the disconnected environment, since that also has the JS API.

**Comment by MarcSimon007** [comment]
If you will attack directly de init.js you need to specify Following URL //gps.esribelux.eu/ArcGIS_js_api/Library/3.25/3.25/init.js.

The use from the JS API is not a good path, I have separate expressly both, will there was een interaction between de API’s. By the installation from the Geoportal Server I lose systematically the active services from the Portal for ArcGIS. To activate them at new, I neede to uninstall the Geoportal server and Tomcat. Also be carefull with this option, will the default JS API to use with ArcGIS Enterprise disconnected is version 4.10.

Provenance : Courrier pour Windows 10

De : Marten
Envoyé le :01 April 2019 21:03
À : Esri/geoportal-server-catalog
Cc : MarcSimon007; State change
Objet :Re: [Esri/geoportal-server-catalog] Geoportal Server 2.6.1 inDisconnected environment with Argis Enterprise 10.6.1 (#257)

after discussing with Urban a bit. the URL to the JS API should return the init.js content, not a browse directory view of the JS API. similar to when you open this: https://js.arcgis.com/3.22
another option is if you have Portal for ArcGIS in the disconnected environment, since that also has the JS API.

**Comment by MarcSimon007** [comment]
If you have some other suggestions, feel free to send them. I will test them as fast as possible;

**Comment by mhogeweg** [comment]
Perhaps obvious, but you did update the value of:

```
https://[HOSTNAME_AND_PATH_TO_JSAPI]dojo
```

after you moved the JS API?

**Comment by MarcSimon007** [comment]
The update init.js and dojo.js is done. To avoid any conflicts I started a completely new setupfromboth servers and I follow the documentation to check all the updates to do.

Provenance : Courrier pour Windows 10

De : Marten
Envoyé le :01 April 2019 23:13
À : Esri/geoportal-server-catalog
Cc : MarcSimon007; State change
Objet :Re: [Esri/geoportal-server-catalog] Geoportal Server 2.6.1 inDisconnected environment with Argis Enterprise 10.6.1 (#257)

Perhaps obvious, but you did update the value of:
https://[HOSTNAME_AND_PATH_TO_JSAPI]dojo
after you moved the JS API?

**Comment by MarcSimon007** [comment]
After adaption IIS and INit.js and referncing all the sources locally, Geoportal window opens. But still 6 errors: 5 for fonts and one for search. 
Global five errors: 6 fonts and 1 search

Fonts not recognised:
* Avenir_Next_W01_300.woff
* Avenir_Next_W01_300.woff2
* Avenir_Next_W01_400.woff
* Avenir_Next_W01_400.woff2
* CalciteWebCorelCons.ttf?r2lind
* CalciteWebCorelCons.woff?r2lind

IIS MIME and web.wml at Topmcat is adapted, but it don't resolve the problem. Bypass error mention is possible with disable chrome security !!! ==> run chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security, but chrome not allowed as official web browser. 
Question: is it possible to download somewhere this fonts and to referncing them local? 

What means this error: SearchPane.js:170 d {message: "Unable to load ./elastic/metadata/item/_search?fro… an error in handleAs: transformation of response", response: {…}, stack: "Error: Unable to load ./elastic/metadata/item/_sea…/arcgis_js_api/library/3.25/3.25/init.js:143:341

**Comment by MarcSimon007** [comment]
Please, 
Can somebody explain me where I need to change the basemap references to see a map through the geoportal searchpanel URL http://cdcwtstgis03.idcn.mil.intra:8080/geoportal/#searchPanel and through the geoportal Mappanel URL http://cdcwtstgis03.idcn.mil.intra:8080/geoportal/#mapPanel. I don't receive any response from a map. Are there some particular preparation to do.

**Comment by zguo** [comment]
for the search map, you can change the basemap reference in  geoportal\app\context\app-config.js\app-config.js, e.g.     basemap: "http://myagsserver.esri.com/arcgis/rest/services/SampleWorldCities/MapServer",

for map viewer it would involve first set up local Portal for ArcGIS  instance, create a web map that is using the local map service created from AGS, then update \geoportal\viewer\config.json to use the web map created in Portal.

    "portalUrl": "http://localagpportal.com",
    "geometryService": "https://localagpportal/arcgis/rest/services/Geometry/GeometryServer",
   "itemId": "6e03e8c26aad4b9c92a87c1063ddb0e3",

**Comment by zguo** [comment]
Close it for now, we can open a new item if it is still issue.
