### ISSUE TITLE
CSW 2.0.2 GetRecords post not working

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#258]
KVP works:
http://datadiscoverystudio.org/geoportal/csw?service=CSW&request=GetRecords&version=2.0.2&namespace=xmlns%28csw=http://www.opengis.net/cat/csw%29&resultType=results&outputSchema=http://www.opengis.net/cat/csw/3.0&outputFormat=application/xml&maxRecords=10&typeNames=csw:Record&elementSetName=summary&constraintLanguage=CQL_TEXT&&constraint_language_version=1.1.0&constraint=AnyText%20Like%20%27water%27

Ok, if you make a post which should work, you get back the capabilities document
```
<?xml version="1.0"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" 
service="CSW" version="2.0.2"  resultType="results" outputSchema="http://www.opengis.net/cat/csw/3.0" maxRecords="200"
 startPosition="1" >
    <csw:Query typeNames="csw:Record">
         <csw:ElementSetName>full</csw:ElementSetName>
         <csw:Constraint version="1.1.0">
            <Filter xmlns="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
                <PropertyIsLike wildCard="%" singleChar="_" escapeChar="\">
                    <PropertyName>AnyText</PropertyName>
                    <Literal>%ioos%</Literal>
                </PropertyIsLike>
            </Filter>
        </csw:Constraint>
    </csw:Query>
</csw:GetRecords>
```

even one with CqlText fails via post:
```
<?xml version="1.0"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" 
service="CSW" version="2.0.2"  resultType="results" outputSchema="http://www.opengis.net/cat/csw/3.0" maxRecords="200"
 startPosition="1" >
    <csw:Query typeNames="csw:Record">
         <csw:ElementSetName>full</csw:ElementSetName>
         <csw:Constraint version="1.1.0">
            <csw:CqlText>AnyText Like '%water%'</csw:CqlText> 
        </csw:Constraint>
    </csw:Query>
```

**Comment by mhogeweg** [comment]
Geoportal 2 has indeed a limited implementation of CSW 2.0.2. We have implemented CSW 3.0.0 that more closely follows the OpenSearch approach.

**Comment by valentinedwv** [comment]
Fine with that.
Should report on post, 
400 operation not supported

and should the ows:post be removed, since it is not supported?
```
        <ows:Operation name="GetRecords">
            <ows:DCP>
                <ows:HTTP>
                    <ows:Get xlink:href="http://localhost:8081/geoportal/csw" />
                    <ows:Post xlink:href="http://localhost:8081/geoportal/csw" />
                </ows:HTTP>
            </ows:DCP>
```

**Comment by mhogeweg** [comment]
@umacgillivray can you take a look at this?

**Comment by zguo** [comment]
added support for post operation, the outputSchema has to be one of the following:
http://www.opengis.net/cat/csw/2.0.2
http://www.w3.org/2005/Atom
http://www.isotc211.org/2005/gmd
