### ISSUE TITLE
Search ItemCard Check Service Function working?

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#260]
In the spring of 2018 the Service Checker returned bar graph images next to the Resource Title. Now I cannot find any records with a Service Icon. _**Is it still working?**_
Last year I could see  "Historical Oil Exploration",  and "Map service: United States Decadal Production History Cells". Now, no icons show.

**ItemCard.js**
line 560: 
`    _renderServiceStatus: function(item) {`

line 583 
`    _checkService: function(id,type) {`

image sample:
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/images/serviceCheckerExcellent16.png

**Comment by mhogeweg** [comment]
yes, this is a feature in Geoportal 2. You may need to update ```webapps\geoportal\app\context\app-config.js``` to include your API key to the service checker. I also noticed that FGDC appears to have moved the service checker, so use the below value for the apiUrl:

```
  statusChecker: {
    apiUrl: "https://statuschecker.fgdc.gov/api/v2/results?",
    infoUrl: "http://registry.fgdc.gov/statuschecker/ServiceDetail.php?",
    authKey: "PROVIDE YOUR KEY HERE"
  }
```

I do notice an issue with the infoUrl. I'll check with FGDC on that

**Comment by mhogeweg** [comment]
note that the service checker URL has changed. please consult the FGDC documentation at https://statuschecker.fgdc.gov/documentation and then find the REST API and information on Live Test.
