### ISSUE TITLE
How To: Create 2 Indexes for ElasticSearch

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#266]
**How can I create two Indexes in the GeoPortal?**
Could I add an index name in the app-context.xml? How do I define two values?
_EG - would this work?_  
`	<beans:bean id="elasticContext" class="com.esri.geoportal.lib.elastic.ElasticContext">
		<beans:property name="clusterName" value="${es_cluster:elasticsearch}" />
		<beans:property name="indexName" value="metadata, metadataIndex2" />`

### **Business Request**
Client would like to have a separate Tab search panel for a unique set of pdf maps.
I suggested a unique "view" of filtered results (like Issue 119) but they do not want the pdf maps mixed into the geospatial data collection.  I've been asked to investigate creating two indexes within the one geoPortal. 

Any tips or suggestions? Could there be draw backs to having two indexes?  This might be the first of many Index creations because there may be _other_ products we will add to the collection using metadata to help catalog data.

BACKGROUND:
The metadata xml files are using the same template. There is _one unique xml field_ in the PDF metadata records (Scale).  Perhaps we could filter IN/OUT on the Scale field?

G.evalProp(task,item,root,"apiso_Denominator_i","gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialResolution/gmd:MD_Resolution/gmd:equivalentScale/gmd:MD_RepresentativeFraction/gmd:denominator/gco:Integer");

**Comment by valentinedwv** [comment]
No, there are still a couple places where the metadata is hard coded.

Adding a URL filter is easier. Did it so you can reference a fileid
https://github.com/Esri/geoportal-server-catalog/pull/239

**Comment by mhogeweg** [comment]
are you looking to use two separate indexes from the same webapp? that is not supported at this point. What you can do is setup a separate index (with a different name) and then have a portal webapp connecting to that. That instance can have its own document structure and search facets

**Comment by KathleenPate** [comment]
We were hoping to have 2 elastic indexes in one webapp. After re-reading Issue 119 we realized that wasn't going to work.  We'll use unique tags and the filters option to keep the collections separate. Thanks for your reply.

**Comment by mhogeweg** [comment]
we are looking at an ability to have multiple sets of facets in 1 webapp. based on (for example) metadata type/source facets could switch to be more appropriate for the content. Think having 1 catalog where you have imagery content (many very similar things) vs 'regular' metadata (fewer but different things). would this be of use for your scenario?

**Comment by KathleenPate** [comment]
Yes, this matches our scenario and would be of use.  Currently we have metadata on shape data but we can see cataloging imagry as well as these PDF maps.

**Comment by mhogeweg** [comment]
closing as this has been implemented using 'collections': https://github.com/Esri/geoportal-server-catalog/wiki/Configure-Collections
