### ISSUE TITLE
Switch from local ElasticSearch to AWS ElasticSearch

### ISSUE THREAD

**Issue by rmuellerjr** [Esri/geoportal-server-catalog#268]
I currently have a docker file to run geoportal on an AWS EC2 instance, where I am using a local ElasticSearch,  but would like to switch to using AWS ElasticSearch directly. I'm not sure where start. Has anyone else had any luck using AWS ElasticSearch?

ElasticSearch install with Docker file (code-snippet from Docker file):
  #Install Elasticsearch 6.4.
  RUN apt-get install apt-transport-https -y && \
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - && \
    echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a 
  /etc/apt/sources.list.d/elastic-6.x.list && \
   apt-get update && apt-get install elasticsearch

**Comment by valentinedwv** [comment]
Can you just open the AWS ES to your workstations address, and set an environment variable?
Since it's a fork (mainly management utilities) it should work.
https://github.com/Esri/geoportal-server-catalog/wiki/Elasticsearch-configuration
```
Add the following to [Tomcat8]/conf/catalina.properties, es_node is a comma separated list.
#Geoportal
es_cluster=myclustername
es_node=host1,host2

```
And i've made some changes to make docker config possible:
https://github.com/Esri/geoportal-server-catalog/pull/264

**Comment by rmuellerjr** [comment]
I hope it's that easy. I'll take a look -thanks!

**Comment by rmuellerjr** [comment]
FYI - I'm still working on testing this. I stood up a new AWS ES and working through issues with testing everything working correctly before I can try with the suggestions above.

**Comment by rmuellerjr** [comment]
I'm still struggling with this one.  I've made this suggested add to my Dockerfile (just under maintainer): 

    ARG es_cluster=**xyz**
    ARG es_node= {EC2 IP}

Based on my AWS Elasticsearch VPC endpoint:

{
  "name" : "test",
  "cluster_name" : "**xyz**",
  "cluster_uuid" : "abc",
  "version" : {
    "number" : "6.5.3",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "159a78a",
    "build_date" : "2018-12-06T20:11:28.826501Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

However, when I compare the ES file from AWS (at the console) and my localhost:9200, the version and build numbers are different.. It would make sense to me to modify the docker-compose, but I can't find anything on Google to support swapping AWS Elasticsearch for a local ES

Docker-compose.yml:
________________________
version: '3.5'

services:
  geoportal:
    build: gpt_stack/geoportal
    ports: 
# keep it off 8080 on local dev
      - "8082:8080"
    hostname: geoportal
    environment:
      - es_cluster=es-geoportal
      - es_node=elasticsearch
      - gpt_authentication=authentication-simple.xml
    volumes:
      - gptharvester:/root
      - gptmetadata:/opt/tomcat/webapps/metadata
    networks:
      - datastudio
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch1
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - cluster.name=es-geoportal
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    networks:
      - datastudio

**Comment by valentinedwv** [comment]
Not sure exactly how docker compose works with AWS, or docker for that matter.

The docker compose file is wired up for local development.
ARG will not work... those are not parameters set in the docker build.

There are environment variables that you set in the container on deployment, or in the tomcat you manually deployed your war files to. (howto somewhere in the wiki)

If I was doing this locally and manually, I might use:
```
cd docker/gpt_stack
docker build 
docker run geoportal -e es_cluster='**xyz**' -e es_node='{EC2 IP}'
```
or 
```
docker run geoportal --env-file={file with defined variables}  --expose (some ports) 
```

You just need to create a docker compose to build the geoportal.

```
version: '3.5'

services:
  geoportal:
    build: gpt_stack/geoportal
    ports: 
# keep it off 8080 on local dev
      - "8082:8080"
    hostname: geoportal
    environment:
      - es_cluster=**xyz**
      - es_node={EC2 IP}
      - gpt_authentication=authentication-simple.xml
    volumes:
      - gptharvester:/root
      - gptmetadata:/opt/tomcat/webapps/metadata
```

**Comment by valentinedwv** [comment]
One more suggestion. Can you temporarily open the AWS elasticsearch to your local machine?
Then set environment variables in your tomcat... 
Note, I don't muck with my workstation tomcat environment variables. I just build and run it in intellij with deployment variables.

workflow might be:
- pull code from GitHub
- setup a tomcat instance in AWS.
- set local env variables in your tomcat 
- build war from master branch
- deploy war locally, see if it runs
- set env variables in AWS tomcat; restart tocmat
- deploy war to AWS instance

or
workflow might be:
- pull code from GitHub
- setup a tomcat instance in AWS.
- setup a run local tomcat in your development environment. 
-- be sure it has the proper env var to run against ES in AWS
- run war from master branch in workstation dev environment.
- test locally, repeat until it connects to AWS
- set env vars in AWS tomcat; restart tomcat
- build and deploy war to AWS tomcat

- deploy war locally, see if it runs
- set env variables in AWS tomcat; restart tocmat
- deploy war to AWS instance


-

**Comment by rmuellerjr** [comment]
Thanks! I will give those options a try. I've been here, there, and everywhere the past couple days to try to get this to run, so to say I've hit a dead end was an understatement. Everything, including Tomcat is through the docker file, which is run locally and if succeeds,  is pushed up and then run from an AWS EC2 (one for Geoportal/Harvester, and one for Elasticsearch).

From my web searches and help here, it sounds like its fairly uncharted territory. Hopefully I can get this figured out, and I can provide some additional documentation for the page Wiki.

**Comment by valentinedwv** [comment]
I probably should have put ‘this is untested new functionality’ on the top of the page. I only did prototyped it a few weeks ago, so I could develop  auth against a keycloak server. 

It would be great to have  notes on AWS deployment. 

Also when in doubt, standard tomcat, hard code, build and deploy war files.

**Comment by rmuellerjr** [comment]
Well - I'm glad to say that we've finally put this issue to rest, which had plagued me forever and couldn't figure it out.  When adding the environmental vars (es_node, es_cluster) to docker-compose yaml we would receive this error for this request in the Chrome dev console: http://localhost:8082/geoportal/elastic/metadata/item/_search?from=0&size=10&sort=title.sort%3Aasc

The answer? To create a mapping in Kibana (or command line):

PUT metadata
{
  "mappings": {
    "_doc": { 
      "properties": { 
        "title":    { "type": "text"  }
        }
      }
    }
  }

Other notes:
- Our AWS environment was AWS ES with Fargate
- This only works with the "Elasticsearch" heading in yaml file removed (as suggested above)
- To the yaml file, add the "volumes" from the original docker compose
- We need to use a AWS-ES-proxy to make this happen, adding the proxy url as es_node
- We also were successful with adding es_node/es_cluster to the Catalina.properties file, making sure (within docker file) to copy from local into docker.

I'll be writing up a more detailed set up info and a pull request. Cheers!
