### ISSUE TITLE
How to add "Source of Origin" to a metadata?

### ISSUE THREAD

**Issue by august-zhu** [Esri/geoportal-server-catalog#269]
In the left panel of Search tab, there is a "Source of Origin" filter. For those metadata harvested via Harvester, the "Source of Origin" would be the input broker name, which does not exist in XML, but exists as the parameter "src_source_name_s" in JSON. But for those metadata manually uploaded/created, there is no place for this "Source of Origin" parameter. How to add this parameter in XML?

**Comment by mhogeweg** [comment]
@umacgillivray can you see if this field can be set as part of uploading/creating metadata in geoportal?
