### ISSUE TITLE
path_hierarchy Aggregation search component

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#27]
Terminology is often in a hierarchy, but this is cannot be expressed as a simple keyword lists. 

Sometimes metadata creators may express such paths in their keywords, eg Science Domain > Earth Sciences > Geology The HierarchyAggregation allows for the generation of tree widgets in the search panel to allow for searching of of such hierarchies.

This allows for the use of fields that have been indexed by the path_hierarchy analyzer

paths: Science Domain > Earth Sciences > Geology
multiple root paths can be displayed seperately

**Comment by valentinedwv** [comment]
In progress:
http://132.249.238.169:8080/geoportal/

branch:
https://github.com/CINERGI/geoportal-server-catalog/tree/hierachy

**Comment by valentinedwv** [comment]
To index, it has to be inside the document.

Done two ways:
1) we put the path as the thesaurus name inside the iso document, then combine TN, and Keyword in the evaluator (categories_cat)
2) we call a REST service in the evaluator, and stuff full paths into the document  (heirarchies_cat)

So for GMET, you would call a service (or some code embedded in geoportal cat), and add a path.

This could be used to prefix terms with thesuarus names, as an easier way create new search facets. May be other ways to do this, also. This is just the simplest.

**Comment by valentinedwv** [comment]
> The hierarchy choice counts appear to not be fully aligned with the current result set. It is possible to select some option in the hierarchy (with a count > 0) and then get no results.

For some reason, two hierarchy filters == zero results

**Comment by mhogeweg** [comment]
Geoportal added the hierarchical search facet: https://github.com/Esri/geoportal-server-catalog/wiki/Configure-Hierarchical-Search-Facet
