### ISSUE TITLE
Typo on ISO Evaluator breaks elastic collection on apiso_Format_s

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#275]
Spent a few days trying to figure out why the **apiso_Format_s** field was not populating when uploading XML ISO metadata. There is a typo on the _name_ xpath.
This file: /geoportal/src/main/resources/metadata/js/EvaluatorFor_ISO.js

line 59:  `G.evalProps(task,item,root,"apiso_Format_s","gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat/gmd:MD_Format/gmd:name/*/text()");`

change /name/ to **/gmd:name/**

Now it works!! :)

**Comment by valentinedwv** [comment]
commit
1f0cc04346ff7a68cbdce2c63f050761cfb053e5
