### ISSUE TITLE
.xml file object into dataroot.js

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#276]
hi,
metadata in geoprtal sercver 2.6.1 can be uploaded using xml file option(Ingest Metadata>>Select xml file).

I want to get hold of that .xml file object into dataroot.js ?

I want to do some preprocessing into metadata iso-1995 when it is loaded using  .xml file.

Any Help Please?

Thanks  in Advance.

**Comment by mhogeweg** [comment]
the proper place to do any processing on the published XML (whether through harvesting or XML upload) is in the evaluators you can find in ...\WEB-INF\classes\metadata\js

This [wiki page](https://github.com/Esri/geoportal-server-catalog/wiki/Mapping-XML-element-to-Elasticsearch-field) has some information on how to modify the evaluators.

You can do pretty interesting things here. For example, I have integrated [LocateXT](https://www.esri.com/en-us/arcgis/products/locatext/overview) and our [OntologyService ](http://gptogc.esri.com/OntologyService/) in the publication pipeline. These two attempt to georeference the XML (in case there is no spatial extent provided) or enrich it with additional related terms.
