### ISSUE TITLE
Geoportal Server 2.6.2 in Disconnected environment

### ISSUE THREAD

**Issue by MarcSimon007** [Esri/geoportal-server-catalog#277]
Trying to use the Geoportal Server 2.6.2 in Disconnected environment, but in the //Geoportal/index.html there is a referencing to a cloud library, this gives errors. How to bring this library local?
L42: <script src="//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>

**Comment by zguo** [comment]
There are two approaches: one is to download the file and reference a local copy, the other is to comment out c3 at L42, as C3 is only used in some non default application of geoportal.
