### ISSUE TITLE
Editor 19115-2 ISO 19119 service taxonomy

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#28]
No codelist showing

**Comment by rafteryd** [comment]
There is no codelist showing when trying to create a Gemini (Service) metadata record either:

![nocodelist](https://cloud.githubusercontent.com/assets/21330930/18079835/93b6a4bc-6e8a-11e6-921b-2beeab9c39bc.png)

**Comment by umacgillivray** [comment]
The ISO Service Category issue was resolved, it affects the INSPIRE and GEMINI profiles.
https://github.com/Esri/geoportal-server-catalog/commit/346ab068156c83ce64bfe385d01e6b20c5b0d32e
