### ISSUE TITLE
any issue if i will use elastic search 7.1.1?

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#287]
new elastic search 7.1.1 is released .
Has anyone tried configuring geoportal server with ES 7.1.1?
Is it even possible?

**Comment by mhogeweg** [comment]
We have not tested with ES 7.x yet. If you want to go ahead and test it, we can look at any issues that may arise.

**Comment by DeveshScientist** [comment]
Hi,
Thanks for reply ...

Since 'item' type of metadata index is hard coded at multiple places, it is becoming difficult to test.

I have remove 'item' type from hard coding and i was able to manage the connection with elastic search 7.1.1 .

but metadata ingestion module is not publishing the data into  elastic search 7.1.1 and throwing an error as "invalid request : 404 gateway not found".

how can i remove "item" type fully from the geoportal application 2.6.1 because elastic search 7.1.1 donot support index type like 'item'.

Thanks and Regards.
