### ISSUE TITLE
search based on attribute alias?

### ISSUE THREAD

**Issue by DeveshScientist** [Esri/geoportal-server-catalog#288]
Hi,

metadata structure is very nested (example :- citation >>distribution) hence to search based on metadata attribute , user have to type the full path of attribute (example :- citation.distribution.date).

is it possible in current edition ? if not , then 
are we planing to have support for search based on attribute alias?

Or any other work around idea will be  very helpful for immediate solution. 

Thanks and Regards

**Comment by mhogeweg** [comment]
hi, when publishing metadata (XML) to geoportal, we pull out elements into a JSON structure to be stored in elasticsearch. You can configure search facets based on the fields in that JSON without needing the full xpath to the element/attribute in the XML. 

Updating the search panel with a new facet is described here: https://github.com/Esri/geoportal-server-catalog/wiki/Customize-search-panel

The mapping of XML elements/attributes to elastic JSON fields is described here: https://github.com/Esri/geoportal-server-catalog/wiki/Mapping-XML-element-to-Elasticsearch-field
