### ISSUE TITLE
Search for URL produces 'An error occurred'

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#29]
https://wateroffice.ec.gc.ca/

![image](https://cloud.githubusercontent.com/assets/851784/18063406/b2a5f05e-6ddf-11e6-9243-91df0d56907c.png)

**Comment by umacgillivray** [comment]
Elasticsearch is throwing an exception while parsing the query string. We aren't escaping special characters prior to submitting. We submit a "query_string", maybe we should switch to a "simple_query_string" to avoid issues like this.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by umacgillivray** [comment]
Installed https://github.com/Esri/geoportal-server-catalog/commit/39c63564394797b539103961612369adac0d0630

For the search text box, switched from query_string to simple_query_string.

This can be changed on the fly from the dev console:
AppContext.appConfig.search.useSimpleQueryString = false

The default can be changed within:
app/context/app-config.js 

At some point we should provide this toggle within the UI.
