### ISSUE TITLE
Custom Element Creation

### ISSUE THREAD

**Issue by GISScience** [Esri/geoportal-server-catalog#290]
Hi,

GP 2.6.1
ES 6.4
Arcgis Javascript API 3.2

I want to create a table custom element like textarea , options , which exist in "metadata>form" path of arcgis js API. table element will help me to show data in grid format.

is there any other way to show data in grid form , any helping document with that respect to creating custom element like table?

Thanks and Regards,

**Comment by valentinedwv** [comment]
https://dojotoolkit.org/reference-guide/1.10/dojox/grid/index.html#dojox-grid-index

**Comment by vishnuvardhank7** [comment]
Hello Devesh,

I'm also looking for custom elements like a table and radio button did you get any information on the same. How to implement new kinds of elements like grid table, radio button, multi-select in the metadata form with proper work flow?

**Comment by mhogeweg** [comment]
Can you share the metadata profile you use that would require these custom elements?

**Comment by vishnuvardhank7** [comment]
> Can you share the metadata profile you use that would require these custom elements?

https://github.com/Esri/geoportal-server-catalog/issues/344
