### ISSUE TITLE
Access to metadata management features

### ISSUE THREAD

**Issue by HZGcoast** [Esri/geoportal-server-catalog#298]
Hi,

we just installed Geoportal Server Catalog v. 2.6.2. According to the features list the Sever Catalog should support the following metadata management options:
- edit metadata
- metadata approval status change
- allow metadata to add fields for custom use

We are currently harvesting a local folder and do not find these options for the harvested records. How can we do this? 

Geoportal 1 allowed for bulk editing of metadata. When will this be implemented in Geoportal 2?

**Comment by KathleenPate** [comment]
There is a **"bulk"** feature to the 2.6.2 portal. Once some data has been harvested you'll notice the options pop up when you are logged in. When we harvest, all the newly added docs are set to "posted". We then choose one of the new docs and in Admin mode click "options" to find various Admin choices.  One of the options will be to manage approval status. You can edit one, or all. (See screen shot below)

I have not found an easy way to **"edit"** the metadata xml content. We use a different editor.

To _Add a Field,_ use the **"Set Field"** option found within the "options" dropdown.  If you want a field to be present in every doc you can add your own sys variable.  I have done that.  It means creating about 4-6 new files and modifying about 8-10 more files.

_Set Approval Status pop-up_
![image](https://user-images.githubusercontent.com/13800356/63108025-34240280-bf43-11e9-981b-43b3ba8316c7.png)

_Set Field to all Harvested docs screen shot_

![image](https://user-images.githubusercontent.com/13800356/63108128-66356480-bf43-11e9-93bf-3c68870cf92e.png)

**Comment by mhogeweg** [comment]
hi, bulk editing of metadata is not supported in Geoportal. You can write your own bulk update functionality against the Geoportal API that provides access to GET/PUT and DELETE metadata using its identifier. 

See: https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/doc/api.txt

**Comment by mhogeweg** [comment]
before those approval status options become available you need to enable them in the configuration. please see the wiki: https://github.com/Esri/geoportal-server-catalog/wiki/Other-Configurations-For-Geoportal
