### ISSUE TITLE
Keyword searching only returns exact matches?

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server-catalog#3]
I'm using the out-of-the-box configuration of Geoportal 2.0 and the descriptive text for one metadata entry is:

> The dataset contains airports / landing strips for the respective StreetPro region. Major airports in capital cities are represented by regions showing layout of landing strips etc. Minor airports / landing strips are represented by point objects.

I'm finding that a keyword search on "airport" returns nothing, whereas "airports" returns a match. Shouldn't "airport" be considered a match?

![airports](https://cloud.githubusercontent.com/assets/133596/15528114/f8ae2b18-2283-11e6-9def-c97e27ff4b0f.png)

![airport](https://cloud.githubusercontent.com/assets/133596/15528120/02c79350-2284-11e6-901d-2d41dc66b728.png)

Here is the file that I uploaded: [Airports.xml](https://github.com/Esri/geoportal-server-catalog/files/280997/Airports.xml.txt)

Let me know if you need any further info.

**Comment by umacgillivray** [comment]
This is associated with Lucene analyzers and stemming. Elasticsearch uses the Standard Analyzer by default (no stemming), Geoportal inherits. We could specify the default for Geoportal within this file (any suggestions?) :
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/config/elastic-mappings.json

Here are a couple of links on the topic:
https://www.elastic.co/guide/en/elasticsearch/guide/current/configuring-analyzers.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/controlling-stemming.html

**Comment by mhogeweg** [comment]
[elastic says](https://www.elastic.co/guide/en/elasticsearch/guide/current/algorithmic-stemmers.html) that the Porter stemmer for English is old, but still the recommended english stemmer.

I suggest we configure this as the default and document pointers to where people can find more on configuring specific stemmers/analyzers and how this works with Geoportal Server.

**Comment by slead** [comment]
Cool, I'll leave it to you guys to sort out how to handle this.

I'd suggest that a non-technical user would expect "airport" to return "airports", so that behaviour should be default, with the option to configure it as required.

Thanks guys

**Comment by MapZombie** [comment]
Was this ever sorted?

**Comment by umacgillivray** [comment]
It was implemented:
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/config/elastic-mappings.json
