### ISSUE TITLE
need  to authenticate the geoportal server 2.6.1 using access token api

### ISSUE THREAD

**Issue by GISScience** [Esri/geoportal-server-catalog#302]
Geoportal server 2.6.1
Elastic search 6.8.0
**Requirement**:- Use only metadata ingestion part of geoportal in another application without login it in geoportal.

So i want to by pass the login screen and want to authenticate the username and password using basic authentication , or oauth or passing username and pass to iframe itself.

I want to render the geoportal server 2.6.1 into a <iframe> but i want to authenticate using passing parameter in iframe itself. how i can get the access token of geoportal in another app.
<iframe src="https:server:8080/geoportal2/oauth/token">
to achieve this i am maintaining same username and roles in myapplication and geoportal.

**Question**:- how can i get the token of geoportal server just by a put request or api call?
how can i pass the username and password to <iframe src="geoportal_server_path"> ,so that it will login automatically without getting login screen?

**Comment by zguo** [comment]
There are are info at below about this:

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/doc/api.txt

HTTP POST geoportal/oauth/token
Generates an OAuth access token.
The token can be supplied to subsequent requests as a query parameter: access_token=
The request should be POSTed via https using form-urlencoded parameters within the body.
Response Content Type: application/json
Required Query Parameters:
  grant_type: password
  client_id: geoportal-client
  username: the username
  password: the password

**Comment by zguo** [comment]
practical use of this api is demonstrated in code below:

https://github.com/Esri/geoportal-server-harvester/blob/master/geoportal-commons/geoportal-commons-gpt-client/src/main/java/com/esri/geoportal/commons/gpt/client/Client.java
