### ISSUE TITLE
How To: Use Get Request to capture all json details within a collection

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#307]
### How can we scan all the metadata json from a GET request?   
For example on the sandbox - below is one record's json http://geoss.esri.com/geoportal2/rest/metadata/item/211762839fff40ea963dc89e4f646308

Can we scan **_all_** the id’s from a parent url?
http://geoss.esri.com/geoportal2/rest/metadata/item

**Comment by valentinedwv** [comment]
Think that it is probably easiest to go straight to the elastic endpoint for JSON:
geoportal/elastic/*
and send a query that just returns ID's.

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/doc/api.txt

we have a tool that we use to create a sitemap:
https://github.com/CINERGI/xmlsitemap
