### ISSUE TITLE
create wiki page about how to create a custom metadata profile

### ISSUE THREAD

**Issue by zguo** [Esri/geoportal-server-catalog#319]

**Comment by andreiste** [comment]
Hello. I want to create a custom metadata profile, but I do not want to extend an existing one like the ISO 19115. I would like to create a metadata profile similar to the ArcGIS and FGDC metadata profiles, but with my own named elements and sections. I found the MyProfile example in the source code and it does work very well, but it is built upon the ISO 19115 metadata standard, and I assume that a lot of the code is inherited from it. I managed to create my Descriptor, my DocumentType, The Root, a nls folder where I store all the labels in js file, and a PortalItemTransformer that for now just inherites the arguments at postCreate. When I build the project and add the war file to Tomcat, in the Metadata Editor Dialog Window I have my InputText elements and I can view the output xml file written corectly with my elements, sections and data provided but for now I can not save the document... When I push the save button nothing happens. and there is no error message in the console. Can you please specify the steps required to create a custom metadata profile in this context and do you know what could be the cause of my error? Thank you very much in advance

**Comment by zguo** [comment]
Sorry we don't have the steps yet, we will be documenting the process as we develop the INSPIRE/GEMINI profiles. For the issue you might check the develop console to see if any errors there and check the network tab to see if any communication to the server. if the request was sent to the server there are some work on the server side for the custom profile (define the custom format and index mapping...)

**Comment by spatialbits** [comment]
As far as index mapping I think @zguo is referring to [this](https://github.com/Esri/geoportal-server-catalog/wiki/Mapping-XML-element-to-Elasticsearch-field)

**Comment by andreiste** [comment]
Thank you all for the advices! I will try the tips you offered me.

**Comment by marcelsip** [comment]
Hi everyone, are there any time plans when could we expect this documentation be finished? The ability to customize profiles is very important for our customers. Thanks in advance.

**Comment by mhogeweg** [comment]
implemented: https://github.com/Esri/geoportal-server-catalog/wiki/Customize-Metadata-Profiles
