### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by Alexey4eg54rus** [Esri/geoportal-server-catalog#322]
Hello! I want to install the latest version on Linux, but I don't find any instuctions. How can I install this software on Linux?

**Comment by mhogeweg** [comment]
First step is to get java, tomcat and elastic running. For Ubuntu:

Java:
https://linuxize.com/post/install-java-on-ubuntu-18-04/

Tomcat
https://help.ubuntu.com/lts/serverguide/tomcat.html

Elasticsearch:
https://tecadmin.net/setup-elasticsearch-on-ubuntu/

Geoportal is then a webapp to be deployed in tomcat. Only references to specific folders should need attention in terms of location and permissions.
