### ISSUE TITLE
Geoportal not correctly harvested

### ISSUE THREAD

**Issue by HZGcoast** [Esri/geoportal-server-catalog#326]
Hi everyone,

we have installed a new instance of Geoportal Server Catalog version 2.6.3. However, so far none of our colleagues has managed to harvest us via csw. Our endpoint is at https://coastmap.hzg.de/geoportal/csw 
We have tried harvesting our own csw endpoint from two different Geonetwork installations, but got error messages both time, stating that 'GetRecords' or (the other time) 'SearchResults' could not be found. Has anyone else trouble with being harvested via csw?

Kind regards!

**Comment by mhogeweg** [comment]
hi, I have been looking into this a bit and will talk to our developer @pandzel.

It appears I can harvest your geoportal via its own API, but also run into an issue harvesting it via CSW.
I notice the CSW capabilities includes operations URLs using http protocol, while the entire site is https. While this is not a problem, I do suggest looking at updating that.

What I think is happening is that when Harvester sends its GetRecords request, the response is as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecordsResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ows="http://www.opengis.net/ows" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/">
    <csw:SearchStatus timestamp="2020-05-28T19:07:43.729Z"/>
    <csw:SearchResults numberOfRecordsMatched="18" numberOfRecordsReturned="10" nextRecord="11" recordSchema="http://www.opengis.net/cat/csw/2.0.2" elementSetName="full">
        <gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink">
            <gmd:fileIdentifier>
                <gco:CharacterString>1,1,1-Trichloro-2,2-bis-(p-chlorophenyl)-ethane, Insecticide (Grain size &lt;63 microm) in sediment CAS: 50-29-3</gco:CharacterString>
            </gmd:fileIdentifier>
            <gmd:language>
                <gmd:LanguageCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/ML_gmxCodelists.xml#LanguageCode" codeListValue="eng">eng</gmd:LanguageCode>
            </gmd:language>
            <gmd:characterSet>
                <gmd:MD_CharacterSetCode codeListValue="utf8" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_CharacterSetCode"/>
            </gmd:characterSet>
            <gmd:hierarchyLevel>

```

Notice the fileIdentifier:
```1,1,1-Trichloro-2,2-bis-(p-chlorophenyl)-ethane, Insecticide (Grain size &lt;63 microm) in sediment CAS: 50-29-3```

when I run the GetRecordById request:
https://coastmap.hzg.de/geoportal/csw?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&id=1,1,1-Trichloro-2,2-bis-(p-chlorophenyl)-ethane,%20Insecticide%20(Grain%20size%20&lt;63%20microm)%20in%20sediment%20CAS:%2050-29-3

the response is an error:
```
<?xml version="1.0" encoding="UTF-8"?>
<ExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ows">
  <Exception exceptionCode="InvalidParameterValue" locator="id">
    <ExceptionText>Id not found.</ExceptionText>
  </Exception>
</ExceptionReport>

```

**Comment by HZGcoast** [comment]
Hi @mhogeweg ,

thank you for your quick response!
I do not think that the fileIdentifier is the issue, but I changed the long names to UUIDs nonetheless. When you request a record by GetRecordById, you need to use the ElasticSearch field "_id", which is also shown when opening the item as html from the Geoportal Server Catalog web interface.
Example:

- Item on website: https://coastmap.hzg.de/geoportal/rest/metadata/item/444f7e8b044342caa9a1dd483a96f508/html

- GetRecordById using ElasticSearch ID: https://coastmap.hzg.de/geoportal/csw?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&id=444f7e8b044342caa9a1dd483a96f508 (request works)

- GetRecordById using FileIdentifier: https://coastmap.hzg.de/geoportal/csw?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&id=5f187011-491f-43fa-9b95-d0636614bf81 (same error that you got, ID not found)

We also realized that a lot of links point to http instead of https. They all get rerouted to https automatically, but a lot of them are hard coded in for example geoportal/WEB-INF/classes/gs/config/csw2-capabilities.xml. We did not find an option to generally change all links to https.

Kind regards!

**Comment by mhogeweg** [comment]
hi, couple questions. Did you customize this geoportal? asking as the GetRecordById response should be a csw:Record of some type. See this:
http://geoss.esri.com/geoportal2/csw?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&outputSchema=&http://www.w3.org/2005/Atom&id=830877b9c8d04e9ba4b6064d52ddee35

have you forced the outputschema to be ISO?

The Harvester fails on reading the response, not because the unexpected format but because a Java IO functions fails to read and deliver content to the Harvester functions working with the response. It literally returns “<Unreadable>” string instead of anything which would resemble GetRecords response.

again, this makes us suspect you made changes to the code. please confirm.

**Comment by pandzel** [comment]
My observations:

1. Something forces to generate response like it would be outputSchema=http://www.isotc211.org/2005/gmd appended to the request,
2. Currently, there is no CSW profile within Harvester which would match workflow with such outputSchema appended,
3. It's easy to create such custom CSW profile (I did it),
4. But even with that custom profile Harvester will be unable to retrieve records due to mismatch in ID format, Marten mentioned earlier.

**Comment by HZGcoast** [comment]
You are right, we set up a custom profile. However, we changed it back to the original configuration and harvesting still doesn't work for us (which was the reason why we created the custom profile in the first place. as there seemed to be error messages related to Dublin Core and we only had metadata in ISO).
