### ISSUE TITLE
Can't find the XSLT details files

### ISSUE THREAD

**Issue by nad3r** [Esri/geoportal-server-catalog#33]
Hello there,

I am having a lot of trouble finding the xslt stylesheets for many types, especially the arcgis-details.xslt
The file seems to be referenced into : 
  "arcgis": {
    key: "arcgis",
    evaluator: G.evaluators.arcgis,
    interrogationXPath: "/metadata/Esri/ArcGISFormat",
    identifier: "ArcGIS-Metadata",
    detailsXslt: "metadata/details/arcgis-details.xslt",
}
But it is not included in the code and I can't find it anywhere.

Thank you for your help !!

**Comment by umacgillivray** [comment]
We don't yet have an xslt for ArcGIS metadata. The others are located here:
https://github.com/Esri/geoportal-server-catalog/tree/master/geoportal/src/main/resources/metadata/details

**Comment by xlhomme** [comment]
Hi we have a lot of error message : 
`{"error":{"message":"Could not make xslt template from /metadata/details/iso-details/xml-to-html-ISO.xsl"}}`
Can you explain us what need need to do in order to resolve this : 
Do I need to do something else than create the xslt and put it in the /metadata/details directory ?

**Comment by umacgillivray** [comment]
@xlhomme Are you running on a Linux server? 
If so we had to rename printtextlines.xsl to printTextLines.xsl

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/metadata/details/iso-details/printTextLines.xsl

**Comment by xlhomme** [comment]
Thanks it works !

Le 6 déc. 2016 8:31 PM, "Urban MacGillivray" <notifications@github.com> a
écrit :
