### ISSUE TITLE
base Url problem Atom, CSW, CSV, JSON formats

### ISSUE THREAD

**Issue by andreiste** [Esri/geoportal-server-catalog#332]
Hi,

I have a problem while outputing all the content of the geoportal in Atom, CSW, CSV, JSON formats etc. The problem is that for each item in the geoportal de URLs are written as follows: 
http://{hostname}:{port}/geoportal/rest/metadata/item/{itemid} for json
http://{hostname}:{port}/geoportal/rest/metadata/item/{itemid}/xml for xml
http://{hostname}:{port}/geoportal/rest/metadata/item/{itemid}/html for html

And they should be something like this:
https://mysite.domain.com/geoportal/rest/metadata/item/{itemid}
https://mysite.domain.com/geoportal/rest/metadata/item/{itemid}/xml
https://mysite.domain.com/geoportal/rest/metadata/item/{itemid}/html

When I access an item from the ItemCard the URL is correct but when I output all the content of the geoportal either in Atom, CSW, CSV, JSON format etc. the URLs are outputed wrong as above and as expected they do not return nothing when accessed externally. 

Is there a way to change the base URL for these services? I am using Geoportal Server Catalog 2.6.3. 

Thank you very much for the help in advance,
Andrei

**Comment by zguo** [comment]
I checked with our developer, he asked if there is a reverse proxy used, if yes you might change it in geoportal\WEB-INF\classes\gs\context\nashorn to see if it would work.

    // to override the base URL if you have a reverse proxy
    //requestInfo.baseUrl = "https://www.geoportal.com/geoportal";

**Comment by andreiste** [comment]
Thank you so much! This was the solution to my problem!
