### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server-catalog#333]
Search Box
#330 in Geoportal-server
Hi 

I went through the Lucene Search Text Queries(Lucene Search Syntax) in which it is mentioned that we should use double quotes ("world imagery") to get the search result containing those words directly after each other. Is there any other way to get the search result as most relevant without using the syntax (i.e., the double quotes or fields) given. For example, if we search just the phrase World imagery we should get the data containing those two words directly next to each other.

**Comment by mhogeweg** [comment]
Geoportal 2.x uses elasticsearch as the index. I suggest first reading up on elastic dsl: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
