### ISSUE TITLE
Problems with Portal for ArcGIS-authentication

### ISSUE THREAD

**Issue by scma-esrich** [Esri/geoportal-server-catalog#335]
Following your guidelines from https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-ArcGIS I still have trouble to implement it correctly.

The app-registration on the Portal-side works without any problems and Portal's login-interface is propagated through. However, when I enter valid credentials, in the Geoportal Server-GUI there still is the "Sign In"-hyperlink to the top-right and looking at the request, I get the following error:
![image](https://user-images.githubusercontent.com/45851791/94816319-f2327600-03fb-11eb-819a-0d60b18ab3ec.png)

Do I need to add the users to some form of user-repository on the geoportal-server-catalog side, although I want to use ArcGIS-authentication?

Are the two parameters `geoportalPublishersGroupId` and `geoportalAdministratorsGroupId` mandatory or optional and only to be used in combination with https://github.com/Esri/geoportal-server-catalog/wiki/Group-Access-Configuration?

Thanks in advance for any hints!

**Comment by G-NOCM** [comment]
@scma-esrich Did you end up resolving this issue? We are experiencing the same with a project we are working on and would appreciate any advice you could provide. Many thanks in advance.

**Comment by G-NOCM** [comment]
Thank you. Any help would be appreciated.

**Comment by mhogeweg** [comment]
hi, you can use `geoportalAdministratorsGroupId` and `geoportalPublishersGroupId` to designate groups in ArcGIS Portal who's members will be considered administrators and publishers in Geoportal Server respectively. If you set these groups, the membership of the user of these groups determines their role in Geoportal Server. If you do not set these groups, the role of the user in Geoportal Server will depend directly on the role of that user in ArcGIS Portal, as follows:

- Administrator becomes Administrator 
- Publisher becomes Publisher 
- User becomes User 
- Other ArcGIS Portal roles become 'no role' in Geoportal Server, being the same as anonymous users
