### ISSUE TITLE
ElasticSearch database - Operate on independent machine from geoportal webapp?

### ISSUE THREAD

**Issue by mfforte** [Esri/geoportal-server-catalog#336]
Can elasticsearch run on an independent server (other than one hosting geoportal webapp)?

If so, is this configured in [Tomcat8]/webapps/geoportal/WEB-INF/classes/config/app-context.xml - any other places?

We have a security limitation that requires database servers be independent of web applications.

Thanks,
Mike

**Comment by zguo** [comment]
yes you can run elasticsearch on separate server from geoportal, the  configure file is app-context.xml.

**Comment by mfforte** [comment]
Many thanks for your reply!
