### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by jjosserand** [Esri/geoportal-server-catalog#339]
Why is there no longer a v2.6.2 showing on the installation page at [https://github.com/Esri/geoportal-server-catalog/wiki/Installation](https://github.com/Esri/geoportal-server-catalog/wiki/Installation) ???

Please respond to me at jesse.josserand@gdit.com -- thanks!

**Comment by zguo** [comment]
I would recommend to install 2.6.4. If you have to use 2.6.2, please follow the installation guide for 2.6.1. the installation steps for 2.6.2 is the same as 2.6.1.

Thanks,

**Comment by jjosserand** [comment]
Thank you. 1 more question if you please... I know I must install ElasticSearch 7.5.0 first then Geoportal v2.6.x, but where in the process is Harvester installed? Before those? After both? Between ElasticSearch and Geoportal? In my architecture ES and GP are on one server, while Harvester is on another, and my HTTPD Proxy server is on yet another server.

**Comment by mhogeweg** [comment]
Harvester is really independent nowadays (compared to 1.x) of Catalog. Can run anywhere where you can run Tomcat (I typically run it from my laptop, while the Catalog is on some server). And therefore it can be installed whenever.

**Comment by jjosserand** [comment]
Excellent. Thanks so much!

**Comment by jjosserand** [comment]
I have a new question. After deploying Harvester 2.6.1 on one server and setting up reverse proxy, then deploying Geoportal 2.6.2 on another server (and setting up its reverse proxy), I am able to harvest data into it, but when I view the pom file, it says 2.6.3. Is that a typo in 2.6.2??? ...or should I be concerned. My team lead actually made the discovery, when verifying versions for approvals from gov't management on our project.

**Comment by jjosserand** [comment]
Perhaps I'm actually using Geoportal 2.6.3 (since that was what my developers gave me to deploy) with Harvester 2.6.1 (to avoid the problems in Harvester 2.6.2 I previously had).
QUESTION: Is that an acceptable configuration (that is, Geoportal 2.6.3 with Harvester 2.6.1)?

Also, though Geoportal 2.6.3 and above claim to need JDK11 and Tomcat9, the copy of 2.6.3 I'm running is working find with JRE8 and Tomcat8. 
QUESTION: Is that ok?

Finally, I have tried deployments using JDK11 and Tomcat9 with version 2.6.3 of Geoportal and Harvester; however, JDK11/Tomcat9 seem to break my OpenAM deployment we use for authentication.
Do you have any recommendations or comments about this?

**Comment by mhogeweg** [comment]
generally, we recommend newer releases of the underlying components (java, tomcat, elastic) but as you see, the apps typically work with earlier ones as well. Between catalog/harvester, there is not a direct release dependency. The API the harvester uses to publish to catalog has not changed since early days of 2.x. 

regarding OpenAM, are all these components on the same machine? I'd look at compatibility of OpenAM with the various other components. I have had OpenAM/OpenDS, tomcat, geoportal, etc all on 1 laptop just fine. But this would not be a typical production deployment.

**Comment by jjosserand** [comment]
Thanks for the quick response. Glad to hear that about catalog/harvester relationship version-wise.
OpenAM is on one Centos7 box, Harvester on another, and Geoportal/ElasticSearch on another with reverse proxies set up on our httpd server (also a separate box -- all of them centos7, but soon to be rhel7).

**Comment by mhogeweg** [comment]
that should work. the issues with OpenAM could then be related to certificates/ports? since they're not on the same machine I can't see Tomcat causing interference

**Comment by jjosserand** [comment]
Each of the boxes (except the httpd server) have java and tomcat installed.
Our goal is to have the same versions of those across all 3 servers (openam, harvester, and geoportal servers).
However, since jdk11/tomcat9 seem to break OpenAM, what do you think the implications would be of running JRE8/Tomcat8 on the OpenAM server and jdk11/tomcat9 on the other 2? Would that work?
Should I just find a way to make OpenAM work with jdk11/tomcat9? Would that be better?

What version of OpenAM are you running with jdk11/tomcat9?

**Comment by mhogeweg** [comment]
running a different version for OpenAM should be no problem. it's a web service as far as Geoportal is concerned!

I see some discussion on issues with OpenAM and newer tomcat versions:
https://backstage.forgerock.com/knowledge/kb/article/a73027813

this may then need upgrading OpenAM to a version that supports JRE9/Tomcat 9
