### ISSUE TITLE
Changing Item Card Properties eg. Title, Owner

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#34]
Hello, I am trying to find a way to change the search results Item Card properties a little bit. 
For example instead of the Title showing up at the top of the card in Bold, I would like the Filename there in bold and the Title within the description text underneath.  

Would somebody be able to point me into the right direction on how to make this change?
![image](https://cloud.githubusercontent.com/assets/17599236/20075512/a8c5487a-a4f1-11e6-9bc1-f0f8cfbc7483.png)

Thanks!

**Comment by umacgillivray** [comment]
https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/app/search/ItemCard.js

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/app/search/templates/ItemCard.html

[tomcat]/webapps/geoportal/app/search/ItemCard.js

line 64:
util.setNodeText(this.titleNode,item.title);
change to:
util.setNodeText(this.titleNode,item.someOtherJsonProperty);

line 329:
      if (text.length > 0) {
        util.setNodeText(this.ownerAndDateNode,text);
      }
change to:
      if (text.length > 0) text += " ";
      text += item.title
      if (text.length > 0) {
        util.setNodeText(this.ownerAndDateNode,text);
      }

**Comment by MapZombie** [comment]
Thanks this works.
