### ISSUE TITLE
Sample Site: Where is the Sandbox

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#342]
Does esri still support an example _demonstration_ site of the Geoportal Server product?  There used to be a sandbox site where I could view (and test) the latest code but I can't find it now.  The link used to be on the homepage, but the link could also be put on the first Wiki page if you have it.  :) Thank you.

**Comment by mhogeweg** [comment]
hi! yes, we do have both v1 and v2 demo sites:

v1 - https://gptogc.esri.com/geoportal
v2 - https://gptogc.esri.com/geoportal2

for version 2 we also have a different configuration that contains several 100,000 images as its catalog:
https://geoss.esri.com/imagecatalog

**Comment by KathleenPate** [comment]
👍   Great.  _Thank you!!_

**Comment by mhogeweg** [comment]
:-)
