### ISSUE TITLE
Trouble setting up with Azure App services

### ISSUE THREAD

**Issue by Aegman** [Esri/geoportal-server-catalog#343]
Hi,

I've followed the installation steps to setup GeoPortal 2.6.4 (AppService) and ElasticSearch 7.5.0 (VM) in Azure, both are working. We're using simple auth for testing.

I can create and upload metadata records through GeoPortal frontend to ElasticSearch, but the home/search page is throwing an error:

```Unable to load ./elastic/metadata_v1/item/_search?from=0&size=10&sort=title.sort%3Aasc status: 500 and an error in handleAs: transformation of response```

The response is:

```Exception

java.lang.IllegalStateException: A filter or servlet of the current chain does not support asynchronous operations.
	org.apache.catalina.connector.Request.startAsync(Request.java:1690)
	org.apache.catalina.connector.Request.startAsync(Request.java:1682)
	org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1043)
	javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:383)
	javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:383)
...
```

I can see my metadata using http://<server>:9200/metadata_v1/_search

There is nothing useful (nothing at all) in the logs.

Any idea what may be wrong?

**Comment by mhogeweg** [comment]
hi. We have seen this being resolved by using ```<async-supported>true</async-supported>``` in web.xml.

in my geoportal web.xml I have this:
```
  <filter>
    <filter-name>springSecurityFilterChain</filter-name>
    <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    <async-supported>true</async-supported>
  </filter>
```

**Comment by Aegman** [comment]
Hi @mhogeweg  - Thanks for the quick reply, unfortunately that parameter is already set in web.xml. Is there anything else I should look in to?

**Comment by mhogeweg** [comment]
adding @pandzel to this thread.

**Comment by pandzel** [comment]
I have no direct experience with Azure, neither I've experienced mentioned issue. However, all the information I found points to the solution @mhogeweg already cited: 'async-supported' flag. That said it's also true that this flag is in every possible place in web.xml already. I am wondering if anyone has succeeded with deployment on Azure...

**Comment by Aegman** [comment]
Apologies returning to this late, the issues were resolved (thansk to @mhogeweg)  by adding some filters to the WEB-INF/web.xml file:
```
  <!-- Filters required to function inside an Azure App Service -->
  <filter>
    <filter-name>EasyAuthFilter</filter-name>
    <filter-class>com.microsoft.azure.appservice.EasyAuthFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>

  <filter>
    <filter-name>AppServiceFilter</filter-name>
    <filter-class>com.microsoft.azure.appservice.filters.AppServiceFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>
  <!-- End Azure Filters -->
```
I'm not sure if adding these filters will cause issues when deploying outside an Azure app service, so use with caution.
