### ISSUE TITLE
Custom Input Fields in Metadata Form

### ISSUE THREAD

**Issue by vishnuvardhank7** [Esri/geoportal-server-catalog#344]
Hello,

I'm trying to create a custom metadata profile. How do I add a new type of input field in the metadata form?
I want to add a group of radio buttons and a multi-select dropdown in a proper way. I can able to add in the UI but the selected values not showing/rendering in the XML.

![image](https://user-images.githubusercontent.com/41356490/98362061-9ee2c180-2052-11eb-8ee1-54066f6c47ee.png)

![image](https://user-images.githubusercontent.com/41356490/98362203-d5b8d780-2052-11eb-99ca-604e4e64d2b4.png)

Can you please guide me?

```
<div data-dojo-type="esri/dijit/metadata/form/Element" 
     data-dojo-props="target:'gmd:version',label:'${i18nIso.MD_Format.version}'">
  <div data-dojo-type="esri/dijit/metadata/form/iso/InputMultiSelect" 
       data-dojo-props="target:'gmd:attributes'"></div>
</div>

**Comment by mhogeweg** [comment]
how do the radio buttons relate to the multi-select list? if the content in the multi-select list depends on the choice in the radio buttons, you could change this to use tabs instead of radio buttons. take a look at the ISO 19115 (Data) editor, then Identification > Constraints. After you turn on the constraints, you'll see this:

![image](https://user-images.githubusercontent.com/394890/99192442-bcd1b580-2727-11eb-83d4-955252e4afdb.png)

The tabs are the radio buttons, the contents of each tab could be your specific list.

**Comment by vishnuvardhank7** [comment]
No. In my use cases, the radio button and multi-select are independent.

**Comment by mhogeweg** [comment]
here is a snippet from the ISO 19115 (Data) editor for a single-choice drop-down list:
```
<div data-dojo-attach-point="containerNode">
  <div data-dojo-type="esri/dijit/metadata/form/iso/CodeListElement"
    data-dojo-props="target:'gmd:CI_DateTypeCode'">
    <div data-dojo-type="esri/dijit/metadata/form/iso/CodeSpaceAttribute"></div>
    <div data-dojo-type="esri/dijit/metadata/form/iso/CodeListAttribute"
      data-dojo-props="value:'${codeListPrefix}CI_DateTypeCode'"></div>
    <div data-dojo-type="esri/dijit/metadata/form/iso/CodeListValueAttribute">
      <div data-dojo-type="esri/dijit/metadata/form/InputSelectOne">
        <div data-dojo-type="esri/dijit/metadata/form/Options">
          <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'',value:''"></div>
          <div data-dojo-type="esri/dijit/metadata/form/Option"
            data-dojo-props="label:'${i18nIso.CI_DateTypeCode.creation}',value:'creation'"></div>
          <div data-dojo-type="esri/dijit/metadata/form/Option"
            data-dojo-props="label:'${i18nIso.CI_DateTypeCode.publication}',value:'publication',selected:true"></div>
          <div data-dojo-type="esri/dijit/metadata/form/Option"
            data-dojo-props="label:'${i18nIso.CI_DateTypeCode.revision}',value:'revision'"></div>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by mhogeweg** [comment]
here is a snippet from an FGDC editor that allows multi-select of states:

```
<div data-dojo-type="esri/dijit/metadata/form/Element"   data-dojo-props="target:'placekey',minOccurs:1,maxOccurs:'unbounded', label:'States'">
  <div data-dojo-type="esri/dijit/metadata/form/InputSelectMany" data-dojo-props="">
    <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'Alabama',value:'Alabama'"></div>
    <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'Alaska',value:'Alaska'"></div>
    <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'Arkansas',value:'Arkansas'"></div>
    <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'California',value:'California'"></div>
    <div data-dojo-type="esri/dijit/metadata/form/Option" data-dojo-props="label:'Wyoming',value:'Wyoming'"></div>
  </div>
</div>
```

**Comment by mhogeweg** [comment]
in your case, the radio buttons and the multi-select field need to be separate divs. in your example they are nested. You'll see in the two examples, we have standard UI elements, like:

- esri/dijit/metadata/form/InputSelectOne
- esri/dijit/metadata/form/InputSelectMany

you need to include the choices in the div for each of the input elements as shown above. the location in the metadata is driven from the target value in the data-dojo-props attribute of the Element div.
