### ISSUE TITLE
sandbox url in README.md is outdated

### ISSUE THREAD

**Issue by andreasplesch** [Esri/geoportal-server-catalog#350]
The url linking to the [sandbox site](url) here

https://github.com/Esri/geoportal-server-catalog#cant-wait-to-get-started

should become

https://gptogc.esri.com/geoportal2

I can provide a quick PR if desired.

**Comment by mhogeweg** [comment]
thanks. just updated. the demo server is feeling its age, so we will do some maintenance on it.

**Comment by andreasplesch** [comment]
Thanks !
