### ISSUE TITLE
Adding additional fields & info in the item card

### ISSUE THREAD

**Issue by moco32** [Esri/geoportal-server-catalog#355]
I am using a custom profile at the moment with a few extra fields /values and I am trying to add them in the card item, for example.

![NovicaJ_1-1615382777952](https://user-images.githubusercontent.com/23172444/112071389-edab7680-8b6f-11eb-8f65-6ceceb9bf2b9.png)

I've been trying something like this, in the EvaluatorFor_ISO.js but it's not working, I simply cannot add the two new fields in the json

` 
    /* general */
    G.evalProp(task,item,root,"fileid","gmd:fileIdentifier/*/text()");
    G.evalProp(task,item,iden,"title","gmd:citation/gmd:CI_Citation/gmd:title/*/text()");
    G.evalProp(task,item,iden,"description","gmd:abstract/gco:CharacterString");
    G.evalProps(task,item,root,"keywords_s","//gmd:MD_TopicCategoryCode | //gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/*/text() ");
    G.evalProp(task,item,iden,"thumbnail_s","gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:fileName/gco:CharacterString");
    G.evalProps(task,item,root,"contact_organizations_s","//gmd:CI_ResponsibleParty/gmd:organisationName/*/text()");
    G.evalProps(task,item,root,"contact_people_s","//gmd:CI_ResponsibleParty/gmd:individualName/*/text()");
    G.evalProps(task,item,root,"price","myprofile:price/*/text()");
    G.evalProps(task,item,root,"tax","myprofile:tax/*/text()");
`
Any pointers on how to proceed?

**Comment by mhogeweg** [comment]
hi, just like you had to do when creating the metadata editor, the evaluators need to know the namespace associated with the prefix ```myprofile```. You can add a URI for this namespace in ```Evaluator.js```. Look for the function ```G._initializeTask```.

**Comment by moco32** [comment]
@mhogeweg 
So, I'd need something like this in the `G._initializeTask`
`  nsmap.put("myprofile","what goes here?");`

**Comment by mhogeweg** [comment]
the same as what you have for the namespace URI in the XML editor. Remember in geoportal/app/gxe/types/myprofile/base I said to insert the following function in DataDocumentType.js?

```
    initializeNamespaces: function() {
      this.addNamespace("myprofile", "http://www.example.com/myprofile");
    }
```

the [namespace URI](https://www.w3schools.com/xml/xml_namespaces.asp) in this case is ```http://www.example.com/myprofile``` (it is a type of [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)). ```myprofile``` is a namespace prefix, which is a convenient way of referring to a namespace in an XML document without having to include the full URI.

in ```G.initializeTask``` you would include:
```
nsmap.put("myprofile","http://www.example.com/myprofile"); 
```

**Comment by moco32** [comment]
I added the URI in the `G.initializeTask` as instructed but it's still not working

**Comment by moco32** [comment]
@mhogeweg 
maybe I need to add something in the `xslt` files in web-inf/classes/metadata/xslt?

**Comment by moco32** [comment]
@mhogeweg 
I also tried adding this `G.evalProps(task,item,root,"price","myprofile:price/*/text()");` in other evaluators like the Cinergi one.
No results again. Any pointers you might have? :)

**Comment by mhogeweg** [comment]
can you share a sample XML file in this profile?

**Comment by moco32** [comment]
@mhogeweg here is a sample XML with the custom `myprofile` profile

[xmlSampleForMarten.zip](https://github.com/Esri/geoportal-server-catalog/files/6192919/xmlSampleForMarten.zip)

**Comment by moco32** [comment]
@mhogeweg also, here's the [LINK ](https://file.io/HfKDk0Du0eMO)to my geoportal server catalog, if you need it.

**Comment by mhogeweg** [comment]
I removed the various entries where you tried setting the price/tax fields and only left this in function ```evalBase()``` in file ```EvaluatorFor_ISO.js```:

```
    var price = G.Val.chkDbl(G.getString(task, root, "//myprofile:price/gco:CharacterString/text()"), null);
    G.writeProp(item, "price_f", price);

    var tax = G.Val.chkDbl(G.getString(task, root, "//myprofile:tax/gco:CharacterString/text()"), null);
    G.writeProp(item, "tax_f", tax);
```

This gets the value of the XML elements using an absolute xpath and then turns that value in a float before storing in the fields. The suffix _f is important as this tells Elastic how to index the value. This also makes it possible to use the tax/price values in search facets.

**Comment by moco32** [comment]
@mhogeweg 
I also removed all the entries for price/tax and only left the above lines of code you have provided me with but I still don't have the price or tax fields in the json. This is what my json looks like
`{
   "_index":"metadata_v1",
   "_type":"_doc",
   "_id":"0fa6011c97cb4c16817aef0c33d4a188",
   "_version":1,
   "_score":1,
   "_source":{
      "fileid":"1616573778993r5163034513422675",
      "title":"orgName",
      "description":"orgName",
      "keywords_s":[
         "farming"
      ],
      "contact_organizations_s":[
         "orgName"
      ],
      "apiso_Identifier_s":"1616573778993r5163034513422675",
      "apiso_Title_txt":"orgName",
      "apiso_Abstract_txt":"orgName",
      "apiso_OrganizationName_txt":"orgName",
      "apiso_Subject_txt":[
         "farming"
      ],
      "apiso_TopicCategory_s":[
         "farming"
      ],
      "apiso_Type_s":"dataset",
      "apiso_Modified_dt":"2021-03-24T00:00:00Z",
      "apiso_PublicationDate_dt":"2021-03-24T00:00:00Z",
      "apiso_HasSecurityConstraints_b":false,
      "envelope_geo":[
         {
            "type":"envelope",
            "coordinates":[
               [
                  -180,
                  90
               ],
               [
                  180,
                  -90
               ]
            ]
         }
      ],
      "envelope_cen_pt":[
         {
            "lat":0,
            "lon":0
         }
      ],
      "apiso_Lineage_txt":[
         "orgName"
      ],
      "apiso_SpecificationTitle_txt":[
         "orgName"
      ],
      "apiso_SpecificationDateType_txt":[
         "publication"
      ],
      "app_editor_s":"gxe",
      "sys_created_dt":"2021-03-24T08:16:56.898Z",
      "sys_modified_dt":"2021-03-24T08:16:56.898Z",
      "sys_xmlmodified_dt":"2021-03-24T08:16:56.898Z",
      "sys_owner_s":"admin",
      "sys_owner_txt":"admin",
      "sys_metadatatype_s":"iso19115",
      "sys_xml_clob":"<?xml version="1.0" encoding="UTF-8"?><gmd:MD_Metadata xmlns:myprofile=""http":" xmlns:gmd=""http"://www.isotc211.org/2005/gmd" xmlns:gco=""http"://www.isotc211.org/2005/gco" xmlns:srv=""http"://www.isotc211.org/2005/srv" xmlns:gml=""http"://www.opengis.net/gml/3.2" xmlns:gmx=""http"://www.isotc211.org/2005/gmx" xmlns:xlink=""http"://www.w3.org/1999/xlink" xmlns:xsi=""http"://www.w3.org/2001/XMLSchema-instance"> <gmd:fileIdentifier> <gco:CharacterString>1616573778993r5163034513422675</gco:CharacterString> </gmd:fileIdentifier> <gmd:language> <gco:CharacterString>en</gco:CharacterString> </gmd:language> <gmd:hierarchyLevel> <gmd:MD_ScopeCode codeSpace="ISOTC211/19115" codeList=""http"://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue=""dataset"">dataset</gmd:MD_ScopeCode> </gmd:hierarchyLevel> <gmd:contact> <gmd:CI_ResponsibleParty> <gmd:organisationName> <gco:CharacterString>orgName</gco:CharacterString> </gmd:organisationName> <gmd:contactInfo> <gmd:CI_Contact> <gmd:address> <gmd:CI_Address> <gmd:electronicMailAddress> <gco:CharacterString>orgName</gco:CharacterString> </gmd:electronicMailAddress> </gmd:CI_Address> </gmd:address> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeSpace="ISOTC211/19115" codeList=""http"://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue=""pointOfContact"">pointOfContact</gmd:CI_RoleCode> </gmd:role> </gmd:CI_ResponsibleParty> </gmd:contact> <gmd:dateStamp> <gco:Date>2021-03-24</gco:Date> </gmd:dateStamp> <gmd:metadataStandardName> <gco:CharacterString>MyProfile</gco:CharacterString> </gmd:metadataStandardName> <gmd:metadataStandardVersion> <gco:CharacterString>1.0</gco:CharacterString> </gmd:metadataStandardVersion> <gmd:identificationInfo> <gmd:MD_DataIdentification> <gmd:citation> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>orgName</gco:CharacterString> </gmd:title> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2021-03-24</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeSpace="ISOTC211/19115" codeList=""http"://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue=""publication"">publication</gmd:CI_DateTypeCode> </gmd:dateType> </gmd:CI_Date> </gmd:date> </gmd:CI_Citation> </gmd:citation> <gmd:identifier> <gmd:MD_Identifier> <gmd:code> <gco:CharacterString>1616573779223r4292964396317702</gco:CharacterString> </gmd:code> </gmd:MD_Identifier> </gmd:identifier> <gmd:abstract> <gco:CharacterString>orgName</gco:CharacterString> </gmd:abstract> <gmd:language> <gco:CharacterString>en</gco:CharacterString> </gmd:language> <gmd:topicCategory> <gmd:MD_TopicCategoryCode>farming</gmd:MD_TopicCategoryCode> </gmd:topicCategory> <gmd:extent> <gmd:EX_Extent> <gmd:geographicElement> <gmd:EX_GeographicBoundingBox> <gmd:westBoundLongitude> <gco:Decimal>-180</gco:Decimal> </gmd:westBoundLongitude> <gmd:eastBoundLongitude> <gco:Decimal>180</gco:Decimal> </gmd:eastBoundLongitude> <gmd:southBoundLatitude> <gco:Decimal>-90</gco:Decimal> </gmd:southBoundLatitude> <gmd:northBoundLatitude> <gco:Decimal>90</gco:Decimal> </gmd:northBoundLatitude> </gmd:EX_GeographicBoundingBox> </gmd:geographicElement> </gmd:EX_Extent> </gmd:extent> </gmd:MD_DataIdentification> </gmd:identificationInfo> <gmd:dataQualityInfo> <gmd:DQ_DataQuality> <gmd:scope> <gmd:DQ_Scope> <gmd:level> <gmd:MD_ScopeCode codeSpace="ISOTC211/19115" codeList=""http"://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue=""dataset"">dataset</gmd:MD_ScopeCode> </gmd:level> </gmd:DQ_Scope> </gmd:scope> <gmd:report> <gmd:DQ_DomainConsistency> <gmd:result> <gmd:DQ_ConformanceResult> <gmd:specification> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>orgName</gco:CharacterString> </gmd:title> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2021-03-24</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeSpace="ISOTC211/19115" codeList=""http"://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue=""publication"">publication</gmd:CI_DateTypeCode> </gmd:dateType> </gmd:CI_Date> </gmd:date> </gmd:CI_Citation> </gmd:specification> <gmd:explanation> <gco:CharacterString>orgName</gco:CharacterString> </gmd:explanation> <gmd:pass/> </gmd:DQ_ConformanceResult> </gmd:result> </gmd:DQ_DomainConsistency> </gmd:report> <gmd:lineage> <gmd:LI_Lineage> <gmd:statement> <gco:CharacterString>orgName</gco:CharacterString> </gmd:statement> </gmd:LI_Lineage> </gmd:lineage> </gmd:DQ_DataQuality> </gmd:dataQualityInfo> <myprofile:price> <gco:CharacterString>5585</gco:CharacterString> </myprofile:price> <myprofile:tax> <gco:CharacterString>5</gco:CharacterString> </myprofile:tax> </gmd:MD_Metadata>",
      "sys_xmlmeta_obj":{
         "mimetype":"application/xml",
         "hash":"-8469304827899881853:184388615160123186:5587",
         "date":"2021-03-24T08:16:56.908Z",
         "size":5587
      }
   }
}`

**Comment by moco32** [comment]
@mhogeweg 
I also tried replacing the `item` & `root` variable with `iden`, but I still get no changes in the JSON.

**Comment by mhogeweg** [comment]
I emailed a link to Novica to a onedrive folder with the updated geotest webapp. I also configured a search facet for price:

![image](https://user-images.githubusercontent.com/394890/112380828-171aee00-8ca7-11eb-89b5-69ae1e5a7d85.png)
