### ISSUE TITLE
Catalog returns null items

### ISSUE THREAD

**Issue by moco32** [Esri/geoportal-server-catalog#357]
I am working on a specific scenario. So with external help, I have created a custom profile with additional fields. We extracted the additional fields from the XML in the JSON. Creating new metadata works fine but the index page does not work now. 
All I get is this
![image](https://user-images.githubusercontent.com/23172444/113052825-e6a3ea00-91a7-11eb-8f03-760c2afdcb24.png)

and I do have metadata, as seen below.
![image](https://user-images.githubusercontent.com/23172444/113052903-fc191400-91a7-11eb-9807-abe7173d286a.png)

If anyone has any idea or pointers what could be causing this, please let me know. I have tried with ElasticSearch, 6.4, 7.5, 7.11, none of them show the metadata. It all started after I extracted the additional two fields from the XML in the JSON. Here's a download [link ](https://easyupload.io/je66qa)for my catalog. Maybe another pair of eyes can see what I am missing.

**Comment by mhogeweg** [comment]
are you certain your geoportal looks at this particular index? especially since you mention you have tried multiple versions of elastic. please include the output of: ```http://localhost:9200/_cat/indices``` and ```http://localhost:9200/_cat/aliases```

**Comment by moco32** [comment]
![image](https://user-images.githubusercontent.com/23172444/113061286-1657ef80-91b2-11eb-8ca9-102c1f004348.png)
![image](https://user-images.githubusercontent.com/23172444/113061309-1fe15780-91b2-11eb-8241-80fb21fa7030.png)

It did work with 7.5 as well as 7.11 before the addition of the two new fields in the JSON. Before I create a new metadata entry, I have 31 entries.

**Comment by mhogeweg** [comment]
And did you 'add the new fields in JSON' through the geoportal or through this elastic client?
