### ISSUE TITLE
French translation / i18n support

### ISSUE THREAD

**Issue by xlhomme** [Esri/geoportal-server-catalog#36]
Hi 
For translating the main app in french, I had to add a resources.js file in the app/nls/fr directory and fixe the app/nls/resources .js file  in order to load french file.
(like it's done in the viewer repository) 

The application is loading well the french translation, but don't display the french / latin character like   "é" .

What do I miss in order to succed the translation ?
 
I Use GeoPortal-Server 2.0.1
 
![2016-12-02 15-31-25](https://cloud.githubusercontent.com/assets/3986660/20837495/94948ac0-b8a4-11e6-9f15-8be3d0a02f31.png)

**Comment by xlhomme** [comment]
Forgot to precise that I add to remove 
/* locale: "en", */`
in the index.html

**Comment by zguo** [comment]
you might check if resources.js is saved to a proper encoding. we just added a documentation about localization, https://github.com/Esri/geoportal-server-catalog/wiki/Localization.
