### ISSUE TITLE
Deploying Geoportal Server 2.6.4

### ISSUE THREAD

**Issue by mgracer** [Esri/geoportal-server-catalog#369]
In the Installation Instructions, under the "Deploy Geoportal Server" section, it says to "Deploy geoportal.war to Tomcat (e.g. by copying geoportal.war file to the webapps folder)."  But I can't find a geoportal.war file in the distribution package.  Am I missing something?

Thanks,
- Mike
-

**Comment by mhogeweg** [comment]
hi Mike, the .war is included in [geoportal-server-catalog-2.6.4.zip](https://github.com/Esri/geoportal-server-catalog/releases/download/v2.6.4/geoportal-server-catalog-2.6.4.zip)

**Comment by mgracer** [comment]
Ah great, I had just gotten the source code and not the release.  Thank you very much Marten!
