### ISSUE TITLE
Steps to Customize Search filter

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#37]
I am having issues trying to get a custom search filter working, please guide me on what I might be missing?

1.  Add ISO path to **EvaluatorFor_ISO.js**
`G.evalProps(task,item,root,"business_area_s","//gmd:CI_ResponsibleParty/gmd:ciBusinessAreaName/gco:CharacterString");`

2.  Add the string title "Business Area" to **resources.js**
`
search:  {  criteria: {
businessArea: "Business Area"},`

3.  Add a new div for business_area_s in **SearchPanel.html**
```
</div>    
    <div data-dojo-type="app/search/TermsAggregation"
        data-dojo-props="field:'business_area_s',label:'${i18n.search.criteria.businessArea}'">
</div>
```

**Comment by MapZombie** [comment]
Any help on this would be great.

**Comment by mhogeweg** [comment]
is the problem that the filter is not showing up? - make sure the div is in the right place in SearchPanel.html
or is the problem that there is no data showing? - is ciBusinessAreaName indeed in your metadata XML? got sample file to share? make sure to reindex the metadata after adding a search filter.

**Comment by MapZombie** [comment]
The problem is the data does not show up.  The filter appears but with no results under it.  How do I go about reindexing?

**Comment by mhogeweg** [comment]
In order to reindex, you can issue this HTTP GET request:
```
http://host:port/geoportal/rest/metadata/reindex?fromIndexName=metadata&toIndexName=metadata
```
Before you do, I suggest publishing a file with the additional element and then accessing the JSON link that shows up with every search result, like this example:

http://geoss.esri.com/geoportal2/rest/metadata/item/915af1f81bc549eb8aba2bf023d391a5?pretty=true

your additional index element should be listed there.

**Comment by MapZombie** [comment]
ReIndexing did the trick.  Thanks.

**Comment by MapZombie** [comment]
I am trying to add data another filter called "data_type", while this shows up fine in the harvested JSON
`data_type: "mxd - ESRI ArcGIS Map file",`

I add it to my SearchPanel.html
`      <div data-dojo-type="app/search/TermsAggregation"
        data-dojo-props="field:'data_type',label:'${i18n.search.criteria.datatype}'">
      </div>`

resources.js
`datatype: "Data Type",`

EvaluatorFor_ISO.js
`G.evalProps(task,item,root,"data_type","//gmd:resourceFormat/gmd:MD_Format/gmd:name/gco:CharacterString");`

But I get "an error occured" when opening geoportal
![image](https://cloud.githubusercontent.com/assets/17599236/22838420/51e411a4-ef82-11e6-90f5-55a6e84c8972.png)


I'm stumped as I followed the same steps I took to get Business Areas working yet I get a 400 bad request.  Any insight as to what might be happening here?

**Comment by MapZombie** [comment]
ah what is required is to set the type of dynamic template elastic mapping by using **"data_type_s"** instead of "data_type"

from elastic-mappings.json
`"dynamic_templates":[
        {
          "_s":{
            "match":"*_s",
            "mapping":{
              "type":"keyword"
            }
          }
        },
        {
          "_txt":{
            "match":"*_txt",
            "mapping":{
              "type":"text"
            }
          }
        },
        {
          "_b":{
            "match":"*_b",
            "mapping":{
              "type":"boolean"
            }
          }
        },
        {
          "_i":{
            "match":"*_i",
            "mapping":{
              "type":"integer"
            }
          }
        },
        {
          "_l":{
            "match":"*_l",
            "mapping":{
              "type":"long"
            }
          }
        },
        {
          "_f":{
            "match":"*_f",
            "mapping":{
              "type":"float"
            }
          }
        },
        {
          "_d":{
            "match":"*_d",
            "mapping":{
              "type":"double"
            }
          }
        },
        {
          "_dt":{
            "match":"*_dt",
            "mapping":{
              "type":"date"
            }
          }
        },
        {
          "_geo":{
            "match":"*_geo",
            "mapping":{
              "type":"geo_shape"
            }
          }
        },
        {
          "_pt":{
            "match":"*_pt",
            "mapping":{
              "type":"geo_point"
            }
          }
        },
        {
          "_nst":{
            "match":"*_nst",
            "mapping":{
              "type":"nested"
            }
          }
        },
        {
          "_obj":{
            "match":"*_obj",
            "mapping":{
              "type":"object"
            }
          }
        },
        {
          "_blob":{
            "match":"*_blob",
            "mapping":{
              "type":"binary",
              "store": true,
              "doc_values": false
            }
          }
        },
        {
          "_clob":{
            "match":"*_clob",
            "mapping":{
              "type":"keyword",
              "index":false,
              "store": true,
              "doc_values": false
            }`

More here: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html
