### ISSUE TITLE
Embed ISO19110 into ISO19115 (without linkage)

### ISSUE THREAD

**Issue by SoftFeta** [Esri/geoportal-server-catalog#389]
Can I embed ISO19110 into ISO19115, without linking to it using a <gmd:linkage><gmd:URL> tag?
Is ISO19115-3.2018 supported? It seems that it is not possible to upload XML from the Walloon government's Metawal.
Is an ISO19110 Editor available?

**Comment by mhogeweg** [comment]
hi, you can extend the 19115 editor to include 19110 elements. That would mean the feature catalog information would be included directly in the dataset metadata. We have not configured that in Geoportal 2.x, but [have had this in Geoportal 1.x](https://github.com/Esri/geoportal-server/tree/master/geoportal/profiles/metadata/iso/iso19110) for several years and could look at porting that over to 2.x. 

Is it possible for you to share a 19115 document with 19110 elements embedded? Would help us understand what you are looking for specifically.

**Comment by SoftFeta** [comment]
Could you elaborate on the decision to remove ISO19110 functionality in 2.x?
The Walloon Metwal uses ISO19115-3.2018 the <gfc:> namespace for ISO19110 tags.

**Comment by SoftFeta** [comment]
Any updates?

For examples, you may simply search them on GitHub.

https://github.com/ISO-TC211/schemas/blob/33d31fb3076912be1434717d21fb787db09f4842/19110/gfc/1.1/exampleInstance.xml
https://github.com/metadata101/iso19115-3/blob/357df0c2bfa966444fb1874d7215f83563f51ff4/src/main/plugin/iso19115-3/templates/geodata.xml
https://github.com/eea/geonetwork-eea/blob/5a4c2d866dff0b653a5a32208bfbd9fbef1b72ef/services/src/test/resources/org/fao/geonet/api/records/extent/metadata.iso19115-3_with_three_extent.xml
https://github.com/AlexZeller/ISO19115-3Creator/blob/6c458ab8ef716641d30a263d93d247c50c89bc86/ISO19115Creator/standards.iso.org/iso/19110/gfc/1.1/exampleInstance.xml

**Comment by SoftFeta** [comment]
![image](https://user-images.githubusercontent.com/9071916/129132845-306f667b-80d5-4930-950f-34316906aa65.png)

**Comment by SoftFeta** [comment]
![image](https://user-images.githubusercontent.com/9071916/129133467-01c3184e-6bc4-4803-8984-1cc5be1f9102.png)

**Comment by SoftFeta** [comment]
https://github.com/metadata101/iso19115-3/blob/357df0c2bfa966444fb1874d7215f83563f51ff4/src/main/plugin/iso19115-3/templates/geodata.xml is the better example.

**Comment by mhogeweg** [comment]
thanks for the samples and references. I have started configuring the ISO 19115-3 editor for Geoportal 2, but this will take some time to complete as the spec breaks with the earlier 19115/19139 definitions in more ways than just adding the namespaces.

**Comment by SoftFeta** [comment]
Thanks!

**Comment by SoftFeta** [comment]
Embedding ISO19110 into ISO19115-3.2018 is good because:
1. The Feature Catalog can be indexed by Elastic Search, which makes the entity searchable by stuff inside ISO19110; while linking to a separate ISO19110 document does not.
2. There is no need to take care where the separate document is stored.

**Comment by SoftFeta** [comment]
Thanks for the enhancement, Marten! 😉

**Comment by mhogeweg** [comment]
closing as geoportal 2.6.5 (newly released!) now includes ISO 19115-3 and embedded ISO 19110 in the available types. You can include this in an existing install by copying the type to the install:
https://github.com/Esri/geoportal-server-catalog/tree/master/metadata-editor/app/gxe/types/iso-19115-3
