### ISSUE TITLE
How configure Oracle 12C with Geoportal Server Catalog 2.6.4?

### ISSUE THREAD

**Issue by Dineshr25** [Esri/geoportal-server-catalog#390]
Dear Team,

Can you please suggest how we can connect **Geoportal Server Catalog 2.6.4** with any of bellow mentioned databases:

1. Oracle 12C
2. Microsoft SQL Server
3. PostGreSQL

Thanks in advance for continuous support.

Regards
Dinesh

**Comment by mhogeweg** [comment]
hi. connect in what sense? Geoportal Server 2.x does not use a RDBMS for any data storage. The only connection is the ability to [harvest metadata from a table in one of these databases](https://github.com/Esri/geoportal-server-harvester/wiki/Brokers#jdbc-database).

**Comment by Dineshr25** [comment]
Thanks for your response. But, I need connection to store user credentials that is username, password and roles for some external users in RDBMS and need authentication through RDBMS table. I need this in Geoportal Server Catalog 2.6.4. As of now, I have not seen any RDBMS connection other than xml file in Geoportal Server Catalog 2.6.4 in respect of users authentication.

You have mentioned about connection ability of Geoportal Server Harvester with h2 database.

Regards
Dinesh

**Comment by mhogeweg** [comment]
if you want to authenticate users against a table in an RDBMS you will have to extend the authentication mechanism. Geoportal supports three mechanisms: [simple ](https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-Simple) (the xml file), [LDAP](https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-LDAP), and [ArcGIS](https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-ArcGIS).

We use the Spring security framework. The providers for LDAP and ArcGIS can be found [here](https://github.com/Esri/geoportal-server-catalog/tree/master/geoportal/src/main/java/com/esri/geoportal/base/security) and may provide a model for creating an RDBMS provider.
