### ISSUE TITLE
Geoportal Search widget - Add to map button disable with feature layer ID

### ISSUE THREAD

**Issue by buddhi2** [Esri/geoportal-server-catalog#391]
Dear Team

I have configured Geoportal search widget with web app builder and connected to the geoportal.Geoportal allowed to add feature layer to map using Link.but when i go to the Web appbuilder it's not allowed to add using geoportal search widget.

when i update layer url without layer ID, add button will enabled.

![image](https://user-images.githubusercontent.com/49560655/129169889-cb171513-f98f-4639-ae22-d523ce95ad2f.png)

![image](https://user-images.githubusercontent.com/49560655/129171446-f04898e2-b020-439f-ab6c-2b151ef36b23.png)
same layer Add button disable with geoportal search widget

![image](https://user-images.githubusercontent.com/49560655/129171289-2fab0e36-103c-4afb-8c47-5935d41f9458.png)
only enable Add button without layer ID

kindly support to fix this.

Thanks
Buddhi

**Comment by mhogeweg** [comment]
hi, the search widget functions as designed in that it allows selecting a map _service_ to be added to the map, not individual map _layers_. Similarly, if you select 'Add to Map' on the search result item, the map service is added to the map viewer, not the individual layer.

once you add a map service to the map, you can use the layer list widget to turn on/off individual layers.
