### ISSUE TITLE
How to purge Index?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#41]
How would one go and delete either portions of the index or all entries?  I am looking to reharvest my geoportal index.  Do I do this directly with elastic search?  Or is there a simple way through geoportal?

**Comment by mhogeweg** [comment]
to wipe the index you'd run this command line (using curl) against your elasticsearch:

```
curl -XDELETE http://localhost:9200/<indexname>
```

Be warned: it is gone!

**Comment by MapZombie** [comment]
Thanks.  Just to be sure this does not affect the originally harvested XMLs correct?  Just the index record within Geoportal?
