### ISSUE TITLE
An error occured - elasticsearch

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#42]
After deleting the index.  I tried to reharvest a folder.  Harvester says the files succeeded but when I try opening Geoportal I get the dreaded "an error occured"

I trace the error to:
`{"error":{"root_cause":[{"type":"search_parse_exception","reason":"No mapping found for [title.sort] in order to sort on"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"metadata","node":"RKTEL3vvS7O5Uyvz2t2PJg","reason":{"type":"search_parse_exception","reason":"No mapping found for [title.sort] in order to sort on"}}]},"status":400}`

Was I supposed to change anything after deleting the old index?  I restarted elasticsearch and apache to no avail.

**Comment by MapZombie** [comment]
`Failed to load resource: http://localhost:8088/geoportal_new/elastic/metadata/item/_search?from=0&size=10&sort=title.sort%3Aasc the server  responded with a status of 400 (Bad Request)`

I've checked the app-context.xml file settings were unchanged;
`<beans:bean id="geoportalContext" class="com.esri.geoportal.context.GeoportalContext">
		<beans:property name="elasticContext" ref="elasticContext" />
	</beans:bean>

	<beans:bean id="elasticContext" class="com.esri.geoportal.lib.elastic.ElasticContext">
		<beans:property name="clusterName" value="${es_cluster:elasticsearch}" />
		<beans:property name="indexName" value="metadata" />
		<beans:property name="indexNameIsAlias" value="true" />
		<beans:property name="autoCreateIndex" value="true" />
		<beans:property name="allowFileId" value="false" />
		<beans:property name="mappingsFile" value="config/elastic-mappings.json" />
		<beans:property name="nodes">
			
			<beans:list>
				<beans:value>${es_node:localhost}</beans:value>
			</beans:list>
		</beans:property>
	</beans:bean>`



From geoportal.log
`2017-01-13 12:14:05,886 ERROR [com.esri.geoportal.context.AppResponse] - Exception
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]`

**Comment by valentinedwv** [comment]
What happens with:
http://{host}:9200/metadata_v1/_settings

and if your running 2.5, then you need to be running ES 5.x

**Comment by MapZombie** [comment]
I am now running 2.5 with ES 5.1.2
I have an index named "metadata" as well I've added "metadata_v1"

When I open the settings page I get:
`{"metadata_v1":{"settings":{"index":{"creation_date":"1484337373940","number_of_shards":"5","number_of_replicas":"1","uuid":"yFJGLpxSRR2lqKS0Gohbpg","version":{"created":"5010299"},"provided_name":"metadata_v1"}}}}`

and

`{"metadata":{"settings":{"index":{"creation_date":"1484334146378","number_of_shards":"5","number_of_replicas":"1","uuid":"fi75bYDVQ7ebz8BkCeXdBA","version":{"created":"5010299"},"provided_name":"metadata"}}}}`

**Comment by MapZombie** [comment]
Spent all morning trying to figure out what is happening.  Here's a recap:

- Deleted my metadata index yesterday
- Recreated index "metadata" and harvested a few xmls
- Went back into Geoportal and no search results would load

- Installed an instance of Geoportal 2.5 with ElasticSearch 5 
- Created index called "metadata" and harvested some files
- I get basically the exact same error as the previous version 

- Nothing with the app-context or app-security xmls was changed so I am not sure what is happening here.  Any insight would be great, all I was trying to do was purge my index and start fresh :(

**Comment by MapZombie** [comment]
`[2017-01-13T14:21:36,301][DEBUG][o.e.a.s.TransportSearchAction] [PQadvDD] [metadata][1], node[PQadvDDnTRGyTBk5EHPgQg], [P], s[STARTED], a[id=49Dx0SHxS7aWq9rLDuarKA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[metadata], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[item], routing='null', preference='null', requestCache=null, scroll=null, source={
  "from" : 0,
  "size" : 10,
  "sort" : [
    {
      "title.sort" : {
        "order" : "asc"
      }
    }
  ],
  "ext" : { }
}}] lastShard [true]`

**Comment by MapZombie** [comment]
Is there a way to change the index that Geoportal uses to [metadata] to match where the harvester indexes?

**Comment by MapZombie** [comment]
I reverted to a previous release of harvester that was working and it pushed fine to metadata_v1.
