### ISSUE TITLE
Configure Geoportal Server to use Portal for ArcGIS authentication

### ISSUE THREAD

**Issue by ken-jpg** [Esri/geoportal-server-catalog#424]
Following the guidelines from https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-ArcGIS. I still have trouble to implement it correctly.

The app-registration on the Portal-side works without any problems and Portal's login-interface is propagated through. However, when I enter valid credentials, in the Geoportal Server-GUI there still is the "Sign In"-hyperlink to the top-right and looking at the request, I get the following error:
![image](https://user-images.githubusercontent.com/91579998/135191754-1069478b-8be5-4dbe-9702-bec00e37ec49.png)

Please kindly advise. Thanks.

**Comment by davidmccorkindale** [comment]
@ken-jpg did you ever get this resolved? We have the same issue.

**Comment by mhogeweg** [comment]
closing as duplicate of #335
