### ISSUE TITLE
How to handle searching in ISO with RoleCodes

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#43]
ISO standards include tags that are structured identically except they have coded values.  For example "originator" and "user" values are both structured as:
```
<gmd:contact>
    <gmd:CI_ResponsibleParty>
        <gmd:individualName>
            <gco:CharacterString>Originators Name Here</gco:CharacterString>
        </gmd:individualName>
        <gmd:role>
            <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="originator" codeSpace="ISOTC211/19115">originator</gmd:CI_RoleCode>
        </gmd:role>
    </gmd:CI_ResponsibleParty>
</gmd:contact>
```

```
<gmd:contact>
    <gmd:CI_ResponsibleParty>
        <gmd:individualName>
            <gco:CharacterString>User's Name Here</gco:CharacterString>
        <gmd:role>
            <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="user" codeSpace="ISOTC211/19115">user</gmd:CI_RoleCode>
        </gmd:role>
    </gmd:CI_ResponsibleParty>
</gmd:contact>
```
What is the best way to decipher this in Geoportal?  Can we use a dict / key system?
  In the EvaluatorFor_ISO.js file we have the entry:
    `G.evalProps(task,item,root,"contact_people_s","//gmd:CI_ResponsibleParty/gmd:individualName/gco:CharacterString");`

And if I add the following the search panel, it only displays the first entry of "gmd:contact"
`                <div data-dojo-type="app/search/TermsAggregation"
        data-dojo-props="field:'contact_people_s',label:'${i18n.search.criteria.contactPeople}'">
      </div>`

**Comment by mhogeweg** [comment]
the trick is in the xpath expression. for example to get all originators:

```
//gmd:CI_ResponsibleParty[gmd:role/gmd:CI_RoleCode/@codeListValue='originator']/gmd:organisationName/gco:CharacterString
```

to get publishers or to get individual names you would combine xpath1 | xpath2 etc.

**Comment by MapZombie** [comment]
Great that worked however the search display is messed up as it seems to be separating by each space.  
JSON:
![image](https://cloud.githubusercontent.com/assets/17599236/21998752/f46c523a-dbf3-11e6-9407-413197c46370.png)

Search Filter:
![image](https://cloud.githubusercontent.com/assets/17599236/21998736/e07ff506-dbf3-11e6-82a5-ce4b19831ae7.png)

**Comment by MapZombie** [comment]
Any clue what is causing this?

**Comment by MapZombie** [comment]
This seems to have been resolved when using proper dynamic template of "_s" 

`          <div data-dojo-type="app/search/TermsAggregation"
                 data-dojo-props="field:'created_by_s',label:'${i18n.search.criteria.createdBy}'">
            </div>`
and

`    G.evalProps(task,item,root,"created_by_s","//gmd:contact/gmd:CI_ResponsibleParty[gmd:role/gmd:CI_RoleCode/@codeListValue='originator']/gmd:individualName/gco:CharacterString");`
