### ISSUE TITLE
Geoportal Server Catalog 2.6.4 in disconnected environment - ArcGIS JS API, local ArcGIS server, localhost, xsd

### ISSUE THREAD

**Issue by tknezevic1** [Esri/geoportal-server-catalog#441]
Hi,
I was following instructions for configuring Geoportal Server Catalog 2.6.4 in disconnected environment and files app-config.js (map service), PreviewUtil.js (geometry service), and config.json (portalUrl, geometry service and itemid) have references to local ArcGIS server. Was skipping these configurations until I'm sure they are required. 
Do I need to have local ArcGIS Server and Portal for ArcGIS instances installed to be able to have a successful Geoportal Server Catalog installation in disconnected environment? Would these instances require ArcGIS license cost?

Was struggling with Spring framework xsd references, Spring Security xsd was not in the instructions. 
Do I need to download xsd files that are referenced in import and include elements and update the references to their local paths? 

Have a question about Tomcat configuration as it seems that the installation is successful when trying localhost:8080. 
Do I need to change server.xml config file and hosts file or default install is enough?

As you can see I don't have experience with xml and web server, nor GIS, but still trying to make this installation work. So far it's showing 404 status for localhost:8080/geoportal and it's frustrating, feels like I'm finding missing files constantly and not sure when it will work. Don't know what I'm missing to make it work. Didn't change configuration for harvester yet, wanted first to fix geoportal catalog. It would be nice if the package has all the dependencies and simplified configuration with maybe environment variables or a config file where you change on one spot versus so many file changes. But that's an expensive dream I guess :)
Appreciate your guidance!

Thanks,
Tatjana

**Comment by mhogeweg** [comment]
hi, do you also have a local ArcGIS JS API? this is needed for the map element to function. Can you see messages in the geoportal.log log file? by default this will be in the Tomcat/logs folder.

What version of Tomcat/Java/Elastic are you using?

**Comment by tknezevic1** [comment]
Thank you for your help Marten.
I've installed: 

1. arcgis_js_v325_api and sdk
2. apache-tomcat-9.0.29
3. OpenJDK11U-jdk_x64_windows_hotspot_11.0.12_7
4. elasticsearch-7.5.0-no-jdk-windows-x86_64.

Tomcat and Elasticsearch are installed as windows service, default installation.
The application server is windows server 2019 datacenter on Azure in disconnected environment (no http/https).
Based on geoportal.log file seems like it's stuck on beans from spring security xsd schema. I was referencing local xsd schema files using "file:///C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/spring-framework/schema/beans/spring-beans-4.3.xsd" instead of http. Was trying with "../../" relative path and changed to full path to make sure I don't make a mistake. Probably it's still referencing somewhere with http spring security xsd, but not sure where. I was suspecting that import and include are loading xsd from http, but don't know if that's true. Hope it's okay to attach geoportal.log file, at the end you should see the latest messages.

Thanks,
Tatjana

[geoportal.log](https://github.com/Esri/geoportal-server-catalog/files/8020016/geoportal.log)

**Comment by mhogeweg** [comment]
You'll need to host those XSD behind http(s). Since you already have then in webapps, you can turn that folder into a web application quite easily. Also make sure you download all the includes in the xsd. For example web-app_3_1.xsd includes web-common_3_1.xsd, which includes  javaee_7.xsd andjsp_2_3.xsd, etc

**Comment by mhogeweg** [comment]
these are just from Geoportal's web.xml file. the app-security.xml file has 2 xsd it references, etc

**Comment by tknezevic1** [comment]
Thanks Marten for helping out!
I've started downloading and editing xml and xsd files. It takes time to manually do it. Will let you know how it goes.

Tatjana

**Comment by tknezevic1** [comment]
Hi Marten, 

I've changed xml and xsd files, and it still fails.
Seems like it can't pass in **app-context.xml** spring-context.xsd part.
First I've changed to
<beans:beans 
	xmlns:beans="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans **file:///C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/spring-framework/schema/beans/spring-beans-4.3.xsd**
    http://www.springframework.org/schema/context **file:///C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/spring-framework/schema/context/spring-context-4.3.xsd**"> 

	<context:property-placeholder/>

and then with classpath for spring-beans.xsd which was checking the jar file and found this spring-beans.xsd, this one doesn't load any other xsd and it was passing through.
What didn't pass is when I started messing with spring-context.xsd part, thinking that namespace declaration before xsd is the issue. Don't know if namespace and targetnamespace need to be changed as well and how. I am concerned this is more complicated to fix as it's used in each file and their dependencies, referencing other files. I couldn't find any article I can understand how to declare targetnamespace and namespace for these local xsds, and their dependencies. Some xsds have includes, some xsds have imports or both, and that can cause the conflict with targetnamespace for local xsds if it's out of scope for other files referenced.
Hope you can help with this issue and what would be the best way to make disconnected environment work if that is possible.

<beans:beans 
	xmlns:beans="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans **classpath:/org/springframework/beans/factory/xml/spring-beans.xsd**
    **file:///C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/spring-framework/schema/context/spring-context-4.3.xsd** file:///C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/spring-framework/schema/context/spring-context-4.3.xsd"> 

	<context:property-placeholder/>

Here's the geoportal.log error for the latest attempt:

2022-03-02 15:14:58,216 INFO [org.springframework.web.context.ContextLoader] - Root WebApplicationContext: initialization started
2022-03-02 15:14:58,513 ERROR [org.springframework.web.context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 9 in XML document from class path resource [config/app-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 33; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'context:property-placeholder'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:405) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

Thank you.
Tatjana

**Comment by mhogeweg** [comment]
@lindhor has expanded on the [documentation for installing Geoportal Server in a disconnected environment](https://github.com/Esri/geoportal-server-catalog/wiki/Configure-geoportal-for-a-disconnected-environment). Please check this out.
