### ISSUE TITLE
Procedures for building own war?

### ISSUE THREAD

**Issue by tom62291** [Esri/geoportal-server-catalog#443]
Hi there are any procedures for building own war?

As I tried build the own war by using eclipse, there are some files missing in the war when compared to the official relased war.
For example, the gs folder in GeoportalSearch widget is missing
![image](https://user-images.githubusercontent.com/8196925/154407243-99f86b48-0ec4-42d0-bd9d-b4d4a48a0653.png)

**Comment by mhogeweg** [comment]
Geoportal Server is setup to be built using [Apache maven](https://maven.apache.org/), for example: `mvn clean install` will first clean the target folders and then compile the java code and collect all in a geoportal.war file.

**Comment by tom62291** [comment]
OK, it works, thank you.
