### ISSUE TITLE
CI_OnlineResource with gmd:protocol

### ISSUE THREAD

**Issue by tom62291** [Esri/geoportal-server-catalog#448]
Hi hello,
How can the metadata editor supporting embedding protocol information for the online resource in ISO 19115 metadata schema   as below?

[http://www.datypic.com/sc/niem21/e-gmd_CI_OnlineResource.html](url)

**Comment by tom62291** [comment]
hello, any exact instruction how can I do that?
Modifiy the source code of the metadata-editor?

I am not sure how to add extract protocol in the metadata-editor...
![image](https://user-images.githubusercontent.com/8196925/161886509-48cf0360-0839-47ea-8fd9-641c51c7d00c.png)

**Comment by mhogeweg** [comment]
PS: we have expanded on the documentation of the metadata editor:
https://github.com/Esri/geoportal-server-catalog/wiki/Customize-Metadata-Profiles
