### ISSUE TITLE
Supporting a distribution format with format distributor in ISO19115 via metadata editor

### ISSUE THREAD

**Issue by tom62291** [Esri/geoportal-server-catalog#449]
Hello,

How can the metadata editor can support to create distribution format with format disributor in ISO19115 metadata as below?

[https://github.com/roomthily/ISO-19115-Distribution-Structures](url) <-Example 5

**Comment by mhogeweg** [comment]
hi @tom62291, in the inspire2 type that is included in the default configuration of geoportal, you will now find an expanded distribution section where you can include the distribution format and the format distributor per your example:
https://github.com/Esri/geoportal-server-catalog/tree/master/geoportal/src/main/webapp/app/gxe/types/inspire2

this was achieved by adding some elements to the editor. The documentation for customizing or creating metadata types (profiles or versions of standards) is being expanded on in the [wiki](https://github.com/Esri/geoportal-server-catalog/wiki/Customize-Metadata-Profiles).
