### ISSUE TITLE
Adding a New Tab and Custom Link to a Search Result

### ISSUE THREAD

**Issue by vladymir30** [Esri/geoportal-server-catalog#45]
Hello everyone!,

I'm just wondering how to add a customized "Details"  link for the search intem result in this new version (Geoportal 2.5.0), in this case I will create my own form consuming the metadata information and presenting info in user friendly way (not XML, JSON or integrated HTML), the same to create my custom gallery tab.

Best Regards,

Vladymir

**Comment by MapZombie** [comment]
What do you mean by Details link?  Please be more specific.  And what metadata standard are you using?

**Comment by vladymir30** [comment]
I mean display all metadata information like the HTML and XML options, but in my custom presentation format,  I tried using the limited json object (json link) but doesn´t work for me, because I need the complete info, so think I will create my own using all information in the xm link. The metadata Std is ISO-19115

**Comment by smrgeoinfo** [comment]
There's an ISO 19115 to html xslt that I substitute for the out of the box one that comes with geoportal. Its been prettied up some, might be worth a look
https://github.com/iedadata/geoportal-server-catalog/tree/master/geoportal/src/main/resources/metadata/details/iso-details  named ISO19139ToHTML.xsl, and imports some other style sheets from the imports subdirectory in the same repo.
