### ISSUE TITLE
sandbox url is dead

### ISSUE THREAD

**Issue by kjetpett** [Esri/geoportal-server-catalog#455]
The sandbox url (http://gptogc.esri.com/geoportal2) seems to be dead.

**Comment by mhogeweg** [comment]
hi, we have moved to a new domain for the demo sites: https://gpt.geocloud.com/geoportal2. Also updated the repo landing page.

**Comment by kjetpett** [comment]
Wow! That was quick. Looking forward to evaluating this in our environment. Thank you.
