### ISSUE TITLE
Geoportal Server Catalog Map Window under filter not showing or working

### ISSUE THREAD

**Issue by vishnuvardhank7** [Esri/geoportal-server-catalog#459]
![image](https://user-images.githubusercontent.com/41356490/169282868-d2b4df18-d965-40eb-a0e0-0ee2aced1e03.png)

**Comment by vishnuvardhank7** [comment]
I'm using 2.5.2 Geoportal code with some UI modification

**Comment by mhogeweg** [comment]
couple questions:
- are you seeing errors in the browser console?
- it looks like the map itself is not showing. What do you use as the map service for the spatial search facet?

**Comment by vishnuvardhank7** [comment]
1. I'm seeing CORS origin error
2. I didn't modify anything in the spatial search facet.

FYR
![image](https://user-images.githubusercontent.com/41356490/169856813-faa00c45-bde7-44f4-bc80-c060315e7152.png)

**Comment by vishnuvardhank7** [comment]
Also
![image](https://user-images.githubusercontent.com/41356490/169858735-ef7adf8c-6907-4acb-a9cb-5e7667cd0c3c.png)

**Comment by mhogeweg** [comment]
hmmm. can you test this?

in /geoportal/app/context/app-config.js look for the searchMap element and then within that change what is there to:

    _basemap: "streets",
    basemapUrl: "https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer",

this changes the reference to the basemap used in the map facet from a named basemap to an actual map service link. You will also see the link referencing https, not http.

**Comment by vishnuvardhank7** [comment]
After modifying the map facet in /geoportal/app/context/app-config.js the map window is working now.

Thank you Marten.
