### ISSUE TITLE
Single sign-on Geoportal by Single sign-on Portal for ArcGIS

### ISSUE THREAD

**Issue by tom62291** [Esri/geoportal-server-catalog#461]
May I know if my geoportal is using Portal for ArcGIS for user authentication, if my Portal for ArcGIS is connecting with AD and enabled the single signon, can my geoportal also signon?

**Comment by davidmccorkindale** [comment]
hi @tom62291, 

Yes any authentication supported by your portal can be used by the geoportal.  For example we have arcgis, SAML and OpenID Connect configured and users can use the most appropriate one.
