### ISSUE TITLE
How to set default map extent/zoom? 

### ISSUE THREAD

**Issue by karbah-geodata** [Esri/geoportal-server-catalog#464]
Currently, the default when opening geoportal is that the map in the left search pane is centered and zoomed over North America. Where would I look to change the default map extent/bbox on startup, ie which js files and/or functions control this? And the same for the larger map tab (when clicking "Map" on the top menu)? Thanks!

**Comment by mhogeweg** [comment]
hi, this wiki page has some information on how to configure a different search map, different initial extent, and location search capability within the map: 
https://github.com/Esri/geoportal-server-catalog/wiki/Customize-search-panel#update-the-map-search-facet
