### ISSUE TITLE
Linking to particular metadata entries or search results?

### ISSUE THREAD

**Issue by karbah-geodata** [Esri/geoportal-server-catalog#471]
Hi, all interactions within geoportal seem to be dynamic within the same page, ie the url doesn't change. This poses a problem if I want to share a link to a particular metadata entry from an external site, so when the user clicks the link they arrive at the geoportal site with the popup for that item's metadata entry. Other types of links would also be useful, e.g. a link that takes the user to the search page with the results for a particular query, or a link that shows the map page with a set of items added/visualized. 

Are there any mechanisms I'm not aware of that allow linking to particular views of the geoportal website, maybe via GET or POST parameters? I know there's the rest api, but that's only useful for access to the data, not for access to the website. 

Thanks!

**Comment by mhogeweg** [comment]
there are a couple things possible, best illustrated with some examples.:
- every record is accessible directly in an HTML rendering. Fairly basic look-and-feel but that can be modified. see: https://gpt.geocloud.com/geoportal2/rest/metadata/item/09f6b15d19e2482aa94b9b33986bc452/html
- results of a specific search are accessible via the 'WEB' link at the bottom of the page. This link includes the search query based on the selected criteria. see: https://gpt.geocloud.com/geoportal2/?from=1&size=10&sort=sys_modified_dt%3Adesc&esdsl=%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22query_string%22%3A%7B%22analyze_wildcard%22%3Atrue%2C%22query%22%3A%22%5C%22Tidevannssone%20versjon%201%20ortofoto%20-%20INSPIRE%5C%22%22%7D%7D%5D%7D%7D%7D#searchPanel

the HTML page is rendered based on an XSLT applied to the metadata. These XSLT can be found in `/geoportal/WEB-INF/classes/metadata/details`.
