### ISSUE TITLE
Item identifier vs fileIdentifier

### ISSUE THREAD

**Issue by kep1n** [Esri/geoportal-server-catalog#473]
Hi there,

This is more of a question than an issue but we are experiencing some troubles regarding the internal identifier used by Geoportal when harvesting an existing CSW in old Geonetwork to deploy a new Geoportal. Everything seems to work flawlessly but the identifier set by Geoportal is alike to a Portal for ArcGIS element id and does not match with the harvested element fileIdentifier. From what we can see from other CSW services the identifier and fileIdentifier tend to match to ease the GetRecordById request.

In this case we must perform a GetRecords request prior to a GetRecordById. ¿Is there a way to force Geoportal use the fileIdentifier as the identifier in the harvesting/uploading/creating process?

Thanks,

![capture](https://user-images.githubusercontent.com/19705091/194095490-cb7183fb-2d51-411c-9b32-9fdc3a662b76.png)

**Comment by mhogeweg** [comment]
hi. yes, there is a way to change what field in the metadata Geoportal Server uses for the identifier. I suggest the topic of Evaluators on the wiki as a start: https://github.com/Esri/geoportal-server-catalog/wiki/Evaluators. Evaluators pick elements from the configured metadata types and store them in common fields in the elastic index. One of those elements is the identifier. 

Key is that this identifier is unique and persistent. This is a bit of a challenge with ISO metadata with the fileIdentifier is optional and oftentimes not used. While an identifier may be some URI/URL, we have seen cases of recurring values, meaning the fileIdentifier is also not unique.

if this situation does not apply to your case, you could change the evaluator for your metadata and pull the fileIdentifier to use as the main identifier for a record

**Comment by mhogeweg** [comment]
ah, wait, that _id cannot be modified. That is an id assigned by elasticsearch. What you can change is all in the _source element. There you will find the fileid field that for ISO metadata is based on the file identifier. See this example:
https://gpt.geocloud.com/geoportal2/rest/metadata/item/d1b6fed3e06d4960af263970ad7b0bd6?pretty=true

**Comment by kep1n** [comment]
Hi again, 

Finally we manage to set the `fileIdentifier` as internal `_id` but just within the geoportal environment modifying `MetadataEditor.js` and `UploadMetadata.js` which control the `Create Metadata` and `Upload Metadata` options respectively. Everything seems to work properly, letting us delete individual items, searching for them, etc.

Now, could you please tell us where should be looking at to apply similar approach on the _Harvester_ side? As we can see from using DevTools it requests `process`, `triggers` and `execute` links through the `rest` but cannot get further before looking at the source code.

Thanks

**Comment by mhogeweg** [comment]
the allowFileId use would indeed achieve your goal. Sorry, I totally missed this setting described in: https://github.com/Esri/geoportal-server-catalog/wiki/Elasticsearch-configuration

"If set to "true", you can use the metadata file id as Elasticsearch id, the id will not be used if the id contains forward slash (e.g. in urls)."

**Comment by kep1n** [comment]
Already made the change on the source code and it works flawlessly. Thank you very much.
