### ISSUE TITLE
Pass Parameters/filters on URL

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#48]
Is there a way to pass a set of filters/parameters?

Basically, allow a user to pass a set of results by URL

**Comment by MapZombie** [comment]
Did this get implemented?

**Comment by pandzel** [comment]
#278 adds this functionality.

**Comment by zguo** [comment]
From the search result, click on link "web"  (lower right of the result page) will show the url with the parameters.
