### ISSUE TITLE
Help with Geoportal and Elasticsearch Cluster

### ISSUE THREAD

**Issue by maximilianomarin01** [Esri/geoportal-server-catalog#480]
Hi all. 
I am trying to connect Geoportal version 2.6.5 with an Elasticsearch 2 node cluster. I am using 3 vm, all them connected to a virtual swithch full connectivity. 
I configured app-context.xml with cluster name and nodes.
But, when I load the portal I get this message:

2022-11-23 11:09:21,866 DEBUG [com.esri.geoportal.lib.elastic.ElasticContextHttp] - Checking index: metadata
2022-11-23 11:09:21,920 ERROR [com.esri.geoportal.lib.elastic.ElasticContextHttp] - Error executing ensureIndex()
java.net.SocketException: Unexpected end of file from server

My cluster has a username and password. How can set those credentitals in Geoportal?

Thank you  in advance,

**Comment by mhogeweg** [comment]
on the configuration page for elasticsearch, you will see information on working with a secured elastic index: https://github.com/Esri/geoportal-server-catalog/wiki/Elasticsearch-configuration

**Comment by maximilianomarin01** [comment]
Thank you.!!
