### ISSUE TITLE
Encoding LDAP Server manager-password

### ISSUE THREAD

**Issue by vishnuvardhank7** [Esri/geoportal-server-catalog#484]
Is there any way to hashing the password in authentication-ldap.xml?
`<security:ldap-server
id="ldapServer"
url="ldap://ldapservername:10389"
manager-dn="uid=admin, ou=system" 
manager-password="Qwerty@123" />`

My password is visible here.

**Comment by mhogeweg** [comment]
Geoportal Server uses the spring framework. Please see https://docs.spring.io/spring-security/reference/features/authentication/password-storage.html#authentication-password-storage for information on the options for storing an encrypted password.
