### ISSUE TITLE
Ontology Service

### ISSUE THREAD

**Issue by davidmccorkindale** [Esri/geoportal-server-catalog#487]
Is there an ontology service for the new geoportal the way the v1 geoportal had one?

**Comment by mhogeweg** [comment]
hi. no, we do not have this built into the new geoportal. However, the Ontology Service was always a separate web application. The source code is available here: https://github.com/Esri/geoportal-server/tree/master/components/server/OntologyService/trunk.

Be aware, that this is some 9 years old and may need some TLC to run on current Java/Tomcat versions.
