### ISSUE TITLE
Facet/field search on url

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#49]
I'd say implement:
Filter-FES-KVP-Advanced/Filter-CQL

But honestly, can we think simpler approach.
facet=apiso_ServiceType_s:WMS

**Comment by valentinedwv** [comment]
Note for those wishing simple query. 
Already in the API, simple filter supported (thanks)
Example: http://localhost:8080/geoportal/index.html?filter=oceans

Optional Query Parameters:
  filter - a filter to be applied to all searches

**Comment by valentinedwv** [comment]
#239 includes ability to search for fileid

**Comment by mhogeweg** [comment]
closing as this is possible via OGC Records and Geoportal REST api.
