### ISSUE TITLE
Modifying item cards and json mappings

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#50]
Trying to determine the best way to add some links to an item card, and create a custom field in the json mappings (where these links might be stored).
Basically, how to handle customization in a way that would have the least impact on keeping code in sync

**Comment by valentinedwv** [comment]
Observing that  search/ItemCard is getting a bit long, and unwieldy. 
Split up into it's own component, so that features can be more easily added, and maintained idependently.

**Comment by zguo** [comment]
consider add this when doing interface enhancements

**Comment by mhogeweg** [comment]
no action seen since 2020
