### ISSUE TITLE
update bootstrap

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-catalog#525]
update bootstrap to 5.3.2. a quick test shows several breaking changes in the UI:

- The drop-down with links for the 1 item that’s there does not work. There is a link element, but clicking the drop-down doesn’t do anything and throws no console errors.
- Sort drop-down doesn’t work
- Edit facet details doesn’t work
- Clearing filters doesn’t work

**Comment by as0050629** [comment]
Fixed in branch https://github.com/Esri/geoportal-server-catalog/tree/2.7.1.2_bootstrapUpgrade

**Comment by mhogeweg** [comment]
closed. See release 2.7.1.3
