### ISSUE TITLE
Implement STAC transaction API

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-catalog#528]
STAC has an extension that provides add/update/delete functionality to the STAC API. This ticket is to include support for the management API in Geoportal Server.

**Comment by as0050629** [comment]
@mhogeweg  STAC feature Add and update is complete.  Should Delete also be done?

**Comment by mhogeweg** [comment]
@as0050629 yes please, both for items and collections.

**Comment by as0050629** [comment]
Delete Item and collection implemented via #549
