### ISSUE TITLE
About tab

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#53]
Basic about tab, with version number. (for harvester, too)

**Comment by KathleenPate** [comment]
You could add your own _About_ page and then link to it in the NavBar.
Open main>webapp>app>main>templates>App.html
 modify the Navbar (line 4)

```
	  <ul class="nav navbar-nav">
	    <li class="nav-item active">
	      <a class="nav-link" href="#searchPanel" data-toggle="tab">${i18n.nav.search} <span class="sr-only">(current)</span></a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="#mapPanel" data-toggle="tab">${i18n.nav.map}</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="#aboutPanel" data-toggle="tab">${i18n.nav.about} </a>
	    </li>
```

You will probably have to define the About page in the App.js for this to work.  
e.g. `define(["dojo/_base/declare",
...
        "app/main/SearchPanel",
        "app/main/MapPanel",
        "app/main/AboutPanel",
        "app/content/MetadataEditor",
        "app/content/UploadMetadata"], `

I've JUST loaded the software so I'm beginning to orient myself to the layout and organization. I have not built a page yet.

**Comment by KathleenPate** [comment]
I have made Pull Request #73 which creates an About Page. The steps include:

- Create a new page App/main/AboutPanel.js & template App/main/templates/AboutPanel.html
- Add new About page to app/nls/Resources.js file
- Add new page to app/main/app.js
- In app.html add new page to the Nav `<ul>` tags and define link content
