### ISSUE TITLE
'supportsApprovalStatus' not being respected after upgrade to v2.7

### ISSUE THREAD

**Issue by rhodges** [Esri/geoportal-server-catalog#542]
**Describe the bug**
When deploying GeoPortal Server Catalog v2.7.0 and above, all records are presented by default, regardless of approval status.

**To Reproduce**
1. Populate your records with a mix of 'approved', 'posted', etc....
2. clone repository and use 'master' branch or any tag starting with 'v2.7.0'
3. Edit geoportal/src/main/resources/config/app-context.xml
   * `<beans:property name="supportsApprovalStatus" value="true" />`
   * `<beans:property name="defaultApprovalStatus" value="posted" />`
4. use `mvn clean install` to build your .war
5. Deploy your new geoportal.war with tomcat
6. Open https://your.site.com/geoportal/

**Expected behavior**
Any user not logged in should only see records set to 'approved'.

Example running v2.6.5: [https://portal-staging.westcoastoceans.org/geoportal/](https://portal-staging.westcoastoceans.org/geoportal/)
-- Note that there are 15,331 total items that show if logged in, but only those 705 are 'approved' or 'reviewed'

**Screenshots**
![image](https://github.com/Esri/geoportal-server-catalog/assets/526505/95af4e61-6510-48bc-bd50-b25189691152)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser: FireFox
 - Version 127.0.2

**Additional context**
GeoPortal Server Stack:
- OS: Ubuntu 22.04 LTS
- Tomcat: 9.0.87
- JVM: 11.0.23+9-post-Ubuntu-1ubuntu122.04.1

**Comment by rhodges** [comment]
If additional configuration is now required, please update the documentation. I was reviewing this one: [https://github.com/Esri/geoportal-server-catalog/wiki/Other-Configurations-For-Geoportal#enable-metadata-approval-status](https://github.com/Esri/geoportal-server-catalog/wiki/Other-Configurations-For-Geoportal#enable-metadata-approval-status)

**Comment by as0050629** [comment]
@rhodges I was able to reproduce this and has been resolved in branch. Pull request https://github.com/Esri/geoportal-server-catalog/pull/545. It will soon be merged to master

**Comment by mhogeweg** [comment]
hi @rhodges, this fix is now merged into master and will be in the upcoming 2.7.2 release. If you don't want to wait for that, please get the master branch and build the webapp from there.

**Comment by rhodges** [comment]
Thanks @as0050629 and @mhogeweg ! I'll check it out next week!

**Comment by rhodges** [comment]
Confirmed: this is working now! Thanks!

**Comment by mhogeweg** [comment]
thanks for confirming. great catch!
