### ISSUE TITLE
Catalog results don't load after commit 406adc57c51bbeab35de0a2fa4c478f59c4b73ed

### ISSUE THREAD

**Issue by rhodges** [Esri/geoportal-server-catalog#547]
**Describe the bug**
Loading `/geoportal/` (or `/geoportal/#searchPanel`) in a browser, instead of results, I get the message "An error occurred."
The query to elasticsearch `/elastic/metadata/_search?from=0&size=10` 

**To Reproduce**
1. Clone master and check out the commit 24e47e596e37bad96c1b79e09194185721bbe34a (when the commit was merged in)
2. `mvn clean install`
3. Deploy the .war file on Tomcat
4. Open your.url/geoportal/ in your browser
   * Page loads without results
   * Elasticsearch query, now missing sort in URL, but with 'sort' in the request fails (see screenshot)

Request: 
```
/elastic/metadata/_search?from=0&size=10
```

parameters: 

```
{ 
   aggregations: {...}, 
   sort:{
      title.keyword: {
         order:"asc", 
         unmapped_type:"String"
      }
   }, 
   track_total_hits: true
}
```
   * Reverting to a prior commit (not including 406adc57c51bbeab35de0a2fa4c478f59c4b73ed when the code was added) results load as expected.

**Expected behavior**
The query to load all initial results should populate the catalog page.

Working query:
Request:
```
/elastic/metadata/_search?from=0&size=10&sort=%7B%22title.keyword%22%3A%20%7B%22order%22%20%3A%20%22asc%22%20%2C%22unmapped_type%22%3A%20%22String%22%7D%7D
```

request context: 
```
{ 
   aggregations:{...}, 
   track_total_hits: true
}
```

**Screenshots**
![image](https://github.com/user-attachments/assets/ebd9bc07-36b3-4a2e-b28c-ad6592157239)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser: FireFox
 - Version 127.0.2

**Additional context**
GeoPortal Server Stack:

 *   OS: Ubuntu 22.04 LTS
 *   Tomcat: 9.0.87
 *   JVM: 11.0.23+9-post-Ubuntu-1ubuntu122.04.1

**Comment by rhodges** [comment]
@as0050629 - That seems to have fixed it! After building I see all of my records. Thanks!

**Comment by mhogeweg** [comment]
awesome! thanks for your willingness to test this fix.
