### ISSUE TITLE
Add delete collection to STAC API

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-catalog#549]
in the stac API include HTTP DELETE operation on

- http://host:port/geoportal/stac/collections/{collectionId} - deletes collection and items
- http://host:port/geoportal/stac/collections/{collectionId/items
  - parameter itemIds = comma separated list of itemIds to delete
  - if parameter itemIds = empty then deletes all items from collection
- http://host:port/geoportal/stac/collections/{collectionId}/items/{itemId} - deletes single item
-

**Comment by as0050629** [comment]
@mhogeweg Implemented in https://github.com/Esri/geoportal-server-catalog/tree/2.7.2. Please give test run and let me know if you see any issue
