### ISSUE TITLE
Flag records with duplicate fileIdentifier on harvest

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#55]
Currently, ISO metadata records with the same fileIdentifier can be harvested via different brokers without raising any notice.  A process to check if an identifier already exists during a harvest process would be good to avoid duplicating metadata.

**Comment by zguo** [comment]
There is a parameter "allowFileId" in app-context.xml , when set to true, the internal file identifier will used as the Elasticsearch id (as long as it does not contain a forward slash).
