### ISSUE TITLE
Explain the map tab better

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#56]
Currently, when I open the map tab and click on map search, the Catalogs offered are 'Caliornia Geoportal', 'Geoportal Sandbox', and 'USGIN Geoportal'. I don't see the catalog that the server application is attached to; shouldn't that be the default. Is there any documentation on what the map tab is supposed to to and how to confgure the Search to use the active catalog by default?  I see nothing in the Wiki.
thanks

**Comment by zguo** [comment]
currently the search capability in the map tab is still limited. it is a separate app built on top of web app builder and need some more capability, currently it is possible to add/remove entries by updating config.json file within the GeoportalSearch widget, we are thinking make some enhancements once developers have availability.

**Comment by smrgeoinfo** [comment]
Its not clear where the GeoportalSearch widget code that's being used resides...

**Comment by smrgeoinfo** [comment]
@zguo  any new developments recently on the map tab?  I'd like to get it working.  The catalog search looks like its based on the csw search client widget.

**Comment by zguo** [comment]
sorry we don't have much update yet since all developers are currently quite busy, the code is under /src/main/webapp/viewer/widgets/GeoportalSearch.

**Comment by zguo** [comment]
A new search widget is added in the coming release.
