### ISSUE TITLE
Configuration error in localhost in geoportal-server-catalog (error status:500)

### ISSUE THREAD

**Issue by ShameeraJayawardana** [Esri/geoportal-server-catalog#560]
Do you have a tutorial or document on how to install Geoportal on the local computer with all requirements (elastic search) properly? The installation I did was not successful. When adding metadata this error occurred.
![image](https://github.com/user-attachments/assets/b9d8a1b7-603d-4efd-a05c-c03d94738a72)

**Comment by mhogeweg** [comment]
hi, you can find documentation here in GitHub on the wiki: https://github.com/Esri/geoportal-server-catalog/wiki

various installation and configuration topics are collected on this page: https://github.com/Esri/geoportal-server-catalog/wiki#installation-and-upgrade

**Comment by as0050629** [comment]
@ShameeraJayawardana Link for elastic configuration 
https://github.com/Esri/geoportal-server-catalog/wiki/Elastic-Search-configuration
