### ISSUE TITLE
Unrecognized metadata type (ISO 19115-3) when uploading xml

### ISSUE THREAD

**Issue by hsiddique** [Esri/geoportal-server-catalog#561]
**Describe the bug**
When trying to upload a ISO 19115-3 xml file (which has been exported via ArcGIS pro), the following error message appears
**Unrecognized metadata type.**

**To Reproduce**
1. Go to https://gpt.geocloud.com/geoportal2/#searchPanel 
2. Log in as admin/admin
3. Click Admin from the menu bar
4. Select Upload Metadata
5. Select the ISO 19115-3 xml
6. Click Upload

**Expected behavior**
File Should be uploaded

**Screenshots**
![image](https://github.com/user-attachments/assets/ede9da3c-2a38-4cd0-9099-7b421411570f)

**Additional context**
Same issue on 2.7,1.3

**Comment by mhogeweg** [comment]
hi, I am troubleshooting this issue. Meanwhile, you can see ISO 19115-3 metadata in the stand-alone metadata editor: https://gpt.geocloud.com/metadata_editor/
