### ISSUE TITLE
uniqName_16: parser returned unfilled promise when trying to create a new metadata document

### ISSUE THREAD

**Issue by hsiddique** [Esri/geoportal-server-catalog#562]
**Describe the bug**
When trying to Create a ISO 19115-3 metadata document, the following error message appears
**An error occurred while loading the document.
uniqName_16: parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin. Must pre-load all supporting widgets before instantiation.**

**To Reproduce**
1. Go to https://gpt.geocloud.com/geoportal2/#searchPanel
2. Log in as admin/admin
3. Click Admin from the menu bar
4. Select Create Metadata
5. Select New Document
6. Select ISO 19115-3

**Expected behavior**
Editor for ISO 19915-3 should appear

**Screenshots**
![image](https://github.com/user-attachments/assets/563d3c04-9856-4df4-bbdc-d0a30d261c3f)

**Additional context**
Same issue on 2.7,1.3

**Comment by aliciuki** [comment]
I have exactly the same issue, exactly the same steps (except my instance is on localhost).
Any clues about what might be missing?

**Comment by hsiddique** [comment]
Just to add, i also have the same issue on localhost.

**Comment by mhogeweg** [comment]
hi. This issue has been resolved in branch [272_ISO19115_3](https://github.com/Esri/geoportal-server-catalog/tree/272_ISO19115_3). Please feel free to get the code from there and build Geoportal Server using mvn. We will be releasing a patch, but that may still take a couple weeks as we'll include a few more updates.
