### ISSUE TITLE
Add to Map

### ISSUE THREAD

**Issue by ShameeraJayawardana** [Esri/geoportal-server-catalog#577]
can we connect to Geosever published data to the Add to Map option?
by connecting "var url = "http://localhost:8080/openlayers_app/";" in mapPannel.js
and giving the links when adding the metadata like below
"http://localhost:8080/geoserver/cad_Data/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=cad_Data:matara_sheet&outputFormat=application/json"

**Comment by mhogeweg** [comment]
hi, yes. GeoServer would host OGC services such as WMS, WMTS, WFS, .... In your metadata you would include the link to the WFS (in your example) in the onlinke linkage in the distribution section. Instead of the GetFeature request, you need to use the GetCapabilities request for this service.

**Comment by ShameeraJayawardana** [comment]
Give me an example of GetCapabilities request for this service, I don't have Arc server to publish data, I'm using geoserver

**Comment by mhogeweg** [comment]
can you share your XML? I assume you reference your geoserver WMS/WFS directly? if you have services from ArcGIS Online registered in your catalog and those services are not shared with the public (only within the ArcGIS Online subscription) or if those services themselves require authentication, the viewer would challenge you for credentials. There is nothing the Geoportal can do about that.

**Comment by ShameeraJayawardana** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink">
<gmd:fileIdentifier>
<gco:CharacterString>Anu_Sporadic</gco:CharacterString>
</gmd:fileIdentifier>
<gmd:language>
<gco:CharacterString>en</gco:CharacterString>
</gmd:language>
<gmd:hierarchyLevel>
<gmd:MD_ScopeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset">dataset</gmd:MD_ScopeCode>
</gmd:hierarchyLevel>
<gmd:contact>
<gmd:CI_ResponsibleParty>
<gmd:organisationName>
<gco:CharacterString>Survey Deparment</gco:CharacterString>
</gmd:organisationName>
<gmd:role>
<gmd:CI_RoleCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="resourceProvider">resourceProvider</gmd:CI_RoleCode>
</gmd:role>
</gmd:CI_ResponsibleParty>
</gmd:contact>
<gmd:dateStamp>
<gco:Date>2024-12-02</gco:Date>
</gmd:dateStamp>
<gmd:metadataStandardName>
<gco:CharacterString>ISO 19139/19115 Metadata for Datasets</gco:CharacterString>
</gmd:metadataStandardName>
<gmd:metadataStandardVersion>
<gco:CharacterString>2003</gco:CharacterString>
</gmd:metadataStandardVersion>
<gmd:referenceSystemInfo>
<gmd:MD_ReferenceSystem>
<gmd:referenceSystemIdentifier>
<gmd:RS_Identifier>
<gmd:code>
<gco:CharacterString>4326</gco:CharacterString>
</gmd:code>
</gmd:RS_Identifier>
</gmd:referenceSystemIdentifier>
</gmd:MD_ReferenceSystem>
</gmd:referenceSystemInfo>
<gmd:identificationInfo>
<gmd:MD_DataIdentification>
<gmd:citation>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>Anuradhapura Sporadic Data</gco:CharacterString>
</gmd:title>
<gmd:date>
<gmd:CI_Date>
<gmd:date>
<gco:Date>2024-12-02</gco:Date>
</gmd:date>
<gmd:dateType>
<gmd:CI_DateTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation">creation</gmd:CI_DateTypeCode>
</gmd:dateType>
</gmd:CI_Date>
</gmd:date>
</gmd:CI_Citation>
</gmd:citation>
<gmd:abstract>
<gco:CharacterString>Land survey is performed in order to locate and preparation of plan / map of the boundaries and corners of a parcel of land. It might also include the topography of the parcel, and the location of buildings and other improvements made to the parcel. This land survey information is an important requirement for land development projects and land use planning activities. An extensive range of current and historical survey documents are available in the Survey Department in variety of formats. Most of the documents are available to the general public and have been facilitated by the Survey Department.</gco:CharacterString>
</gmd:abstract>
<gmd:pointOfContact>
<gmd:CI_ResponsibleParty>
<gmd:individualName>
<gco:CharacterString>Snr SS</gco:CharacterString>
</gmd:individualName>
<gmd:organisationName>
<gco:CharacterString>Land Information System</gco:CharacterString>
</gmd:organisationName>
<gmd:contactInfo>
<gmd:CI_Contact>
<gmd:phone>
<gmd:CI_Telephone>
<gmd:voice>
<gco:CharacterString>.112558899</gco:CharacterString>
</gmd:voice>
</gmd:CI_Telephone>
</gmd:phone>
<gmd:onlineResource>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>https://www.survey.gov.lk/sdweb/pages_service_land_info.php?id=5f5cd6934735e284da3ca2fe58fd5382927937e5</gmd:URL>
</gmd:linkage>
</gmd:CI_OnlineResource>
</gmd:onlineResource>
</gmd:CI_Contact>
</gmd:contactInfo>
<gmd:role>
<gmd:CI_RoleCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="pointOfContact">pointOfContact</gmd:CI_RoleCode>
</gmd:role>
</gmd:CI_ResponsibleParty>
</gmd:pointOfContact>
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>Sporadic</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme">theme</gmd:MD_KeywordTypeCode>
</gmd:type>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
<gmd:language>
<gco:CharacterString>en</gco:CharacterString>
</gmd:language>
<gmd:topicCategory>
<gmd:MD_TopicCategoryCode>planningCadastre</gmd:MD_TopicCategoryCode>
</gmd:topicCategory>
<gmd:extent>
<gmd:EX_Extent>
<gmd:geographicElement>
<gmd:EX_GeographicBoundingBox>
<gmd:westBoundLongitude>
<gco:Decimal>-180</gco:Decimal>
</gmd:westBoundLongitude>
<gmd:eastBoundLongitude>
<gco:Decimal>180</gco:Decimal>
</gmd:eastBoundLongitude>
<gmd:southBoundLatitude>
<gco:Decimal>-90</gco:Decimal>
</gmd:southBoundLatitude>
<gmd:northBoundLatitude>
<gco:Decimal>90</gco:Decimal>
</gmd:northBoundLatitude>
</gmd:EX_GeographicBoundingBox>
</gmd:geographicElement>
</gmd:EX_Extent>
</gmd:extent>
</gmd:MD_DataIdentification>
</gmd:identificationInfo>
<gmd:distributionInfo>
<gmd:MD_Distribution>
<gmd:distributionFormat>
<gmd:MD_Format>
<gmd:name>
<gco:CharacterString>Shapefile</gco:CharacterString>
</gmd:name>
<gmd:version>
<gco:CharacterString>1</gco:CharacterString>
</gmd:version>
</gmd:MD_Format>
</gmd:distributionFormat>
<gmd:transferOptions>
<gmd:MD_DigitalTransferOptions>
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>http://localhost:8080/geoserver/cad_Data/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cad_Data%3Amatara_sheet&maxFeatures=50</gmd:URL>
</gmd:linkage>
</gmd:CI_OnlineResource>
</gmd:onLine>
</gmd:MD_DigitalTransferOptions>
</gmd:transferOptions>
</gmd:MD_Distribution>
</gmd:distributionInfo>
</gmd:MD_Metadata>

**Comment by mhogeweg** [comment]
first off: when using Geoportal Server your metadata is in Geoportal Server, not in ArcGIS Online. The URL to the WFS in the XML is to localhost. While that may work for you when you're on the machine running Geoserver it may work (since your browser can see localhost:8080), but other users will not be able to connect to the WFS. Finally, as mentioned above, you appear to register a GetFeature request instead of the GetCapabilities request.

**Comment by ShameeraJayawardana** [comment]
i want to change basemap of the map viewer how can I change?

**Comment by mhogeweg** [comment]
https://github.com/Esri/geoportal-server-catalog/wiki/Customize-search-panel#update-the-map-search-facet

**Comment by ShameeraJayawardana** [comment]
I published a shapefile in Arconline with labels, but when it was added to the geoportal Add to Map, the labels were not displaying and only the shapefile data were displaying. how to show the labelling?

**Comment by mhogeweg** [comment]
in the future, please submit new questions as new issues. this particular issue was about registering geoserver WFS and has been closed (meaning we may not see new questions).

these styles/labels, when defined in the map viewer are not maintained in the originating service, but in the item in ArcGIS Online. Geoportal Server connects to the source services. If the source service has symbololgy defined, the map viewer and preview functions in Geoportal Server will display that. You may use this tree service as an example: https://services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/Landscape_Trees/FeatureServer/0

![image](https://github.com/user-attachments/assets/63872aac-d141-4572-8f09-a3ba0e84264c)
