### ISSUE TITLE
CSW is getting exception when search keyword with QGIS 's MetaSearch

### ISSUE THREAD

**Issue by KenNg117** [Esri/geoportal-server-catalog#582]
When using QGIS's MetaSearch on CSW of geoportal-server-catalog, searching with keywords would get exception as return (csw:AnyText is not a supported queryable.). 

It turns out the QGIS is applying `csw:AnyText `for the` ogc:PropertyName`, yet CSW of geoportal-server-catalog only accepts `AnyText `for the ` ogc:PropertyName`. 

Please consider to improve the text search.

Referrence:
![image](https://github.com/user-attachments/assets/3118315b-65a4-49d4-a966-16b9645282bf)
![image2](https://github.com/user-attachments/assets/24daad81-e8d2-49e7-a7b0-1fb20102dd52)

Request:
```
<?xml version="1.0" ?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows" xmlns:gmd="http://www.isotc211.org/2005/gmd" outputSchema="http://www.opengis.net/cat/csw/2.0.2" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" startPosition="1" maxRecords="10" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
	<csw:Query typeNames="csw:Record">
		<csw:ElementSetName>full</csw:ElementSetName>
		<csw:Constraint version="2.0.2">
			<ogc:Filter>
				<ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\">
					<ogc:PropertyName>csw:AnyText</ogc:PropertyName>
					<ogc:Literal>map</ogc:Literal>
				</ogc:PropertyIsLike>
			</ogc:Filter>
		</csw:Constraint>
	</csw:Query>
</csw:GetRecords>
```

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<ExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ows">
    <Exception exceptionCode="InvalidParameterValue" locator="PropertyName">
        <ExceptionText>
csw:AnyText is not a supported queryable.
		</ExceptionText>
    </Exception>
</ExceptionReport>
```

**Comment by mhogeweg** [comment]
hi, I believe I have resolved this issue. After a small change in I can search my geoportal server CSW from QGIS. The change is to allow csw:AnyText as an alias of AnyText searches. The change is available in PR https://github.com/Esri/geoportal-server-catalog/pull/584.

The modified file is in the geoportal-search component: [GetRecordsParser.js](https://github.com/Esri/geoportal-server-catalog/blob/f/582/geoportal-search/src/main/resources/gs/provider/csw/GetRecordsParser.js), line 159.

![image](https://github.com/user-attachments/assets/73c8e2f2-4454-48ce-8e77-4ffb1bdddca5)
