### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by ShameeraJayawardana** [Esri/geoportal-server-catalog#583]
hi, after we enter the metadata details, what is the location of the XML that saves the data? are all data entered, saved to XML only?

**Comment by mhogeweg** [comment]
all information, XML and extracted fields are in JSON documents in the index. You can view the JSON content as follows: https://[gpt.geocloud.com/geoportal2/rest/metadata/item/2553b0a7daea4c8bb414457530eea055](https://gpt.geocloud.com/geoportal2/rest/metadata/item/2553b0a7daea4c8bb414457530eea055) (where the last part of the URL path is the id of the metadata record. For this example, adding [/html](https://gpt.geocloud.com/geoportal2/rest/metadata/item/2553b0a7daea4c8bb414457530eea055/html) to the path renders the metadata in a friendly HTML view. Adding [/xml](https://gpt.geocloud.com/geoportal2/rest/metadata/item/2553b0a7daea4c8bb414457530eea055/xml) to the path renders just the source XML.

The full XML is stored in the JSON in the index in the `sys_xml_clob` field.
