### ISSUE TITLE
Support Solr in addition to Elasticsearch

### ISSUE THREAD

**Issue by gla-sday** [Esri/geoportal-server-catalog#6]
The Greater London Authority is evaluating this product to support a London DataStore enhancement, however we use Solr as our technical standard. Adopting this product would be much easier if there was an option to use Solr.

**Comment by MapZombie** [comment]
I would also really appreciate support for Solr.  I know of a few other large organizations running with Solr as well.

**Comment by mhogeweg** [comment]
hi. in Geoportal Server 2.0 we switched from Lucene to using elasticsearch (which under the hood uses lucene again) to provided scalable and faceted search. 

in Geoportal Server 1.2.7 we do have an integration with Apache Solr documented here:
https://github.com/Esri/geoportal-server/wiki/Geoportal-Facets-using-Apache-Solr

**Comment by ch-k** [comment]
Hello,
do you have any plans for your roadmap to integrate a kind of abstraction layer to support other storage backends like Solr (or i.e. RDBMS) besides ES in geoportal-server-catalog? Currently, the code seems to be very "twisted" with the ES API. My organization already runs Solr which is used by other systems as well. It would be great to add an OpenSearch interface on top of this existing Solr installation. We don't want to synchronize and maintain different data repositories. My question is not about the implementation of a specific backend like Solr, but to allow other developers to integrate custom backends by implementing some kind of interface.
