### ISSUE TITLE
Date widget in search doesn't constrain results

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#62]
The date control on the left side of the Search window would appear to allow one to limit to results within a certain date range, but changing the date range has no effect on the result set.   (client is Chrome, Windows 10).

**Comment by valentinedwv** [comment]
You need to click on the  link created to add it to the filters.
![image](https://cloud.githubusercontent.com/assets/851784/25589027/c36a22c0-2e5f-11e7-82e3-274265520f5b.png)

The ISO patch will also allow for the creation of Publication and creation date facets for 19115-2 which often use DateTime

**Comment by valentinedwv** [comment]
There is an issue. You can set the range once, graphic shows only the filtered range. If you set it a second time, it will show the full range, even though filter show it to be set.
