### ISSUE TITLE
Author/Publisher Core CSW returnables into Index

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#65]
"contact_people_s" is big bucket which when used as "people" brings creators of the metadata to the top of the heap, and not the creators of the dataset.

creator
An entity primarily responsible for making the content of the resource
MD_Metadata.identificationInfo.AbstractMD_Identification.pointOfContact.CI_ResponsibleParty.

publisher
An entity responsible for making the resource available.
MD_Metadata.identificationInfo.AbstractMD_Identification.pointOfContact.CI_ResponsibleParty.organisationName[role.CI_RoleCode@codeListValue=’publisher’]

contributor
An entity responsible for making contributions to the content of the resource.
MD_Metadata.identificationInfo.AbstractMD_Identification.pointOfContact.CI_ResponsibleParty.organisationName[role.CI_RoleCode@codeListValue=’author’]

**Comment by zguo** [comment]
Yes the role can be different, it is possible to customize to individual roles by following steps in https://github.com/Esri/geoportal-server-catalog/wiki/Mapping-XML-element-to-Elasticsearch-field
