### ISSUE TITLE
Search pane scroll

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#70]
We have a long list of facets.
I tried to add get a scroll bar to show 
\geoportal\src\main\webapp\app\main\templates\SearchPanel.html
g-search-pane-left div

and tried to wrap up some of the facets (below  app/search/SearchBox" ) in a div with style="overflow-y: auto;max-height:  90%;"

the box expands to the size of the open dropPane's

Any ideas on how to do this

**Comment by KathleenPate** [comment]
The DIV height must be a specified pixel size in order for overflow to work. What version of Geoportal are you using? We have 2.5 and there are scroll bars in the facet filters. For more overflow tips check out [w3schools](https://www.w3schools.com/cssref/pr_pos_overflow.asp).
