### ISSUE TITLE
sorting facet values alphabetically by default

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-catalog#72]
for the facets in the left side of the search panel, if you open the settings dialog, you can configure to sort values on that facet by count or alphabetically. The UI defaults to sorting by count, I"m wondering if there's a way to configure the facet in Searth_Panel.html to sort alphabetically by defualt.   Seems like it should be a parameter in  the data-dojo-props, but I can't find any documentation for what the parameter name or values to use would be...

 ```
<div data-dojo-type="app/search/TermsAggregation"
    data-dojo-props="field:'sys_owner_s',open:false,label:'${i18n.search.criteria.owner}'">
  </div>
```

**Comment by umacgillivray** [comment]
Here's an example:
`
      <div data-dojo-type="app/search/TermsAggregation"
        data-dojo-props="field:'sys_metadatatype_s',props:{order:{_term:'asc'}},label:'${i18n.search.criteria.metadataType}'">
      </div>  
`

The 'props' property is Elasticsearch syntax:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

**Comment by smrgeoinfo** [comment]
works great, thanks
