### ISSUE TITLE
How to configure WAB Search Widget qith Geoportal Catalog 2.5?

### ISSUE THREAD

**Issue by kescalera84** [Esri/geoportal-server-catalog#74]
Hi everyone, I have been testing the new Geoportal Catalog and it is working fine, but I have a problem trying to configure the Search Widget that comes with integrated the Map Viewer, I see that it comes with the Geoportal Search widget configured with two Geoportal Servers as an example, wich I think is version 1.2.x, I have been trying to add my own Geoportal with no success, I don't know if there is something additional that I have to enable in Geoportal Catalog for Federated search to work or what is the right Url to set in the Geoportal search widget to work with my geoportal:

{
  "catalogs": [
      {
        "name": "Geoportal Sandbox",
        "url": "http://gptogc.esri.com/geoportal/rest/find/document"
      },
      {
        "name": "California Geoportal",
        "url": "http://portal.gis.ca.gov/geoportal/rest/find/document"
      },
      {
        "name": "USGIN Geoportal",
        "url": "http://catalog.usgin.org/geoportal/rest/find/document"
      },
      {
        "name": "KEVO'S Geoportal",
        "url": "http://arcgiswin.esri.pa:8080/geoportal/....."     ???????????????
	  }  
  ],
      
  "recordsPerPage": 10,
  "showAllAddedLayers": true
}

any help would be apretiated.....

**Comment by mhogeweg** [comment]
The widget was not updated to handle Geoportal Server 2.x sites yet. I just posted some code updates to the develop branch that implement the basic handling. Changes are limited to: [QueryTask.js](https://github.com/Esri/geoportal-server/blob/develop/components/wab/GeoportalSearch/common/QueryTask.js) and [config.json](https://github.com/Esri/geoportal-server/blob/develop/components/wab/GeoportalSearch/config.json)

**Comment by jysuh** [comment]
I have updated my Dev environment with QueryTask.js you just uploaded but I am getting an error. I had to hard code "url" and also "response" variable is not defined. So, here is working version and snapshot of output but still need to 

1. Parse search input
2. Correct result output, so that it shows coverage area as well as correct link
![capture](https://user-images.githubusercontent.com/20560192/27744160-b45df356-5d7b-11e7-9a16-117f0fe322cf.JPG)


define([
  'dojo/_base/declare',
  'dojo/_base/lang',
  'dojo/topic',
  'esri/request'
],function(declare,lang,
           topic,
           esriRequest){
    return declare(null, {

      query: null,

      execute: function(query){
        this.query = query;
        var requestHandle = esriRequest({
              "url": "http://localhost:8080/geoportal/rest/metadata/search?gptVersion=2&q=alberta",
              "content": query,
              handleAs:'json'
            },{
              useProxy:false
            });
          requestHandle.then(lang.hitch(this,this._onQueryFinish), this._onQueryError);
      },

      _queryToString: function(query) {
          var q = {};
          for (a in query) {
            if (typeof query[a]=="object" || typeof query[a]=="function" || typeof query[a]=="array") {
              continue;
            }
            q[a] = query[a];
          }
          return ioQuery.objectToQuery(q);
      },
        
      _onQueryFinish: function(results, io){
        var myRresults = results;

        // handle Geoportal 2.x structure
        if (results.hits) {
        	myRresults = {
            "title": "",
            "description": "",
            "copyright": "",
            "provider": "",
            "updated": "2017-06-28T17:38:42Z",
            "source": this.query.queryUrl,
            "more": "",
            "totalResults": results.total,
            "startIndex": this.query.start,
            "itemsPerPage": results.hits.hits.length,
            "records": []
          };

          for (var i=0, items=results.hits.hits.length; i<items;i++) {
            var item = results.hits.hits[i];
            var record = {
              "title": item._source.title,
              "id": item._id,
              "updated": item._sys_xmlmodified_dt,
              "summary": item._source.description,
              "bbox": [
                item._source.envelope_geo.coordinates[0][0],
                item._source.envelope_geo.coordinates[0][1],
                item._source.envelope_geo.coordinates[1][0],
                item._source.envelope_geo.coordinates[1][1]
              ],
              "geometry": item._source.envelope_geo,
              "links": [
              ]
            };

            // for now, all links are generic 'open' links
            for (var j=0,links=item._source.links_s.length; j<links;j++) {
              var link = item._source.links_s[j];
              var recordLink = {
                "href": link,
                "type": "open"
              }
              record.links.push(recordLink);
            }

            // generate link to the metadata for this item
            var recordLink = {
              "href": this.query.queryUrl.replace("search","item/").replace("gptVersion=2","").replace("?","") + record.id + "/xml",
              "type": "metadata"
            }
            record.links.push(recordLink);

            // now add this to the result
            myRresults.records.push(record);
          }
        }

        topic.publish("/widgets/GeoportalSearch/action/search", null, { success: true, results: myRresults, query: this.query, io:io });
      },

      _onQueryError:function(error, io){
    	alert("Error");
        topic.publish("/widgets/GeoportalSearch/action/search", null, { success: false, error: error, io:io  });
      }

   });
});

**Comment by zguo** [comment]
Suggest to upgrade to 2.6.2, which has the search widget integrated.
