### ISSUE TITLE
Differences between 2.5.0 and 1.2.7

### ISSUE THREAD

**Issue by luballe** [Esri/geoportal-server-catalog#75]
Hello, From the functionality point of view, is there any difference between (geoportal-server-catalog 2.5.0 + geoportal-server-harvester 2.5.0) and geoportal-server 1.2.7?

Are there funcionalities that version 1.2.7 has and 2.5.0 hasn't implemented yet?

Thanks a lot for your attention.

Luis

**Comment by rexneville** [comment]
Yes there are many functions in Geoportal server 1.2.7 that do not exist in catalog/harvester v2.5
All the items "under consideration" in catalog 2.5 release notes are not implemented in v2.5  
https://github.com/Esri/geoportal-server-catalog/releases

**Comment by mhogeweg** [comment]
Correct. We are filling that gap based on priorities we hear from our users like yourselves. On the other hand, 2.5.x does things that 1.2.x cannot do, such as:
- faceted search (that is configurable to the index at hand)
- handle very large (millions) catalogs with multi-node indexes
- handle arbitrary json (we have built indexes for image catalogs and a bunch of ArcGIS Servers in ways 1.2.x can't)
- use the ArcGIS JS API-based metadata editor (yes, the same one as in ArcGIS Online/Portal!)
- harvest to multiple targets at once
- harvest directly from CKAN

to name a few

**Comment by rexneville** [comment]
Yes good points Marten. On behalf of the GeoDiscover Alberta team,  for functions on the "under consideration"  list,  we would like to vote for the following two functions to be implemented next/soon. 
1. Restricted metadata option for some metadata records to be visible only to authenticates users. A boolean restricted yes/no flag for each record would be sufficient. 
2. Approved or Review status flag for each record. 
Thanks.

**Comment by zguo** [comment]
Both of them have been implemented.
