### ISSUE TITLE
Typo found in variable name for default URL (Client.java)

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#88]
Found a typo in **Client.java** for the DEFAULT_INDEX public variable 

lines 70 & 97
```
public class Client implements Closeable {
  private final Logger LOG = LoggerFactory.getLogger(Client.class);
  private static final String DEFAILT_INDEX = "metadata";
```

The term 'Default' is spelt with an "I" instead of a "U"

The file is found in
/geoportal-commons/geoportal-commons-gpt-client/src/main/java/com/esri/geoportal/commons/gpt/client/Client.java

**Comment by zguo** [comment]
fixed.

**Comment by KathleenPate** [comment]
:) Excellent. Thank you.
