### ISSUE TITLE
URL to Single Record

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#89]
API has an HTML
but just a single record in HTML

**Comment by zguo** [comment]
can you please provide some details.

**Comment by valentinedwv** [comment]
http://cinergi.sdsc.edu/geoportal/?filter=%220ba7a5a0-fcf0-402c-853c-7dc8751ea8b5%22

While it can be done with a filter, it would probably be more appropriate for a single direct query parameter, say ID.

**Comment by valentinedwv** [comment]
#239 adds query parameter fileid
