### ISSUE TITLE
Where are new metadata entry XMLs stored?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#9]
As the new Geoportal does not use a database, I was wondering **where the user created metadata (through metadata editor) files stored?**

When a user creates metadata is it stored as an XML file on the server?  If not, can this be configured to do so?

Thank you.

**Comment by umacgillivray** [comment]
The xml files are stored within ElasticSearch. Within the index there is an es type "item", and another type "clob". The xmls are within the "clob" type.

**Comment by MapZombie** [comment]
Thanks @umacgillivray .  Would you know of an effective way of exporting these from ElasticSearch?

**Comment by mhogeweg** [comment]
to where?

**Comment by umacgillivray** [comment]
Java from within geoportal would look something like this `  

import com.esri.geoportal.lib.elastic.util.Scroller;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Consumer;
import org.elasticsearch.search.SearchHit;

public static void testExport() throws Exception {
    AtomicLong count = new AtomicLong(0);
    String dir = "C:/Projects/elastic/metadata/sampledata2/";
    Scroller scroller = new Scroller();
    scroller.setIndexName("metadata");
    scroller.setIndexType("clob");
    //scroller.setMaxDocs(10);
    scroller.scroll(
      new Consumer<SearchHit>(){
        @Override
        public void accept(SearchHit hit) {
          try {
            System.err.println(count.incrementAndGet());
            String id = hit.getId();
            String xml = (String)hit.getSource().get("sys_clob");
            //System.err.println(id);
            Path p = Paths.get(dir+id.replace("_xml","")+".xml");
            Files.write(p,xml.getBytes("UTF-8"));
          } catch (Exception e) {
            e.printStackTrace();
          }
        }
      }
    );
  }
`

**Comment by MapZombie** [comment]
Basically I'm just looking to export these to the local server as individual XMLs.

**Comment by MapZombie** [comment]
I appreciate the help @umacgillivray .  Would you be able to guide me as to where I would enter this code?  Which file(s) would need to be edited?  I am not very proficient in Java unfortunately.

Thanks.

**Comment by MapZombie** [comment]
Can XMLs be exported server side via editing the JavaScript?  I'm getting a grasp of the save function but trying to figure out where it is being saved and if this can be redirected to a folder and saved as ".xml".

**MetadataEditor.js**
_save: function(xmlString,itemId) {
```
      var client = new AppClient();
      var url = client.getRestUri()+"/metadata/item";
      if (typeof itemId === "string" && itemId.length > 0) {
        url += "/"+encodeURIComponent(itemId);  /* item name id */
      }
      url = client.appendAccessToken(url);     /* Elasticsearch URL? */
      var data = {                            /* Defines Data */
        app_editor_s: "gxe",                  /* Data is from GXE */
        xml: xmlString                        /* XML String */
      };
      var headers = {"Content-Type": "application/json"}; /* Header */
      var info = {handleAs:"json",headers:headers,data:JSON.stringify(data)}; /* Handles as JSON format */
      return dojoRequest.put(url,info);    /* push to server */
    },
```

**Comment by valentinedwv** [comment]
Would this be better done as an enhancement to the geoportal-harvester?

Connect to a geoportal 2.0, export to folder.

**Comment by mhogeweg** [comment]
yes! especially since harvesting to a folder is already supported. you would create an input broker for Geoportal Server Catalog 2.x.
