### ISSUE TITLE
mulitprops not always array

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#90]
links_s field may be a string or list of strings

**Comment by valentinedwv** [comment]
--- geoportal/src/main/resources/metadata/js/EvaluatorBase.js	(date 1496695165000)
+++ geoportal/src/main/resources/metadata/js/EvaluatorBase.js	(date 1501269855000)
@@ -168,6 +168,7 @@
     var self = this;
     this.forEachNode(task,contextNode,xpathExpression,function(node){
       self.writeMultiProp(obj,name,self.getNodeText(node),options);
+        print("props" + obj + name );
     });
   },
 
@@ -271,11 +272,16 @@
     if (typeof value === "string" && value.length === 0) return;
     var v = obj[name];
     if (typeof v === "undefined" || v === null) {
-      obj[name] = value;
+      //obj[name] = value;
+        obj[name] = new Array();
+        obj[name].push(value);
+
     } else if (typeof v.push === "function") {
       v.push(value);
+
     } else {
       obj[name] = [v,value];
+
     }
   },

**Comment by zguo** [comment]
Thanks, closing the issue.
