### ISSUE TITLE
Multiple selections from a single filter?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-catalog#92]
Is it possible to select multiple selections from a single filter? For instance from the Metadata Type filter is there a way to filter it so I can see entries that are EITHER "Arcgis" OR "ISO 19115"?

![image](https://user-images.githubusercontent.com/17599236/29179857-113c59c6-7db3-11e7-8963-f4e2959faf04.png)

**Comment by zguo** [comment]
We are trying to keep the facet counts synchronized with the search results.
It is possible to search multiple sections by typing in the search box with something like
 sys_metadatatype_s:arcgis OR sys_metadatatype_s:iso19115
