### ISSUE TITLE
CSS Changes at esri (update links)

### ISSUE THREAD

**Issue by KathleenPate** [Esri/geoportal-server-catalog#95]
Recently ESRI updated the CSS Bootstrap library. In order to have any Calcite CSS. In Index.html you will have to change your Source URL to http://esri.github.io/calcite-bootstrap/styles/calcite-bootstrap.min.css
`<link rel="stylesheet" href="//esri.github.io/calcite-bootstrap/styles/calcite-bootstrap.min.css">`
I see @umacgillivray was on top of this yesterday so a better solution may be on its way.

**Comment by umacgillivray** [comment]
http://esri.github.io/calcite-bootstrap/assets/css/calcite-bootstrap.css has been restored. We'll bring the css files into this repo for the next release.

**Comment by KathleenPate** [comment]
YEAH!
The new version breaks all the buttons! ;-)

**Comment by KathleenPate** [comment]
#97 merge probably fixes this.
